Repository Satellite-im/Uplink, pull requests merged in 2022-12, with the labels that each got.

#465 fix(context): improve context menu styles, add global svg rules for e…
  Makefile
  src/components/main/files/sidebar/styles.scss
  src/components/main/files/upload/styles.scss
  src/components/reusable/nav/mod.rs
  src/components/reusable/nav/styles.scss
  src/components/styles.scss
  src/ui_kit/src/button/styles.scss
  src/ui_kit/src/context_menu/mod.rs
  src/ui_kit/src/context_menu/styles.scss
  src/ui_kit/src/folder/styles.scss
  src/ui_kit/src/popup/styles.scss
Labels: question, QA approved

#477 feat(state): persist hide prerelease message
  src/components/main/compose/mod.rs
  src/state/mod.rs
Labels: QA approved, missing dev review

#482 feat(buttons): add html title attribute to buttons
  src/ui_kit/src/button/mod.rs
Labels: QA approved, missing dev review

#478 feat(chat): show attachment preview and click to show original message
  src/components/main/compose/messages/mod.rs
  src/components/main/compose/reply/mod.rs
  src/components/main/compose/reply/styles.scss
Labels: QA approved, missing dev review

#490 chore(Textarea): Moved internal textarea component to reusable compon…
  src/components/main/compose/msg/mod.rs
  src/components/main/compose/write/mod.rs
  src/components/reusable/mod.rs
  src/components/reusable/textarea.rs
  src/iui_kit/mod.rs
  src/main.rs
Labels: QA approved, missing dev review

#489 chore(cargo): Update dependency
  Cargo.toml
  extensions/native/audio-factory/src/lib.rs
  src/components/main/compose/messages/mod.rs
  src/components/main/compose/msg/attachment/mod.rs
  src/components/main/compose/reply/mod.rs
  src/components/main/files/toolbar/usage/mod.rs
  src/components/main/sidebar/favorites/mod.rs
  src/components/main/sidebar/mod.rs
  src/components/media/media/mod.rs
  src/components/media/mod.rs
  src/components/media/time/mod.rs
  src/components/prelude/auth/mod.rs
  src/components/reusable/textarea.rs
  src/state/mod.rs
  src/ui_kit/Cargo.toml
  src/ui_kit/src/button/mod.rs
  src/ui_kit/src/file/mod.rs
  src/utils/Cargo.toml
Labels: task, QA approved, missing dev review

#505 chore(rg): Use RayGun::get_conversation
  src/components/main/mod.rs
Labels: task, ready for testing, missing dev review

#511 chore(typo): fix typo
  src/components/main/files/upload/mod.rs
Labels: missing dev review

#498 update(Friends): auto-delete text after searching/adding a friend
  src/components/main/friends/sidebar/mod.rs
  src/ui_kit/src/input_add_friend/mod.rs
  src/ui_kit/src/input_add_friend/styles.scss
  src/ui_kit/src/lib.rs
Labels: QA approved, team: files

#499 fix(settings): button width
  src/components/main/settings/pages/profile/styles.scss
Labels: QA approved, missing dev review

#512 chore(cargo): Update dependencies
  Cargo.toml
  src/ui_kit/Cargo.toml
  src/utils/Cargo.toml
Labels: task, missing dev review

#506 chore(css): improve font size accessibility
  src/components/main/files/browser/styles.scss
  src/components/main/friends/styles.scss
  src/components/styles.scss
  src/ui_kit/src/extension_placeholder/styles.scss
  src/ui_kit/src/loader/styles.scss
Labels: missing dev review

#501 feat(call): resize call media ui
  src/components/media/mod.rs
  src/components/media/styles.scss
  src/ui_kit/src/lib.rs
  src/ui_kit/src/resizable/mod.rs
  src/ui_kit/src/resizable/resizable.js
  src/ui_kit/src/resizable/styles.scss
Labels: missing dev review

#503 fix(chat): call window blocking message area bug
  src/components/main/compose/messages/styles.scss
  src/components/main/compose/mod.rs
  src/components/main/compose/styles.scss
  src/components/main/compose/write/styles.scss
  src/components/reusable/toolbar/styles.scss
Labels: missing dev review

#514 fix(ui_kit): profile picture object fit cover
  src/ui_kit/src/photo_picker/styles.scss
Labels: missing dev review

#519 chore(comments): add inline code comments - src/components/reusable
  src/components/reusable/page_header/mod.rs
Labels: QA approved, missing dev review

#520 chore(comments): add inline code comments - src/utils/src/sounds.rs
  src/utils/src/sounds.rs
Labels: QA approved, missing dev review

#518 chore(comments): add inline code comments - src/components/media
  src/components/media/controls/mod.rs
  src/components/media/media/mod.rs
  src/components/media/mod.rs
  src/components/media/time/mod.rs
Labels: QA approved, missing dev review

#523 Disable dmg build because it ate through all our minutes
  .github/workflows/ci-make-dmg.yml
Labels: missing dev review

#522 chore(comments): add inline code comments in src/components/main/compose/msg/embeds/mod.rs
  src/components/main/compose/msg/embeds/mod.rs
Labels: missing dev review

#534 fix(cargo): Fix cargo build error
  Cargo.toml
  src/utils/Cargo.toml
Labels: task, missing dev review

#509 feat(IncognitoTyping): add incognito typing extension
  Cargo.toml
  extensions/native/incognito-typing/Cargo.toml
  extensions/native/incognito-typing/src/lib.rs
  src/components/main/compose/write/mod.rs
  src/components/main/compose/write/styles.scss
  src/components/main/settings/pages/extensions/mod.rs
  src/components/reusable/textarea.rs
  src/main.rs
  src/state/Cargo.toml
  src/state/src/lib.rs
  src/utils/src/extensions.rs
  src/utils/src/lib.rs
Labels: QA approved, missing fixing conflict

#529 chore(chat): typing indicator chore
  src/components/main/compose/mod.rs
  src/components/main/compose/styles.scss
  src/components/main/compose/write/styles.scss
  src/ui_kit/src/textarea/styles.scss
  src/ui_kit/src/typing_indicator/mod.rs
  src/ui_kit/src/typing_indicator/styles.scss
Labels: UI Issues, QA approved, missing dev review

#486 feat(mobile): combine friends pages
  src/components/main/files/styles.scss
  src/components/main/friends/find/mod.rs
  src/components/main/friends/find/styles.scss
  src/components/main/friends/list/mod.rs
  src/components/main/friends/mod.rs
  src/components/main/friends/request/style.scss
  src/components/main/friends/requests/mod.rs
  src/components/main/friends/sidebar/mod.rs
  src/components/main/friends/sidebar/styles.scss
  src/components/main/friends/styles.scss
  src/components/main/settings/mod.rs
  src/components/reusable/page_header/mod.rs
  src/components/reusable/page_header/styles.scss
  src/components/reusable/toolbar/mod.rs
  src/ui_kit/src/input/styles.scss
Labels: UI Issues, QA approved, missing dev review, team: ui

#536 feat(chat): implement sidebar fuzzy search
  Cargo.toml
  src/components/main/settings/pages/profile/status_msg/mod.rs
  src/components/main/sidebar/mod.rs
  src/ui_kit/src/input/mod.rs
Labels: enhancement, QA approved, missing dev review, team: ui

#527 refactor(chat): improve sidebar styles
  src/components/main/sidebar/chat/styles.scss
  src/components/main/sidebar/favorites/mod.rs
  src/components/main/sidebar/favorites/styles.scss
  src/components/main/sidebar/mod.rs
  src/components/main/sidebar/styles.scss
  src/components/styles.scss
Labels: QA approved, missing dev review

#507 fix(chat): scrolling behaviour fixed
  src/components/main/compose/messages/messages.js
  src/components/main/compose/messages/mod.rs
  src/components/main/compose/messages/styles.scss
  src/components/main/compose/mod.rs
  src/components/main/compose/styles.scss
  test/physical/launch_physical_test.sh
Labels: UI Issues, QA approved, missing dev review

#448 chore(appium): add appium testing framework
  .github/workflows/ci-make-dmg.yml
  .github/workflows/comment-PR-dmg.yml
  .github/workflows/ui-appium-tests.yml
  .gitignore
  appium-tests/README.md
  appium-tests/babel.config.js
  appium-tests/config/wdio.mac.app.conf.ts
  appium-tests/config/wdio.mac.ci.conf.ts
  appium-tests/config/wdio.shared.conf.ts
  appium-tests/config/wdio.shared.local.appium.conf.ts
  appium-tests/package.json
  appium-tests/scripts/run_appium_macos_server.sh
  appium-tests/tests/screenobjects/AppScreen.ts
  appium-tests/tests/screenobjects/CreateAccountScreen.ts
  appium-tests/tests/screenobjects/CreatePinScreen.ts
  appium-tests/tests/screenobjects/EnterPinScreen.ts
  appium-tests/tests/screenobjects/UplinkMainScreen.ts
  appium-tests/tests/specs/create-account-screen.spec.ts
  appium-tests/tsconfig.json
Labels: draft, missing dev review

#532 fix(thumbnails): fix css and bindings to display icon and img's
  src/components/main/files/upload/mod.rs
  src/ui_kit/src/file/mod.rs
  src/ui_kit/src/file/styles.scss
Labels: ready for testing, team: files

#548 fix(typing indicator): fix typing indicator when adding new fields to PersistedState
  extensions/native/incognito-typing/src/lib.rs
  src/components/main/compose/write/mod.rs
  src/components/main/files/mod.rs
  src/components/main/files/upload/mod.rs
  src/components/main/settings/pages/extensions/mod.rs
  src/components/main/sidebar/mod.rs
  src/components/media/time/mod.rs
  src/iui_kit/textarea.rs
  src/main.rs
  src/state/src/lib.rs
  src/ui_kit/src/file/mod.rs
  src/ui_kit/src/input_add_friend/mod.rs
  src/utils/src/extensions.rs
  src/utils/src/lib.rs
Labels: missing dev review, missing fixing conflict

#531 feat(search): basic search functionality for friends
  src/components/main/friends/find/mod.rs
  src/ui_kit/src/input/mod.rs
  src/ui_kit/src/input/styles.scss
Labels: QA approved, missing dev review

#538 feat(friends): add block/unblock feature and blocked users list page
  src/components/main/friends/list/mod.rs
  src/components/main/friends/list_type_button/mod.rs
  src/components/main/friends/list_type_button/styles.scss
  src/components/main/friends/mod.rs
  src/components/main/friends/styles.scss
  src/components/main/friends/users_list/blocked_list/blocked_list_tile/mod.rs
  src/components/main/friends/users_list/blocked_list/mod.rs
  src/components/main/friends/users_list/friend_list/friend_list_tile/mod.rs
  src/components/main/friends/users_list/friend_list/friend_list_tile/styles.scss
  src/components/main/friends/users_list/friend_list/mod.rs
  src/components/main/friends/users_list/mod.rs
Labels: QA approved, team: files

#540 chore(windows): Update Windows Build
  .github/workflows/ci-make-dmg.yml
  .github/workflows/ci-make-windows.yml
  src/main.rs
Labels: QA approved, missing dev review

#546 perf(messages): optimize performance
  src/components/main/compose/messages/mod.rs
  src/components/main/compose/msg/mod.rs
Labels: UI Issues, team: ui

#557 chore(appium): update GH worflow appium file
  .github/workflows/ui-appium-tests.yml
  appium-tests/tests/screenobjects/EnterPinScreen.ts
  appium-tests/tests/specs/create-account-screen.spec.ts
Labels: QA approved, missing dev review

#560 perf(messages): optimize handling of recipients
  src/components/main/compose/messages/mod.rs
  src/components/main/compose/msg/mod.rs
Labels: UI Issues, QA approved, missing dev review, team: ui

#566 fix(message): Remove double replied message
  src/components/main/compose/messages/mod.rs
Labels: bug, UI Issues, QA approved, missing dev review

#568 chore(clippy): Cleanup linting
  src/components/main/compose/messages/mod.rs
Labels: task, QA approved, missing dev review

#570 fix(chats): fix behavior when hiding/showing chats
  src/components/main/friends/friend/mod.rs
  src/components/main/friends/users_list/friend_list/friend_list_tile/mod.rs
  src/components/main/sidebar/favorites/mod.rs
  src/components/main/sidebar/mod.rs
  src/components/main/welcome/mod.rs
  src/components/prelude/auth/mod.rs
  src/components/prelude/loading.rs
  src/components/prelude/unlock/mod.rs
  src/components/reusable/nav/mod.rs
  src/state/src/lib.rs
Labels: missing dev review

#563 feat(extensions): extensions enable/disable
  src/components/main/compose/write/mod.rs
  src/components/main/settings/pages/extensions/extension.rs
  src/components/main/sidebar/mod.rs
  src/state/src/lib.rs
  src/utils/src/extensions.rs
Labels: QA approved

#571 chore(test): test
  .github/workflows/test.yml
Labels: draft

#552 fix(thumbnail): hotfix
  src/components/main/files/upload/mod.rs
  src/ui_kit/src/file/styles.scss
Labels: changes requested

#573 chore(docs): minor update
  appium-tests/README.md
Labels: missing dev review

#515 feat(chat): divider component
  src/components/main/compose/divider/mod.rs
  src/components/main/compose/divider/styles.scss
  src/components/main/compose/messages/mod.rs
  src/components/main/compose/mod.rs
  src/components/main/sidebar/chat/mod.rs
  src/state/src/lib.rs
Labels: QA approved

#576 feat(files): Progress when Uploading
  Cargo.toml
  src/components/main/files/upload/mod.rs
Labels: changes requested, missing dev review

#577 chore(rust): use logs rather than println
  src/components/main/files/upload/mod.rs
Labels: missing dev review

#574 chore(ci): update ci
  .github/workflows/rebase.yml
Labels: missing dev review

#582 chore(builds): Attach builds to release
  .github/workflows/ci-make-dmg.yml
  .github/workflows/ci-make-windows.yml
Labels: missing dev review

#585 fix(build): compile time warnings
  src/components/main/compose/divider/mod.rs
  src/components/main/files/upload/mod.rs
Labels: missing dev review

#587 feat(extensions): add emoji extension
  extensions/native/emoji-selector/Cargo.toml
  extensions/native/emoji-selector/src/emojis.toml
  extensions/native/emoji-selector/src/lib.rs
  src/components/main/compose/write/mod.rs
Labels: changes requested, missing dev review

#597 chore(appium): Update appium readme with videos
  appium-tests/README.md
Labels: missing dev review

#591 update(FindFriends): put friend-request back to on_enter
  src/components/main/friends/find/mod.rs
Labels: QA approved, missing dev review

#586 feat(popout): create reusable popout component
  src/components/main/compose/msg/mod.rs
  src/components/main/compose/msg/styles.scss
  src/components/main/files/mod.rs
  src/components/main/sidebar/mod.rs
  src/components/main/styles.scss
  src/components/reusable/mod.rs
  src/components/reusable/page_header/mod.rs
  src/components/reusable/popout/mod.rs
  src/components/reusable/popout/styles.scss
Labels: enhancement, QA approved, missing dev review, team: ui

#581 feat(storage): Create folder upload file into it
  src/components/main/files/browser/mod.rs
  src/components/main/files/mod.rs
  src/components/main/files/upload/mod.rs
  src/main.rs
  src/ui_kit/src/file/mod.rs
  src/ui_kit/src/folder/file_leave_folder.js
  src/ui_kit/src/folder/file_over_folder.js
  src/ui_kit/src/folder/hide_edit_name.js
  src/ui_kit/src/folder/mod.rs
  src/ui_kit/src/folder/show_edit_name.js
  src/ui_kit/src/new_folder/mod.rs
  src/ui_kit/src/new_folder/new_folder.js
  src/utils/src/lib.rs
Labels: QA approved, missing dev review, team: files

#599 fix(settings): max-width layout
  src/components/main/settings/pages/styles.scss
Labels: QA approved, missing dev review

#601 feat(uikit): add missing props to select component
  extensions/native/audio-factory/src/lib.rs
  src/components/main/friends/find/mod.rs
  src/components/main/settings/pages/general/mod.rs
  src/ui_kit/src/input/mod.rs
  src/ui_kit/src/select/mod.rs
  src/ui_kit/src/select/styles.scss
Labels: QA approved, missing dev review

#615 chore(request): Use event stream for request
  src/components/main/friends/requests/mod.rs
  src/components/main/friends/users_list/friend_list/friend_list_tile/more_menu/mod.rs
  src/components/main/friends/users_list/friend_list/mod.rs
  src/state/src/lib.rs
  src/ui_kit/src/file/mod.rs
  src/ui_kit/src/folder/mod.rs
  src/utils/src/lib.rs
Labels: task, ready for testing, missing dev review

#605 refactor(NewFolder): Fix focus on new folder component, and remove it…
  src/components/main/files/browser/mod.rs
  src/components/main/files/mod.rs
  src/ui_kit/src/new_folder/mod.rs
  src/ui_kit/src/new_folder/new_folder.js
Labels: QA approved, missing dev review, team: files

#596 Revert "chore(ci): move tickets"
  .github/workflows/move-tickets.yml
Labels: missing dev review

#616 fix(MoreMenu): fix more menu staying issue
  src/components/main/friends/users_list/friend_list/friend_list_tile/more_menu/more_menu.js
Labels: ready for testing, team: files

#617 test(appium): unskipping first tests
  appium-tests/tests/screenobjects/CreatePinScreen.ts
  appium-tests/tests/specs/create-account-screen.spec.ts
Labels: missing dev review

#618 chore(cargo): Update dependency
  Cargo.toml
  src/state/Cargo.toml
  src/ui_kit/Cargo.toml
  src/utils/Cargo.toml
Labels: task, QA approved, missing dev review

#620 chore(friends): list css
  src/components/main/friends/styles.scss
  src/components/main/friends/users_list/friend_list/mod.rs
Labels: QA approved, missing dev review

#633 update(Folder): Upload files by drop on folder target
  src/components/main/files/browser/mod.rs
  src/components/main/files/upload/mod.rs
  src/ui_kit/Cargo.toml
  src/ui_kit/src/file/mod.rs
  src/ui_kit/src/folder/file_leave_folder.js
  src/ui_kit/src/folder/mod.rs
  src/utils/Cargo.toml
  src/utils/src/files_functions.rs
  src/utils/src/lib.rs
Labels: QA approved, team: files

#641 chore(cargo): Update dependency
  Cargo.toml
  src/state/Cargo.toml
  src/ui_kit/Cargo.toml
  src/utils/Cargo.toml
Labels: task, QA approved, missing dev review

#647 chore(cargo): Update dependency
  Cargo.toml
  src/components/main/compose/divider/mod.rs
  src/components/main/compose/messages/mod.rs
  src/components/main/compose/msg/mod.rs
  src/components/main/files/browser/mod.rs
  src/components/main/files/mod.rs
  src/components/main/files/upload/mod.rs
  src/components/main/friends/find/mod.rs
  src/components/main/friends/mod.rs
  src/components/main/friends/requests/mod.rs
  src/components/main/friends/users_list/blocked_list/blocked_list_tile/mod.rs
  src/components/main/friends/users_list/blocked_list/mod.rs
  src/components/main/friends/users_list/friend_list/friend_list_tile/more_menu/mod.rs
  src/components/main/friends/users_list/friend_list/mod.rs
  src/components/main/settings/pages/developer/mod.rs
  src/components/main/settings/pages/general/mod.rs
  src/components/main/settings/pages/profile/status_msg/mod.rs
  src/components/main/settings/pages/profile/username/mod.rs
  src/components/main/sidebar/chat/mod.rs
  src/components/main/sidebar/mod.rs
  src/components/media/mod.rs
  src/components/prelude/auth/mod.rs
  src/components/prelude/loading.rs
  src/components/reusable/nav/mod.rs
  src/components/reusable/popout/mod.rs
  src/iutils/mod.rs
  src/state/Cargo.toml
  src/state/src/lib.rs
  src/ui_kit/Cargo.toml
  src/ui_kit/src/activity_indicator/mod.rs
  src/ui_kit/src/folder/mod.rs
  src/ui_kit/src/new_folder/mod.rs
  src/ui_kit/src/photo_picker/mod.rs
  src/utils/Cargo.toml
  src/utils/src/files_functions.rs
Labels: task, QA approved, missing dev review

#646 chore(read-me): add info
  README.md
Labels: QA approved, missing dev review

#648 feat(ui): outside click
  extensions/native/audio-factory/src/lib.rs
  extensions/native/emoji-selector/src/lib.rs
  src/ui_kit/src/lib.rs
  src/ui_kit/src/outside/mod.rs
  src/ui_kit/src/outside/outside.js
Labels: QA approved, missing dev review
