Repository Satellite-im/Uplink, pull requests merged in 2022-10, with the labels that each got.

#52 update strings to use language service
  src/components/main/compose/mod.rs
  src/components/main/compose/msg/mod.rs
  src/components/main/friends/mod.rs
  src/components/main/profile/mod.rs
  src/components/main/sidebar/mod.rs
  src/language/en_us.rs
  src/language/mod.rs
Labels: ready for testing

#76 fix(Unlock Screen): Fixes #56, #54, #58, #61, #62.
  src/.styles.css
  src/components/prelude/unlock/mod.rs
  src/components/prelude/unlock/styles.scss
Labels: changes requested

#79 fix(Friends): Fixes error not clearing when modifying friend.
  src/components/main/friends/mod.rs
  src/components/main/sidebar/mod.rs
Labels: QA approved, missing dev review

#81 fix(Global): Fixed user select to be off by default, now if we want t…
  src/.styles.css
  src/components/main/compose/write/styles.scss
  src/components/main/sidebar/chat/styles.scss
  src/components/main/sidebar/nav/styles.scss
  src/components/main/sidebar/styles.scss
  src/components/main/styles.scss
Labels: QA approved, missing dev review

#82 fix(Friends): Clear friend adding error whenever we leave the friends…
  src/components/main/friends/mod.rs
Labels: changes requested, missing dev review

#80 fix(Compose): fixes #68
  src/components/main/compose/write/mod.rs
Labels: QA approved, missing dev review

#78 60 67
  .DS_Store
  src/.styles.css
  src/components/prelude/auth/mod.rs
  src/components/prelude/auth/styles.scss
  src/utils/mod.rs
Labels: changes requested

#126 Feat/multiline support
  src/components/main/compose/mod.rs
  src/components/main/compose/msg/mod.rs
  src/components/main/compose/msg/styles.scss
  src/components/main/compose/write/mod.rs
  src/components/main/files/browser/mod.rs
  src/components/main/files/sidebar/mod.rs
  src/components/main/files/sidebar/usage/mod.rs
  src/components/main/files/toolbar/mod.rs
  src/components/main/mod.rs
  src/components/main/sidebar/mod.rs
  src/components/prelude/unlock/mod.rs
  src/components/ui_kit/file.rs
  src/components/ui_kit/folder.rs
  src/components/ui_kit/icon_textarea.rs
  src/components/ui_kit/mod.rs
  src/components/ui_kit/textarea.rs
  src/main.rs
Labels: QA approved, missing dev review

#144 chore: Use specific commits from warp
  Cargo.toml
  src/components/prelude/unlock/mod.rs
  src/main.rs
Labels: task

#146 fix: Use variable directly in states
  src/components/main/friends/mod.rs
Labels: task, UI Issues
