Repository Satellite-im/Uplink, pull requests merged in 2022-11, with the labels that each got.

#161 fix (messaging): don't unwrap when formatting last_msg_time
  src/components/main/sidebar/chat/mod.rs
Labels: QA approved

#157 fix(css): minor css fixes
  src/components/main/files/sidebar/styles.scss
  src/components/main/files/sidebar/usage/styles.scss
  src/components/main/files/toolbar/styles.scss
  src/components/main/friends/styles.scss
  src/components/ui_kit/styles.scss
Labels: QA approved

#180 chore: Update warp commit
  Cargo.toml
Labels: task

#219 fix(profile-settings): center profile picture placeholder icon
  src/components/ui_kit/photo_picker/mod.rs
  src/components/ui_kit/photo_picker/styles.scss
Labels: UI Issues

#223 fix(unlock): align login action buttons
  src/components/prelude/unlock/styles.scss
Labels: UI Issues

#236 fix: Use HashSet to fix sorting on rerender
  src/components/main/friends/mod.rs
Labels: bug, QA approved, missing dev review

#242 fix(pfp): update pfps across app with new component
  src/components/main/profile/mod.rs
  src/components/main/profile/style.scss
  src/components/main/sidebar/favorites/mod.rs
Labels: QA approved

#257 Update: Fix navigation to profile and general menu on settings sidebar
  src/components/main/profile/mod.rs
  src/components/main/settings/mod.rs
  src/components/main/settings/sidebar/mod.rs
  src/components/main/settings/sidebar/nav/mod.rs
  src/main.rs
Labels: QA approved

#272 Fix re-rendering in Popup and dioxus-toast
  Cargo.toml
  src/components/main/compose/messages/mod.rs
  src/components/main/compose/mod.rs
  src/components/main/friends/sidebar/mod.rs
  src/components/prelude/auth/mod.rs
  src/components/ui_kit/icon_input/mod.rs
  src/components/ui_kit/popup/mod.rs
Labels: changes requested

#285 chore(readme): add details around windows setup
  README.md
Labels: QA approved

#276 fix:fix the jumping cursor in add friend textfield
  src/components/main/friends/sidebar/mod.rs
  src/components/ui_kit/icon_input/mod.rs
Labels: QA approved, missing dev review

#293 Fix no padding between requests
  src/components/main/compose/messages/mod.rs
  src/components/main/compose/mod.rs
  src/components/main/friends/request/style.scss
  src/components/main/friends/sidebar/mod.rs
  src/components/main/settings/mod.rs
  src/components/main/sidebar/mod.rs
  src/components/ui_kit/photo_picker/mod.rs
  src/main.rs
Labels: QA approved, missing dev review

#294 Add error message when sending friend request to friend
  src/components/main/friends/sidebar/mod.rs
  src/language/en_us.rs
  src/language/mod.rs
Labels: QA approved, missing dev review

#305 fix re-render in friends and add debug logging
  Cargo.toml
  README.md
  src/components/main/compose/messages/mod.rs
  src/components/main/compose/mod.rs
  src/components/main/compose/msg/embeds/mod.rs
  src/components/main/compose/msg/mod.rs
  src/components/main/compose/reply/mod.rs
  src/components/main/compose/topbar/mod.rs
  src/components/main/compose/write/mod.rs
  src/components/main/friends/friend/mod.rs
  src/components/main/friends/mod.rs
  src/components/main/friends/request/mod.rs
  src/components/main/friends/sidebar/mod.rs
  src/components/main/mod.rs
  src/components/main/profile/mod.rs
  src/components/main/settings/mod.rs
  src/components/main/settings/pages/developer/mod.rs
  src/components/main/settings/pages/general/mod.rs
  src/components/main/settings/pages/profile/mod.rs
  src/components/main/settings/sidebar/mod.rs
  src/components/main/settings/sidebar/nav/mod.rs
  src/components/main/sidebar/chat/mod.rs
  src/components/main/sidebar/favorites/mod.rs
  src/components/main/sidebar/mod.rs
  src/components/main/welcome/mod.rs
  src/components/prelude/auth/mod.rs
  src/components/prelude/loading.rs
  src/components/prelude/unlock/mod.rs
  src/components/reusable/nav/mod.rs
  src/components/reusable/sidebar/mod.rs
  src/components/reusable/toolbar/mod.rs
  src/components/ui_kit/activity_indicator/mod.rs
  src/components/ui_kit/icon_input/mod.rs
  src/components/ui_kit/popup/mod.rs
  src/components/ui_kit/textarea/mod.rs
  src/main.rs
Labels: missing dev review

#311 chore/cargo: Update warp dependency
  Cargo.toml
Labels: task, QA approved, missing dev review

#327 chore(ci): update ci
  .github/workflows/ci-make-dmg.yml
Labels: draft

#335 chore(ci): add ci pr title lint
  .github/workflows/lint-PR-title.yml
Labels: missing dev review

#338 feat(notification): notify for incoming friend request
  src/components/main/compose/msg/mod.rs
  src/components/main/compose/write/mod.rs
  src/components/main/files/upload/mod.rs
  src/components/main/sidebar/mod.rs
  src/components/reusable/nav/mod.rs
  src/language/en_us.rs
  src/language/mod.rs
  src/ui_kit/src/textarea/mod.rs
  src/utils/src/notifications.rs
  src/utils/src/sounds.rs
Labels: missing dev review

#334 feat(AudioFactory): added basic UI
  Cargo.toml
  README.md
  src/components/main/compose/msg/embeds/mod.rs
  src/components/main/compose/msg/mod.rs
  src/components/main/compose/reply/mod.rs
  src/components/main/compose/topbar/mod.rs
  src/components/main/compose/write/mod.rs
  src/components/main/compose/write/styles.scss
  src/components/main/friends/friend/mod.rs
  src/components/main/friends/mod.rs
  src/components/main/friends/request/mod.rs
  src/components/main/settings/pages/developer/mod.rs
  src/components/main/settings/pages/general/mod.rs
  src/components/main/sidebar/chat/mod.rs
  src/components/main/sidebar/favorites/mod.rs
  src/components/main/sidebar/mod.rs
  src/components/prelude/loading.rs
  src/components/reusable/sidebar/mod.rs
  src/extensions/native/audio-factory/Cargo.toml
  src/extensions/native/audio-factory/src/lib.rs
  src/iutils/config.rs
  src/iutils/get_meta.rs
  src/iutils/mod.rs
  src/main.rs
  src/ui_kit/src/lib.rs
  src/ui_kit/src/select/mod.rs
  src/ui_kit/src/select/styles.scss
Labels: missing dev review

#342 chore(cargo): Update dependencies
  Cargo.toml
  src/components/reusable/nav/mod.rs
  src/ui_kit/Cargo.toml
  src/utils/Cargo.toml
Labels: enhancement, task

#344 bootstrapped call ui
  Cargo.toml
  extensions/Cargo.toml
  extensions/extension-example/src/extension.rs
  extensions/lib.rs
  extensions/native/audio-factory/src/lib.rs
  src/components/main/compose/messages/styles.scss
  src/components/main/compose/mod.rs
  src/components/main/settings/mod.rs
  src/components/main/settings/pages/developer/mod.rs
  src/components/main/settings/pages/extensions/extension.rs
  src/components/main/settings/pages/extensions/mod.rs
  src/components/main/settings/pages/extensions/styles.scss
  src/components/main/settings/pages/general/mod.rs
  src/components/main/settings/pages/mod.rs
  src/components/main/settings/pages/profile/mod.rs
  src/components/main/settings/pages/styles.scss
  src/components/main/settings/sidebar/mod.rs
  src/components/main/settings/sidebar/nav/mod.rs
  src/components/main/settings/style.scss
  src/components/media/controls/mod.rs
  src/components/media/controls/styles.scss
  src/components/media/media/mod.rs
  src/components/media/media/styles.scss
  src/components/media/mod.rs
  src/components/media/styles.scss
  src/components/mod.rs
  src/components/reusable/toolbar/styles.scss
  src/main.rs
  src/state/mod.rs
  src/ui_kit/src/button/mod.rs
  src/ui_kit/src/button/styles.scss
  src/ui_kit/src/extension_placeholder/styles.scss
  src/ui_kit/src/icon_button/mod.rs
  src/utils/src/extensions.rs
Labels: missing dev review

#346 chore(notifications): add dock badge method
  src/utils/Cargo.toml
  src/utils/src/notifications.rs
Labels: missing dev review

#349 chore(typo): fix typo
  README.md
Labels: missing dev review

#362 chore(Files): Cleans up some of the files UI
  Cargo.toml
  extensions/native/audio-factory/src/lib.rs
  extensions/native/emoji-selector/Cargo.toml
  extensions/native/emoji-selector/README.md
  extensions/native/emoji-selector/src/emojis.toml
  extensions/native/emoji-selector/src/lib.rs
  src/components/main/files/mod.rs
  src/components/main/files/sidebar/mod.rs
  src/components/main/files/sidebar/usage/mod.rs
  src/components/main/files/toolbar/mod.rs
  src/components/main/files/toolbar/usage/mod.rs
  src/components/main/files/toolbar/usage/styles.scss
  src/components/main/settings/pages/extensions/mod.rs
  src/components/main/settings/pages/extensions/styles.scss
  src/components/reusable/toolbar/styles.scss
Labels: missing dev review

#336 feat(Files): Show files on files browser
  src/components/main/files/browser/mod.rs
  src/components/main/files/mod.rs
  src/components/main/files/upload/mod.rs
  src/ui_kit/src/file/mod.rs
Labels: QA approved, missing dev review, team: files

#363 chore(cargo): Update dependency
  Cargo.toml
  src/main.rs
  src/ui_kit/Cargo.toml
  src/utils/Cargo.toml
Labels: task, QA approved, missing dev review

#364 feat(chat): call ui updated
  src/components/main/compose/mod.rs
  src/components/media/controls/styles.scss
  src/components/media/media/mod.rs
  src/components/media/media/styles.scss
  src/components/media/mod.rs
  src/components/media/styles.scss
  src/ui_kit/src/profile_picture/styles.scss
Labels: QA approved, missing dev review

#389 Context menu
  extensions/native/audio-factory/Cargo.toml
  src/components/main/files/browser/mod.rs
  src/components/main/sidebar/mod.rs
  src/components/reusable/context_menu/context.js
  src/components/reusable/context_menu/mod.rs
  src/components/reusable/context_menu/styles.scss
  src/components/reusable/mod.rs
  src/ui_kit/Cargo.toml
  src/ui_kit/src/textarea/mod.rs
Labels: QA approved, missing dev review

#393 feat(chat): context menu
  src/components/main/compose/msg/mod.rs
  src/components/main/compose/write/mod.rs
  src/components/main/sidebar/chat/mod.rs
  src/components/main/sidebar/mod.rs
  src/components/media/media/mod.rs
  src/components/reusable/mod.rs
  src/ui_kit/src/context_menu/context.js
  src/ui_kit/src/context_menu/mod.rs
  src/ui_kit/src/context_menu/styles.scss
  src/ui_kit/src/icon_input/mod.rs
  src/ui_kit/src/input/mod.rs
  src/ui_kit/src/lib.rs
  src/ui_kit/src/textarea/mod.rs
Labels: missing dev review

#391 feat(User Context): Adds UI ready for implementations
  src/components/main/sidebar/chat/mod.rs
  src/components/reusable/context_menu/context.js
  src/components/reusable/context_menu/mod.rs
  src/components/reusable/context_menu/styles.scss
Labels: QA approved, missing dev review

#392 feat(chat): search context menu
  src/components/main/compose/write/mod.rs
  src/components/main/sidebar/chat/mod.rs
  src/components/main/sidebar/mod.rs
  src/components/media/media/mod.rs
  src/components/reusable/mod.rs
  src/ui_kit/src/context_menu/context.js
  src/ui_kit/src/context_menu/mod.rs
  src/ui_kit/src/context_menu/styles.scss
  src/ui_kit/src/icon_input/mod.rs
  src/ui_kit/src/input/mod.rs
  src/ui_kit/src/lib.rs
  src/ui_kit/src/textarea/mod.rs
Labels: QA approved, missing dev review

#385 update(Profile): Improve profile page in setting
  src/components/main/settings/pages/profile/mod.rs
  src/components/main/settings/pages/profile/status_msg/mod.rs
  src/components/main/settings/pages/profile/styles.scss
  src/components/main/settings/pages/profile/username/mod.rs
  src/language/en_us.rs
  src/language/mod.rs
  src/ui_kit/src/input/mod.rs
Labels: QA approved, missing dev review, team: files

#394 feat(settings): configure layout responsiveness for settings page
  src/components/main/files/mod.rs
  src/components/main/files/sidebar/mod.rs
  src/components/main/files/toolbar/mod.rs
  src/components/main/files/toolbar/styles.scss
  src/components/main/mod.rs
  src/components/main/settings/mod.rs
  src/components/main/settings/style.scss
  src/components/main/styles.scss
Labels: enhancement, QA approved

#375 feat(Files): Remove file from constellation
  Cargo.toml
  src/components/main/files/browser/mod.rs
  src/components/main/files/browser/styles.scss
  src/components/main/files/mod.rs
  src/components/main/files/upload/mod.rs
  src/ui_kit/src/file/mod.rs
  src/ui_kit/src/folder/styles.scss
Labels: QA approved, missing dev review, team: files

#401 fix(context-menu): added js to keep context menu inside window bounds
  src/ui_kit/src/context_menu/context.js
Labels: missing dev review

#405 hotfix(Files): Adds the proper UI back in when hovering a file
  src/components/main/files/browser/mod.rs
  src/components/main/files/browser/styles.scss
  src/components/main/sidebar/mod.rs
  src/components/reusable/nav/mod.rs
  src/main.rs
  src/ui_kit/src/context_menu/styles.scss
Labels: missing dev review

#406 chore(dev): add watch command
  Makefile
Labels: missing dev review

#422 fix(utils): Avoid using unwrap directly
  src/iutils/get_meta.rs
Labels: bug, missing dev review

#423 fix(messages): fix continuous messages rendering
  src/components/main/compose/messages/mod.rs
Labels: missing dev review

#425 chore(cargo): Update dependency
  Cargo.toml
  src/ui_kit/Cargo.toml
  src/utils/Cargo.toml
Labels: task, missing dev review

#420 fix(chatSidebar): fix styles, overflow, name ellipsis overflow
  src/components/main/sidebar/favorites/mod.rs
  src/components/main/sidebar/favorites/styles.scss
  src/components/main/sidebar/styles.scss
  src/components/styles.scss
Labels: QA approved

#414 chore(chat): timer
  Config.toml
  src/components/main/settings/mod.rs
  src/components/main/settings/pages/audio_video/mod.rs
  src/components/main/settings/pages/mod.rs
  src/components/main/settings/sidebar/nav/mod.rs
  src/components/media/mod.rs
  src/components/media/time/mod.rs
  src/components/media/time/styles.scss
  src/iutils/config.rs
  src/iutils/mod.rs
Labels: changes requested, missing dev review

#418 feat(media): Call UI responsive and updates
  src/components/media/mod.rs
  src/components/media/responsive.js
  src/components/media/styles.scss
Labels: changes requested

#411 feat(settings): configure layout responsiveness for friends page
  src/components/main/friends/mod.rs
  src/components/main/friends/sidebar/mod.rs
  src/components/main/friends/sidebar/styles.scss
  src/components/main/friends/styles.scss
  src/components/main/settings/mod.rs
  src/components/main/settings/style.scss
  src/components/main/styles.scss
  src/components/reusable/mod.rs
  src/components/reusable/page_header/mod.rs
  src/components/reusable/page_header/styles.scss
Labels: enhancement, changes requested, missing dev review

#431 chore(Heroicons): Update heroicons to latest (adds support for wayyy …
  Cargo.toml
  extensions/native/audio-factory/Cargo.toml
  extensions/native/audio-factory/src/lib.rs
  extra/assets/img/uplink_muted.svg
  src/components/main/compose/msg/embeds/mod.rs
  src/components/main/compose/msg/mod.rs
  src/components/main/files/browser/mod.rs
  src/components/main/files/sidebar/mod.rs
  src/components/main/files/toolbar/mod.rs
  src/components/main/files/upload/mod.rs
  src/components/main/friends/friend/mod.rs
  src/components/main/friends/request/mod.rs
  src/components/main/friends/sidebar/mod.rs
  src/components/main/settings/pages/developer/mod.rs
  src/components/main/settings/pages/extensions/extension.rs
  src/components/main/settings/sidebar/mod.rs
  src/components/main/sidebar/chat/mod.rs
  src/components/main/sidebar/favorites/mod.rs
  src/components/main/sidebar/mod.rs
  src/components/media/controls/mod.rs
  src/components/media/mod.rs
  src/components/prelude/unlock/mod.rs
  src/components/reusable/nav/mod.rs
  src/main.rs
  src/state/mod.rs
  src/ui_kit/Cargo.toml
  src/ui_kit/src/button/styles.scss
  src/ui_kit/src/context_menu/mod.rs
  src/ui_kit/src/folder/mod.rs
  src/ui_kit/src/new_folder/mod.rs
  src/ui_kit/src/popup/mod.rs
Labels: missing dev review

#433 chore(cargo): Update dependency
  Cargo.toml
  src/ui_kit/Cargo.toml
  src/utils/Cargo.toml
  src/utils/src/notifications.rs
Labels: task, missing dev review

#438 fix(friends): reconfigure styling for friends-separator
  src/components/main/friends/styles.scss
Labels: UI Issues, missing dev review

#416 feat(messages): add message attachments
  src/components/main/compose/messages/mod.rs
  src/components/main/compose/mod.rs
  src/components/main/compose/msg/attachment/mod.rs
  src/components/main/compose/msg/attachment/styles.scss
  src/components/main/compose/msg/mod.rs
  src/main.rs
Labels: changes requested, missing dev review

#426 feat(files): Rename files
  src/components/main/files/browser/mod.rs
  src/components/main/files/upload/mod.rs
  src/main.rs
  src/ui_kit/src/file/hide_edit_name.js
  src/ui_kit/src/file/mod.rs
  src/ui_kit/src/file/show_edit_name.js
  src/ui_kit/src/folder/styles.scss
  src/utils/src/lib.rs
Labels: QA approved, missing dev review, team: files

#442 chore(convo): fixed styles for fav button
  src/ui_kit/src/button/styles.scss
Labels: ready for testing

#440 chore(convo): call layout minor
  src/components/media/responsive.js
Labels: ready for testing

#434 chore(cargo): Update dependency and remove locks
  Cargo.toml
  src/components/main/compose/messages/mod.rs
  src/components/main/compose/mod.rs
  src/components/main/compose/msg/attachment/mod.rs
  src/components/main/files/browser/mod.rs
  src/components/main/files/upload/mod.rs
  src/components/main/friends/friend/mod.rs
  src/components/main/friends/mod.rs
  src/components/main/friends/sidebar/mod.rs
  src/components/main/mod.rs
  src/components/main/settings/pages/developer/mod.rs
  src/components/main/settings/pages/profile/status_msg/mod.rs
  src/components/main/settings/pages/profile/username/mod.rs
  src/components/main/sidebar/chat/mod.rs
  src/components/media/mod.rs
  src/components/prelude/auth/mod.rs
  src/components/prelude/loading.rs
  src/components/reusable/nav/mod.rs
  src/iui_kit/textarea.rs
  src/iutils/mod.rs
  src/main.rs
  src/ui_kit/Cargo.toml
  src/ui_kit/src/activity_indicator/mod.rs
  src/ui_kit/src/file/mod.rs
  src/ui_kit/src/photo_picker/mod.rs
  src/utils/Cargo.toml
  src/utils/src/lib.rs
Labels: task, QA approved, missing dev review

#436 fix(text-area): clear hidden input text after message is sent
  src/components/reusable/page_header/styles.scss
  src/ui_kit/src/textarea/mod.rs
Labels: UI Issues, QA approved

#437 refactor(uikit): consolidate input and iconinput components
  src/components/main/friends/sidebar/mod.rs
  src/components/main/settings/sidebar/mod.rs
  src/components/main/sidebar/mod.rs
  src/components/prelude/auth/mod.rs
  src/ui_kit/src/icon_input/mod.rs
  src/ui_kit/src/icon_input/styles.scss
  src/ui_kit/src/input/mod.rs
  src/ui_kit/src/input/styles.scss
  src/ui_kit/src/lib.rs
Labels: QA approved

#445 chore(File Embeds): Clean up file embeds a bit
  src/components/main/compose/msg/attachment/mod.rs
  src/components/main/compose/msg/attachment/styles.scss
  src/state/mod.rs
Labels: QA approved, missing dev review

#450 chore(request): Allow deleting outgoing request
  src/components/main/friends/request/mod.rs
Labels: task, UI Issues, missing dev review

#451 fix(sidebar): add ellipsis to username
  src/components/main/sidebar/chat/styles.scss
  src/components/reusable/toolbar/styles.scss
Labels: UI Issues, missing dev review

#453 refactor(uikit): consolidate button and iconbutton components
  extensions/native/audio-factory/src/lib.rs
  src/components/main/compose/mod.rs
  src/components/main/compose/msg/attachment/mod.rs
  src/components/main/compose/msg/embeds/mod.rs
  src/components/main/compose/msg/mod.rs
  src/components/main/compose/topbar/mod.rs
  src/components/main/compose/write/mod.rs
  src/components/main/files/toolbar/mod.rs
  src/components/main/files/upload/mod.rs
  src/components/main/friends/friend/mod.rs
  src/components/main/friends/request/mod.rs
  src/components/main/friends/sidebar/mod.rs
  src/components/main/sidebar/favorites/mod.rs
  src/components/media/controls/mod.rs
  src/components/media/mod.rs
  src/components/prelude/unlock/mod.rs
  src/components/reusable/nav/mod.rs
  src/components/reusable/page_header/mod.rs
  src/components/reusable/toolbar/styles.scss
  src/ui_kit/src/button/mod.rs
  src/ui_kit/src/button/styles.scss
  src/ui_kit/src/icon_button/mod.rs
  src/ui_kit/src/icon_button/styles.scss
  src/ui_kit/src/lib.rs
  src/ui_kit/src/photo_picker/mod.rs
  src/ui_kit/src/photo_picker/styles.scss
  src/ui_kit/src/popup/mod.rs
Labels: QA approved

#443 feat(extensions): update extensions load
  extensions/extension-example/Cargo.toml
  extensions/extension-example/src/extension.rs
  extensions/extension-example/src/lib.rs
  extensions/native/audio-factory/src/lib.rs
  extensions/native/emoji-selector/src/lib.rs
  src/components/main/compose/write/mod.rs
  src/components/main/settings/pages/extensions/extension.rs
  src/components/main/settings/pages/extensions/mod.rs
  src/utils/Cargo.toml
  src/utils/src/extensions.rs
Labels: QA approved, missing dev review

#332 chore(signing): sign dmg
  .github/workflows/ci-make-dmg.yml
  Makefile
  extensions/Cargo.toml.example
Labels: QA approved

#454 update(auth): add username validation and uploading profile picture
  src/components/main/files/browser/mod.rs
  src/components/main/files/upload/mod.rs
  src/components/main/settings/pages/profile/username/mod.rs
  src/components/prelude/auth/mod.rs
  src/components/reusable/mod.rs
  src/ui_kit/src/file/mod.rs
  src/utils/src/lib.rs
Labels: QA approved, missing dev review, team: files

#464 fix(files-usage): remodel usage bar for files
  src/components/main/files/toolbar/mod.rs
  src/components/main/files/toolbar/styles.scss
  src/components/main/files/toolbar/usage/mod.rs
  src/components/main/files/toolbar/usage/styles.scss
  src/components/main/styles.scss
Labels: UI Issues, QA approved, missing dev review

#468 fix(files): hide sidebar for mobile
  src/components/main/files/mod.rs
  src/components/main/files/toolbar/mod.rs
  src/components/main/files/toolbar/usage/mod.rs
  src/components/main/friends/mod.rs
  src/components/main/settings/mod.rs
  src/components/main/styles.scss
Labels: UI Issues, QA approved, missing dev review

#469 chore(sidebar): favorites ui update
  src/components/main/sidebar/favorites/mod.rs
  src/components/main/sidebar/mod.rs
Labels: QA approved, missing dev review

#467 fix(msg): display attachments in reply modal
  src/components/main/compose/msg/attachment/styles.scss
  src/components/main/compose/msg/mod.rs
  src/components/main/compose/msg/styles.scss
  src/ui_kit/src/button/mod.rs
  src/ui_kit/src/button/styles.scss
Labels: UI Issues, QA approved, missing dev review
