Repository Satellite-im/Uplink, pull requests merged in 2022-12, with the labels that each got.

#10 update(Translate): Keep translate
  kit/src/layout/chatbar/mod.rs
  ui/Cargo.toml
  ui/locales/en-US/main.ftl
  ui/locales/pt-BR/main.ftl
  ui/src/components/chat/compose.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/chat/welcome/mod.rs
  ui/src/components/friends/add.rs
  ui/src/components/friends/friend/mod.rs
  ui/src/components/media/player.rs
  ui/src/components/media/remote_control.rs
  ui/src/components/settings/sidebar.rs
  ui/src/components/settings/sub_pages/audio.rs
  ui/src/components/settings/sub_pages/developer.rs
  ui/src/components/settings/sub_pages/extensions.rs
  ui/src/components/settings/sub_pages/general.rs
  ui/src/components/settings/sub_pages/privacy.rs
  ui/src/layouts/files.rs
  ui/src/layouts/friends.rs
  ui/src/main.rs
  ui/src/utils/language.rs
Labels: enhancement

#13 chore(clippy): Linting cleanup
  kit/src/components/nav/mod.rs
  ui/src/components/chat/compose.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/friends/friend/mod.rs
  ui/src/components/media/player.rs
  ui/src/components/media/remote_control.rs
  ui/src/components/settings/sidebar.rs
  ui/src/components/settings/sub_pages/developer.rs
  ui/src/layouts/settings.rs
  ui/src/layouts/unlock.rs
  ui/src/main.rs
  ui/src/state.rs
  ui/src/testing/mock.rs
  ui/src/utils/language.rs
Labels: QA Approved, Missing dev review

#14 update(Friends): Refactor friends code
  ui/locales/en-US/main.ftl
  ui/locales/pt-BR/main.ftl
  ui/src/components/chat/compose.rs
  ui/src/components/friends/blocked/mod.rs
  ui/src/components/friends/friend/mod.rs
  ui/src/components/friends/friend/style.scss
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/friends/incoming_requests/mod.rs
  ui/src/components/friends/mod.rs
  ui/src/components/friends/outgoing_requests/mod.rs
  ui/src/components/friends/style.scss
  ui/src/layouts/friends.rs
  ui/src/utils/format_timestamp.rs
  ui/src/utils/mod.rs
  ui/todo.md
Labels: QA Approved, Missing dev review

#12 Update(Test-Doc): Adding more documentation
  ui/docs/testing/uplink-checklist.md
Labels: Missing dev review

#29 chore(mock): Changes to identity mock data
  Cargo.lock
  kit/src/components/toast/mod.rs
  ui/Cargo.toml
  ui/src/components/chat/compose.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/friends/blocked/mod.rs
  ui/src/components/friends/friend/mod.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/friends/incoming_requests/mod.rs
  ui/src/components/friends/outgoing_requests/mod.rs
  ui/src/main.rs
  ui/src/state.rs
  ui/src/testing/mock.rs
  ui/src/utils/mod.rs
Labels: QA Approved, Missing dev review

#28 Update(Uplink-Checklist): Adding more documentation
  ui/docs/testing/uplink-checklist.md
Labels: documentation, Missing dev review

#37 fix: Clone and show text instead of a div
  kit/src/elements/button/mod.rs
Labels: bug, Missing dev review

#38 fix(Makefile): Fix makefile paths
  Makefile
  ui/src/components/settings/sub_pages/extensions.rs
Labels: Missing dev review
