Repository Satellite-im/Uplink, pull requests merged in 2023-08, with the labels that each got.

#1045 fix(Attachments): Limit files per message and remove persistance when switching chat
  common/locales/en-US/main.ftl
  common/src/state/action.rs
  common/src/state/chats.rs
  common/src/state/mod.rs
  common/src/testing/mock.rs
  common/src/warp_runner/ui_adapter/mod.rs
  kit/Cargo.toml
  kit/src/components/embeds/file_embed/mod.rs
  kit/src/components/embeds/file_embed/style.scss
  ui/src/components/chat/compose/chatbar.rs
  ui/src/components/chat/compose/mod.rs
  ui/src/components/chat/style.scss
Labels: QA Tested, Ready to Merge, Failed Automated Test

#1059 feat(GroupChats): improve warning
  common/locales/de/main.ftl
  common/locales/en-US/main.ftl
  common/locales/es-MX/main.ftl
  common/locales/pt-BR/main.ftl
  common/locales/pt-PT/main.ftl
  kit/src/elements/input/mod.rs
Labels: QA Tested, Ready to Merge, Failed Automated Test

#1060 fix(chats): remove react option
  ui/src/components/chat/compose/messages.rs
Labels: QA Tested, Ready to Merge

#1068 update(spanish): update spanish translation file to latest
  common/locales/es-MX/main.ftl
Labels: Don't merge yet

#1067 fix(ImageFrame): Fix rectify frames in images
  kit/src/components/embeds/file_embed/mod.rs
  kit/src/components/embeds/file_embed/style.scss
Labels: QA Tested, Ready to Merge

#1065 chore(build): Optimize build
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  extension_example/Cargo.toml
  extensions/Cargo.toml
  icons/Cargo.toml
  kit/Cargo.toml
  native_extensions/clear_all/Cargo.toml
  native_extensions/emoji_selector/Cargo.toml
  native_extensions/emoji_selector/src/lib.rs
  ui/Cargo.toml
  ui/src/components/chat/compose/chatbar.rs
  ui/src/components/chat/compose/messages.rs
Labels: Don't merge yet

#1066 fix(BugModal): bugchat opening image previews highlights chat list avatars
  kit/src/components/embeds/file_embed/mod.rs
  kit/src/components/user_image_group/styles.scss
  kit/src/layout/modal/mod.rs
  kit/src/layout/modal/style.scss
  ui/src/components/files/file_preview.rs
Labels: Don't merge yet, Failed Automated Test

#1073 chore(typo): fix typo
  kit/src/layout/modal/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1074 fix(SearchDropdown): Let search groups as non case sensitive
  common/src/state/mod.rs
  ui/src/layouts/unlock.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1071 fix(SearchDropdown): Fix search dropdown issues
  common/src/state/mod.rs
  ui/src/components/chat/sidebar.rs
Labels: QA Tested, Missing dev review, Don't merge yet, Failed Automated Test

#1063 feat(chat): Overhaul typing indicator
  common/locales/en-US/main.ftl
  kit/src/components/message_typing/format_names.js
  kit/src/components/message_typing/mod.rs
  kit/src/components/message_typing/style.scss
  kit/src/layout/chatbar/mod.rs
  kit/src/layout/chatbar/style.scss
  ui/src/components/chat/compose/chatbar.rs
Labels: QA Tested, Don't merge yet, Failed Automated Test

#1078 fix(chat): Fix wrong translation key causing no typing indicator
  kit/src/components/message_typing/mod.rs
Labels: Missing dev review, Don't merge yet

#1079 fix(ui): Fix accent color in light mode
  ui/extra/themes/light.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#1076 chore(cargo): update dependency
  Cargo.lock
  Cargo.toml
  common/src/state/mod.rs
  common/src/warp_runner/mod.rs
Labels: Ready for testing, Don't merge yet

#1080 fix(chat): Add padding to char counter
  kit/src/elements/textarea/style.scss
Labels: QA Tested, Ready to Merge

#1082 feat(AppWindow): Add borders to the app window
  kit/src/style.scss
  ui/src/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#1070 chore(groupchat): topbar groupchat stuff
  common/locales/en-US/main.ftl
  ui/src/components/chat/compose/mod.rs
  ui/src/components/chat/edit_group.rs
  ui/src/components/chat/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet, Failed Automated Test

#1092 chore(locales): update locale
  common/locales/pt-PT/main.ftl
Labels: QA Tested, Missing dev review, Don't merge yet

#1096 chore(locales): update locale
  common/locales/en-US/main.ftl
Labels: Waiting for CI

#1095 chore(locales): add pt-PT locale
  common/locales/pt-PT/main.ftl
Labels: Waiting for CI

#1093 chore(locales): add pt-PT locales
  common/locales/pt-PT/main.ftl
Labels: Waiting for CI

#1097 chore(locales): add pt-PT locale
  common/locales/pt-PT/main.ftl
Labels: Waiting for CI

#1094 chore(locales): add pt-PT locales
  common/locales/pt-PT/main.ftl
Labels: Waiting for CI

#1101 fix(files): Adjust background for file upload
  kit/src/style.scss
  ui/extra/themes/light.scss
  ui/src/components/files/upload_progress_bar/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#1102 fix(reply): fix background var color for inline-reply
  kit/src/layout/chatbar/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet, Failed Automated Test

#1052 Emoji reroute
  Cargo.lock
  common/src/state/action.rs
  common/src/state/mod.rs
  common/src/state/ui.rs
  native_extensions/emoji_selector/Cargo.toml
  native_extensions/emoji_selector/src/lib.rs
  ui/src/components/chat/compose/messages.rs
  ui/src/components/emoji_group/mod.rs
  ui/src/components/emoji_group/style.scss
  ui/src/main.rs
Labels: Changes requested, Missing dev review, Failed Automated Test

#1103 chore(appium): copy windows assets on appium workflow
  .github/workflows/ui-test-automation.yml
Labels: Missing dev review

#1105 chore(locales): add locale pt-PT
  common/locales/pt-PT/main.ftl
Labels: Missing dev review, Don't merge yet

#1106 update(locales): update spanish translations file
  common/locales/es-MX/main.ftl
Labels: QA Tested, Ready to Merge, Failed Automated Test

#1107 chore(appium): update workflow to copy extensions assets
  .github/workflows/ui-test-automation.yml
Labels: Missing dev review, Don't merge yet

#1110 chore(cargo): Update dependency
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  common/src/warp_runner/mod.rs
  ui/Cargo.toml
Labels: QA Tested, Ready to Merge

#1117 chore(appium): update appium workflow to copy missing extensions assets
  .github/workflows/ui-test-automation.yml
Labels: Missing dev review, Don't merge yet

#1003 fix(textarea): placeholder alignment jitter
  kit/src/elements/textarea/mod.rs
  kit/src/elements/textarea/script.js
  kit/src/elements/textarea/update_input_height.js
  ui/src/components/chat/sidebar.rs
Labels: QA Tested, Don't merge yet, Failed Automated Test

#1116 update(ui): aria labels for emojis extensions and edit group chats
  native_extensions/emoji_selector/src/lib.rs
  ui/src/components/chat/compose/mod.rs
  ui/src/components/chat/edit_group.rs
  ui/src/components/emoji_group/mod.rs
  ui/src/components/settings/mod.rs
Labels: QA Tested, Ready to Merge, Failed Automated Test

#1118 chore(appium): fix appium workflow for windows build copy assets
  .github/workflows/ui-test-automation.yml
Labels: Missing dev review, Don't merge yet

#1112 chore(groupchat): no results state and substring search filter
  common/locales/en-US/main.ftl
  ui/src/components/chat/edit_group.rs
  ui/src/components/chat/group_users.rs
  ui/src/components/chat/style.scss
Labels: QA Tested, Ready to Merge

#1119 fix(counter): lock moving character counter to bottom of textarea
  kit/src/elements/textarea/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#1124 chore(group-images): make group profile image default cursor
  kit/src/components/user_image/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#1125 chore(favorites): favorites showing groups with wrong count
  ui/src/components/chat/sidebar.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1128 chore(cargo): Update dependency
  Cargo.lock
  Cargo.toml
Labels: QA Tested, Missing dev review, Don't merge yet

#1136 fix(sidebar): Fix sidebar being hidden/shown during undesired actions
  ui/src/components/chat/sidebar.rs
  ui/src/main.rs
Labels: Changes requested, Don't merge yet

#1129 fix(EditGroup): Update group name correctly
  ui/src/components/chat/compose/mod.rs
  ui/src/components/chat/create_group.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1139 chore(cargo): Update Dependency
  Cargo.lock
  Cargo.toml
Labels: Ready for testing, Don't merge yet

#1132 chore(calling): hook up reject_call blink method so receiver can decline a call and sender call ends too
  common/src/state/action.rs
  common/src/state/mod.rs
  common/src/warp_runner/manager/commands/blink_commands.rs
  ui/src/components/media/remote_control.rs
  ui/src/main.rs
Labels: QA Tested, Don't merge yet

#1147 chore(appium): update ci to use macos 13 and update spanish translation
  .github/workflows/ui-test-automation.yml
  common/locales/es-MX/main.ftl
Labels: Missing dev review, Don't merge yet

#1143 chore(cargo): update dependency to allow blink to cancel a call
  Cargo.lock
  Cargo.toml
  common/src/state/call.rs
  common/src/state/mod.rs
Labels: QA Tested, Ready to Merge

#1153 chore(docs): minor update
  docs/architecture.md
Labels: Missing dev review, Don't merge yet

#1151 chore(locales): add pt-PT locale
  common/locales/pt-PT/main.ftl
Labels: QA Tested, Missing dev review, Don't merge yet, Failed Automated Test

#1142 chore(Css Cleanup): Cleanup css on the groups code, also adds slimbar for communities
  kit/src/components/invisible_closer/mod.rs
  kit/src/components/invisible_closer/style.scss
  kit/src/components/mod.rs
  kit/src/components/nav/mod.rs
  kit/src/components/user_image_group/mod.rs
  kit/src/components/user_image_group/styles.scss
  kit/src/layout/mod.rs
  kit/src/layout/sidebar/mod.rs
  kit/src/layout/sidebar/script.js
  kit/src/layout/slimbar/mod.rs
  kit/src/layout/slimbar/style.scss
  kit/src/style.scss
  ui/src/components/chat/compose/messages.rs
  ui/src/components/chat/compose/mod.rs
  ui/src/components/chat/edit_group.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/chat/style.scss
  ui/src/components/chat/welcome/mod.rs
  ui/src/components/settings/sub_pages/profile/style.scss
  ui/src/components/topbar/release_info/style.scss
  ui/src/layouts/chat.rs
  ui/src/layouts/friends.rs
  ui/src/layouts/mod.rs
  ui/src/layouts/settings.rs
  ui/src/layouts/slimbar.rs
  ui/src/layouts/storage/mod.rs
  ui/src/layouts/style.scss
  ui/src/style.scss
Labels: QA Tested, Failed Automated Test

#1148 fix(chat): Add indicator for disabled emoji extension
  common/locales/en-US/main.ftl
  common/src/state/ui.rs
  ui/src/components/emoji_group/mod.rs
Labels: Don't merge yet, Hold For Discussion, Failed Automated Test

#1141 fix(emoji): Consistent emoji in context menu
  common/src/state/ui.rs
  ui/src/components/chat/compose/messages.rs
Labels: QA Tested, Ready to Merge

#1121 feat(chat): Pinning messages
  common/locales/en-US/main.ftl
  common/src/state/chats.rs
  common/src/state/mod.rs
  common/src/testing/mock.rs
  common/src/warp_runner/manager/commands/raygun_commands.rs
  common/src/warp_runner/ui_adapter/message_event.rs
  common/src/warp_runner/ui_adapter/mod.rs
  icons/src/icons/outline/pin.svg
  kit/src/components/message/mod.rs
  kit/src/components/message/style.scss
  kit/src/components/user_image/mod.rs
  kit/src/elements/tooltip/style.scss
  ui/src/components/chat/compose/messages.rs
  ui/src/components/chat/compose/mod.rs
  ui/src/components/chat/mod.rs
  ui/src/components/chat/pinned_messages/mod.rs
  ui/src/components/chat/pinned_messages/script.js
  ui/src/components/chat/pinned_messages/style.scss
  ui/src/components/chat/scroll_to_message.js
  ui/src/components/chat/style.scss
Labels: Waiting for CI

#1161 fix(CreateGroup): Fix Create Group Popup
  ui/src/components/chat/create_group.rs
  ui/src/components/chat/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#1163 fix(edit): strip rogue p tag
  kit/src/components/message/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1165 add(aria): aria labels for pinned messages and searchbar
  kit/src/components/message/mod.rs
  ui/src/components/chat/pinned_messages/mod.rs
  ui/src/components/chat/sidebar.rs
Labels: Missing dev review, Don't merge yet

#1149 update(CharCounter): Fix char counter with emoji
  kit/src/elements/textarea/mod.rs
  kit/src/elements/textarea/style.scss
  kit/src/elements/textarea/update_char_counter.js
  native_extensions/emoji_selector/src/lib.rs
Labels: Changes requested, Don't merge yet, Failed Automated Test

#1140 fix(extensions): Fix auto enable extension and emoji selector not working
  common/src/state/mod.rs
  common/src/state/ui.rs
  extensions/src/lib.rs
  ui/src/components/chat/compose/chatbar.rs
  ui/src/components/chat/sidebar.rs
  ui/src/extension_browser/mod.rs
  ui/src/main.rs
Labels: QA Tested, Ready to Merge, Failed Automated Test

#1169 fix(clippy): fix the clippy warnings on windows
  common/src/notifications.rs
  ui/src/components/chat/compose/mod.rs
  ui/src/utils/clipboard/clipboard_data.rs
Labels: QA Tested, Ready to Merge

#1170 chore(appium): add retry step on macos CI test execution
  .github/workflows/ui-test-automation.yml
Labels: Waiting for CI

#1171 fix(slimbar): update zindex
  kit/src/layout/slimbar/style.scss
Labels: Missing dev review, Don't merge yet
