Repository Satellite-im/Uplink, pull requests merged in 2023-04, with the labels that each got.

#569 chore(feedback): add feedback url in app
  common/locales/en-US/main.ftl
  ui/src/main.rs
  ui/src/style.scss
Labels: QA Tested, Ready to Merge

#566 fix(ui): Increase contrast of some text colors
  ui/extra/themes/default.scss
  ui/extra/themes/draculish.scss
  ui/extra/themes/polar.scss
Labels: QA Tested, Ready to Merge

#571 chore(Fonts): finish fonts
  common/locales/en-US/main.ftl
  common/src/state/action.rs
  common/src/state/configuration.rs
  common/src/state/mod.rs
  common/src/state/ui.rs
  ui/src/components/settings/sub_pages/general.rs
  ui/src/main.rs
  ui/src/utils/mod.rs
Labels: Missing dev review, Don't merge yet

#575 fix(makefile): change target for Makefile
  Makefile
Labels: Missing dev review, Don't merge yet

#582 fix(mac): change CFBundleExecutable
  ui/extra/macos/Uplink.app/Contents/Info.plist
Labels: Ready to Merge

#573 chore(cargo): Update dependency
  Cargo.lock
  Cargo.toml
Labels: QA Tested, Missing dev review, Ready to Merge

#530 feat(sidebar): Add icon to hide/show sidebar
  kit/src/layout/sidebar/mod.rs
  kit/src/layout/sidebar/style.scss
  kit/src/layout/topbar/mod.rs
  ui/src/components/chat/compose.rs
  ui/src/layouts/friends.rs
  ui/src/layouts/settings.rs
  ui/src/layouts/storage.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#588 update(EmojiSelector): Let it above chatbar
  native_extensions/emoji_selector/src/style.css
Labels: QA Tested, Missing dev review, Don't merge yet

#603 fix(ui): Fix friend tab not persisting when minimal
  ui/src/layouts/friends.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#572 chore(ui): Font scaling
  Cargo.lock
  common/locales/de/main.ftl
  common/locales/en-US/main.ftl
  common/locales/es-MX/main.ftl
  common/locales/pt-BR/main.ftl
  common/src/state/action.rs
  common/src/state/mod.rs
  common/src/state/settings.rs
  kit/src/components/mod.rs
  kit/src/components/slide_selector/mod.rs
  kit/src/components/slide_selector/style.scss
  kit/src/elements/textarea/mod.rs
  ui/src/components/settings/sub_pages/accessibility.rs
  ui/src/components/settings/sub_pages/audio.rs
  ui/src/components/settings/sub_pages/developer.rs
  ui/src/components/settings/sub_pages/files.rs
  ui/src/components/settings/sub_pages/general.rs
  ui/src/components/settings/sub_pages/privacy.rs
  ui/src/main.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#608 fix(vsc): Update vsc launch.json
  .vscode/launch.json
Labels: Missing dev review, Don't merge yet

#605 chore(misc): Matts branch
  extensions/src/lib.rs
  kit/src/components/slide_selector/mod.rs
  kit/src/elements/tooltip/style.scss
  native_extensions/clear_all/src/lib.rs
  ui/src/components/chat/compose.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/settings/sub_pages/general.rs
Labels: QA Tested, Ready to Merge

#595 feat(updates): add workflow for linux and code to check GitHub API
  .github/workflows/build-dmg-universal.yml
  .github/workflows/build-release-linux.yml
  .github/workflows/build-release-windows.yml
  Cargo.lock
  Makefile
  build_linux_installer.sh
  common/locales/en-US/main.ftl
  common/src/lib.rs
  common/src/state/action.rs
  common/src/state/mod.rs
  common/src/state/settings.rs
  common/src/warp_runner/manager/commands/other_commands.rs
  kit/src/elements/button/mod.rs
  ui/Cargo.toml
  ui/README.md
  ui/deb-config/DEBIAN/control
  ui/src/components/settings/sub_pages/about.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/layouts/unlock.rs
  ui/src/main.rs
  ui/src/style.scss
  ui/src/utils/auto_updater.rs
  ui/src/utils/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#611 feat(chat): Change send button to match if can send or not
  common/src/state/mod.rs
  ui/src/components/chat/compose.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#610 fix(friend): Improved some friend request things
  common/locales/en-US/main.ftl
  common/src/warp_runner/manager/commands/multipass_commands.rs
  ui/src/components/friends/add.rs
Labels: QA Tested, Ready to Merge

#624 feat(desktop): create desktop launcher for windows
  .github/workflows/build-release-linux.yml
  .github/workflows/build-release-windows.yml
  Cargo.lock
  Makefile
  README.md
  build_linux_installer.sh
  common/Cargo.toml
  common/src/lib.rs
  common/src/warp_runner/manager/commands/multipass_commands.rs
  ui/Cargo.toml
  ui/Config.toml
  ui/README.md
  ui/build.rs
  ui/deb/DEBIAN/control
  ui/deb/DEBIAN/postinst
  ui/deb/usr/share/applications/im.satellite.uplink.desktop
  ui/deb/usr/share/metainfo/im.satellite.uplink.metainfo.xml
  ui/extra/linux/im.satellite.uplink.desktop
  ui/src/main.rs
  ui/src/utils/mod.rs
  ui/wix/main.wxs
Labels: QA Tested, Missing dev review, Don't merge yet

#628 fix(Storage): Fix upload files component to be over any avatar on chats
  ui/src/layouts/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#627 chore(appium): updates to appium workflow files
  .github/workflows/ui-test-execution.yml
  .github/workflows/ui-test-windows.yml
Labels: Missing dev review, Don't merge yet

#636 chore(Friends): Remove unused code
  ui/src/layouts/friends.rs
  ui/src/layouts/style.scss
Labels: Ready to Merge, QA Override

#637 chore(appium): accounts as temp artifacts on appium workflows
  .github/workflows/ui-test-execution.yml
Labels: Missing dev review, Don't merge yet

#646 update(locales): update spanish mx translation file
  common/locales/es-MX/main.ftl
Labels: Missing dev review, Don't merge yet

#558 feat(chat): Quick profile feature
  common/locales/en-US/main.ftl
  kit/src/components/context_menu/context.js
  kit/src/components/context_menu/mod.rs
  kit/src/components/context_menu/style.scss
  kit/src/components/message_group/mod.rs
  kit/src/components/message_group/style.scss
  kit/src/components/user_image/mod.rs
  ui/src/components/chat/compose.rs
  ui/src/components/chat/show_context.js
  ui/src/components/chat/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#641 fix(friends): add loading screen after login
  ui/src/layouts/loading.rs
  ui/src/layouts/mod.rs
  ui/src/main.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#640 fix(unlock): disable button while warp command is in progress
  ui/src/layouts/unlock.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#650 update(ui): add missing aria labels on UI elements and spanish locales
  common/locales/es-MX/main.ftl
  kit/src/components/context_menu/mod.rs
  kit/src/components/file_embed/mod.rs
  kit/src/components/user_image_group/mod.rs
  kit/src/layout/chatbar/mod.rs
  ui/src/components/chat/compose.rs
  ui/src/components/chat/create_group.rs
  ui/src/components/chat/sidebar.rs
Labels: Missing dev review, Don't merge yet

#633 feat(loading): improve loading states
  common/locales/en-US/main.ftl
  kit/src/elements/button/mod.rs
  kit/src/elements/input/mod.rs
  ui/src/components/chat/compose.rs
  ui/src/components/chat/create_group.rs
  ui/src/components/chat/style.scss
  ui/src/components/friends/add.rs
  ui/src/components/friends/friend/mod.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/friends/incoming_requests/mod.rs
  ui/src/components/friends/outgoing_requests/mod.rs
  ui/src/components/settings/sub_pages/about.rs
  ui/src/layouts/storage.rs
  ui/src/main.rs
  ui/src/style.scss
  ui/src/utils/auto_updater.rs
Labels: QA Tested, Don't merge yet, Conflicts

#643 fix(notifications): fix badge notifications on Mac
  common/src/state/mod.rs
  common/src/state/notifications.rs
  ui/src/components/chat/compose.rs
  ui/src/main.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#609 feat(reactions): add message reactions
  common/src/state/mod.rs
  common/src/warp_runner/manager/commands/multipass_commands.rs
  common/src/warp_runner/manager/commands/raygun_commands.rs
  common/src/warp_runner/manager/events.rs
  common/src/warp_runner/mod.rs
  common/src/warp_runner/ui_adapter/message_event.rs
  common/src/warp_runner/ui_adapter/multipass_event.rs
  common/src/warp_runner/ui_adapter/raygun_event.rs
  kit/src/components/message/mod.rs
  kit/src/components/message/style.scss
  kit/src/elements/textarea/mod.rs
  quick_build.sh
  ui/src/components/chat/compose.rs
  ui/src/components/chat/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#667 fix(Reply): Fix reply attachments
  common/src/warp_runner/ui_adapter/mod.rs
  kit/src/components/file_embed/mod.rs
  kit/src/components/message_reply/mod.rs
  kit/src/components/message_reply/style.scss
  kit/src/layout/chatbar/mod.rs
  ui/src/components/chat/compose/chatbar.rs
  ui/src/components/chat/compose/messages.rs
Labels: QA Tested, Missing dev review, Don't merge yet, Failed Automated Test

#659 feat(EditGroup): Add and Remove participants in group
  common/locales/en-US/main.ftl
  common/src/state/mod.rs
  common/src/warp_runner/manager/commands/raygun_commands.rs
  common/src/warp_runner/ui_adapter/message_event.rs
  ui/src/components/chat/compose/mod.rs
  ui/src/components/chat/edit_group.rs
  ui/src/components/chat/mod.rs
  ui/src/components/chat/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#684 chore(docs): fix 404
  README.md
Labels: Ready to Merge

#685 chore(ghactions): make fmt action happy
  ui/src/components/chat/compose/mod.rs
Labels: Ready to Merge, QA Override

#686 chore(translations): update encryption text
  common/locales/en-US/main.ftl
  common/locales/es-MX/main.ftl
  common/locales/pt-BR/main.ftl
  common/locales/pt-PT/main.ftl
Labels: QA Tested, Ready to Merge

#675 fix(ui): Center update divs
  ui/src/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet, Failed Automated Test

#687 chore(appium): change resolution on appium windows runner
  .github/workflows/ui-test-windows.yml
Labels: QA Tested, Ready to Merge

#700 chore(appium): update appium workflow to use toolchain 1.68.2
  .github/workflows/ui-test-execution.yml
  .github/workflows/ui-test-windows.yml
Labels: Missing dev review, Don't merge yet

#691 fix(lang): Lang fixes
  common/locales/en-US/main.ftl
  common/src/language/mod.rs
  common/src/state/settings.rs
  ui/src/components/chat/compose/messages.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/friends/friend/mod.rs
  ui/src/components/settings/sidebar.rs
  ui/src/components/settings/sub_pages/accessibility.rs
  ui/src/components/settings/sub_pages/developer.rs
  ui/src/extension_browser/mod.rs
  ui/src/layouts/unlock.rs
  ui/src/utils/format_timestamp.rs
Labels: QA Tested, Ready to Merge, Failed Automated Test

#703 chore(typo): fix typo in locales
  common/locales/pt-BR/main.ftl
Labels: Missing dev review, Don't merge yet

#701 fix(javascript): fix javascript errors
  icons/src/lib.rs
  kit/src/components/nav/mod.rs
  kit/src/elements/button/mod.rs
  kit/src/elements/button/script.js
  kit/src/elements/input/mod.rs
  kit/src/elements/input/script.js
  kit/src/elements/textarea/focus.js
  kit/src/elements/textarea/mod.rs
  kit/src/elements/textarea/script.js
  kit/src/elements/tooltip/mod.rs
  kit/src/layout/chatbar/mod.rs
  ui/src/components/chat/compose/chatbar.rs
  ui/src/components/chat/compose/messages.rs
  ui/src/components/friends/add.rs
  ui/src/components/friends/friend/mod.rs
  ui/src/layouts/file_preview.rs
Labels: QA Tested, Ready to Merge

#704 chore(cargo): Update dependency
  Cargo.lock
  Cargo.toml
  common/src/warp_runner/manager/commands/raygun_commands.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#678 chore(dependencies): update dioxus to 73a2beb3275007a6550adc5c420f36e31b7ddef7
  .github/workflows/build-release-linux.yml
  .github/workflows/cargo.yml
  Cargo.lock
  Cargo.toml
  README.md
  kit/src/components/message/mod.rs
  native_extensions/clear_all/Cargo.toml
  native_extensions/emoji_selector/Cargo.toml
  native_extensions/emoji_selector/src/lib.rs
  ui/Cargo.toml
  ui/src/components/chat/compose/chatbar.rs
  ui/src/components/chat/compose/mod.rs
  ui/src/components/friends/blocked/mod.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/friends/incoming_requests/mod.rs
  ui/src/components/friends/outgoing_requests/mod.rs
  ui/src/components/toast/mod.rs
  ui/src/layouts/storage.rs
  ui/src/logger/mod.rs
  ui/src/main.rs
  ui/src/window_manager/mod.rs
  ui/wix/main.wxs
Labels: QA Tested, Ready to Merge

#710 chore(locales): pt-PT locales
  common/locales/pt-PT/main.ftl
Labels: Missing dev review, Don't merge yet

#709 update(Group): Fix crash when remove users from group
  common/locales/en-US/main.ftl
  common/src/state/mod.rs
  common/src/warp_runner/manager/commands/raygun_commands.rs
  common/src/warp_runner/ui_adapter/message_event.rs
  ui/src/components/chat/compose/mod.rs
  ui/src/components/chat/create_group.rs
  ui/src/components/chat/edit_group.rs
  ui/src/components/chat/style.scss
Labels: QA Tested, Ready to Merge

#706 chore(cargo): Update dependency
  Cargo.lock
  Cargo.toml
Labels: QA Tested, Ready to Merge

#705 fix(searchbar): fix styling for the searchbar
  ui/src/components/chat/sidebar.rs
  ui/src/components/chat/style.scss
Labels: QA Tested, Ready to Merge, Failed Automated Test

#717 fix(Login): Just accept enter if is new account
  ui/src/layouts/unlock.rs
Labels: QA Tested, Don't merge yet, Failed Automated Test

#714 chore(Nav): don't show tooltips on bubble navs
  kit/src/components/nav/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#722 chore(typo): fix typo
  ui/docs/testing/uplink-checklist.md
Labels: QA Tested, Missing dev review, Don't merge yet

#720 chore(ci): remove ci
  .github/workflows/fix-typos.yml
Labels: QA Tested, Missing dev review, Don't merge yet, Failed Automated Test

#724 chore(docs): minor suggestions
  ui/docs/testing/uplink-checklist.md
Labels: QA Override

#712 chore(loading): refactor state initalization
  common/src/state/chats.rs
  common/src/state/friends.rs
  common/src/state/mod.rs
  common/src/testing/mock.rs
  common/src/warp_runner/manager/commands/multipass_commands.rs
  common/src/warp_runner/manager/commands/raygun_commands.rs
  common/src/warp_runner/ui_adapter/mod.rs
  common/src/warp_runner/ui_adapter/raygun_event.rs
  ui/src/components/chat/compose/mod.rs
  ui/src/components/chat/sidebar.rs
  ui/src/layouts/loading.rs
  ui/src/main.rs
Labels: QA Tested, Ready to Merge, missing fixing conflict

#707 fix(friends): Blocked text fix
  common/locales/en-US/main.ftl
  ui/src/components/friends/friend/mod.rs
  ui/src/components/friends/incoming_requests/mod.rs
  ui/src/components/friends/outgoing_requests/mod.rs
Labels: QA Tested, Ready to Merge

#723 fix(Storage): Fix bug on storage with file preview
  ui/src/layouts/storage.rs
  ui/src/main.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#718 update(Reply): Fix reply baloon color
  common/src/warp_runner/ui_adapter/mod.rs
  kit/src/components/message_reply/mod.rs
  ui/src/components/chat/compose/messages.rs
Labels: Changes requested, Missing dev review, Don't merge yet

#726 fix(autofocus): don't focus on input bar when editing or reacting
  common/src/state/ui.rs
  kit/src/components/message/mod.rs
  kit/src/elements/textarea/mod.rs
  kit/src/layout/chatbar/mod.rs
  launch_docker.sh
  ui/src/components/chat/compose/chatbar.rs
  ui/src/components/chat/compose/messages.rs
  ui/src/components/chat/compose/mod.rs
Labels: QA Tested, Ready to Merge

#634 feat(chat): Link preview
  Cargo.lock
  Cargo.toml
  kit/Cargo.toml
  kit/src/components/link_embed/mod.rs
  kit/src/components/link_embed/style.scss
  kit/src/components/message/mod.rs
  kit/src/components/message/style.scss
  kit/src/components/mod.rs
  kit/src/style.scss
  ui/extra/themes/default.scss
  ui/extra/themes/light.scss
Labels: QA Tested, Ready to Merge, Failed Automated Test

#727 chore(appium): delete chat accounts only if jobs succeeded
  .github/workflows/ui-test-execution.yml
Labels: Missing dev review, Draft, Don't merge yet

#730 fix(Tooltip): Fix opacity in tooltip coming soon
  kit/src/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#737 fix(installer): fix build script for linux installer
  build_linux_installer.sh
Labels: Missing dev review, Don't merge yet

#733 feat(downloads): track when attachment is being downloaded
  kit/src/components/file_embed/mod.rs
  kit/src/components/message/mod.rs
  ui/src/components/chat/compose/messages.rs
Labels: QA Tested, Ready to Merge

#740 fix(workflow): linux and mac build scripts
  .github/workflows/build-dmg-universal.yml
  .github/workflows/build-release-linux.yml
  Cargo.lock
  Cargo.toml
  Makefile
Labels: Missing dev review, Don't merge yet

#742 fix(build): try to fix build for dmg
  Cargo.lock
  Cargo.toml
  Makefile
Labels: Ready to Merge, QA Override

#743 fix(installer): use lipo to pack dylibs for mac installer
  Cargo.lock
  Cargo.toml
  Makefile
Labels: Missing dev review, Don't merge yet, QA Override

#748 chore(appium): continue next steps on building app
  .github/workflows/ui-test-execution.yml
  .github/workflows/ui-test-windows.yml
Labels: Missing dev review, Don't merge yet

#752 chore(update): read me
  README.md
Labels: Missing dev review, Don't merge yet

#750 fix(messages): dont use LinkFinder::spans
  kit/src/components/message/mod.rs
Labels: QA Tested, Waiting for CI

#749 fix(rendering): don't re-render every 5 seconds
  ui/src/main.rs
  ui/src/window_manager/mod.rs
Labels: Waiting for CI

#751 chore(ci): auto update bot
  .github/workflows/auto-update.yml
Labels: Ready to Merge

#755 chore(autoupdate): remove autoupdate new action
  .github/workflows/auto-update.yml
Labels: Ready to Merge, QA Override

#741 fix(Popout): Fix all popout when close app on windows
  kit/src/components/topbar_controls/mod.rs
Labels: Missing dev review, Don't merge yet, Waiting for CI

#753 chore(appium): only remove test accounts if both chats jobs succeeded
  .github/workflows/ui-test-execution.yml
Labels: Missing dev review, Don't merge yet

#754 chore(update): update modal added
  common/locales/en-US/main.ftl
  kit/src/components/mod.rs
  kit/src/components/modal/mod.rs
  kit/src/components/modal/styles.scss
  ui/src/components/settings/sub_pages/about.rs
  ui/src/main.rs
  ui/src/style.scss
  ui/src/utils/auto_updater.rs
Labels: Missing dev review, Don't merge yet
