Repository Satellite-im/Uplink, pull requests merged in 2023-05, with the labels that each got.

#738 feat(groups): Add blocked message functionality
  common/locales/en-US/main.ftl
  ui/src/components/chat/compose/messages.rs
  ui/src/components/chat/style.scss
Labels: Ready to Merge

#739 chore(locales): pt-PT
  common/locales/pt-PT/main.ftl
Labels: Missing dev review, Don't merge yet

#757 chore(docs): minor suggestion
  README.md
Labels: Missing dev review, Don't merge yet

#758 fix(WIndow): fix window move clicking on background
  ui/src/main.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#744 fix(ui): Fix group chat picture over hover effect when upload a file
  ui/src/layouts/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#736 update(ChatBar): Add message when user reach maximum of 1024 chars
  common/locales/en-US/main.ftl
  kit/src/elements/textarea/mod.rs
  ui/src/components/chat/compose/chatbar.rs
  ui/src/components/chat/style.scss
Labels: QA Tested, Ready to Merge, Waiting for CI

#770 chore(appium): build only for x86_64 target on appium workflow
  .github/workflows/ui-test-execution.yml
Labels: Don't merge yet, Waiting for CI

#773 chore(appium): build only for x86_64 target on appium workflow - revert
  .github/workflows/ui-test-execution.yml
Labels: Missing dev review, Don't merge yet

#774 chore(locales): add more pt-PT locales
  common/locales/pt-PT/main.ftl
Labels: QA Tested, Missing dev review, Don't merge yet

#779 fix(EditMsg): Fix jump line when enter on edit msg
  kit/src/components/message/mod.rs
Labels: Don't merge yet, Waiting for CI

#783 fix(pkg): fix the .dpkg file not found
  Cargo.lock
  Cargo.toml
  ui/src/utils/auto_updater.rs
Labels: Missing dev review, Don't merge yet, Waiting for CI

#782 feat(update): display toast after checking for updates
  common/locales/en-US/main.ftl
  ui/src/components/settings/sub_pages/about.rs
Labels: Waiting for CI

#784 chore(locales): add more pt-PT locales
  common/locales/pt-PT/main.ftl
Labels: Missing dev review, Don't merge yet

#788 chore(windows): add signing task to windows action
  .github/workflows/build-release-windows.yml
Labels: Missing dev review, Don't merge yet

#787 fix(notification): Move notification into separate thread
  common/src/notifications.rs
Labels: QA Tested, Ready to Merge

#795 chore(ci): add ci
  .github/workflows/new-ticket-label-issue.yml
Labels: Missing dev review, Don't merge yet

#791 update(ui): add aria labels required for ui tests locators
  kit/src/components/context_menu/mod.rs
  kit/src/components/link_embed/mod.rs
  kit/src/components/message/mod.rs
  kit/src/components/message_group/mod.rs
  kit/src/components/message_typing/mod.rs
  kit/src/components/toast/mod.rs
  kit/src/elements/label/mod.rs
  kit/src/layout/chatbar/mod.rs
  ui/src/components/chat/compose/messages.rs
  ui/src/components/chat/compose/quick_profile.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/friends/blocked/mod.rs
  ui/src/components/friends/friend/mod.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/friends/incoming_requests/mod.rs
  ui/src/components/friends/outgoing_requests/mod.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/layouts/storage.rs
  ui/src/main.rs
Labels: QA Tested, Ready to Merge, Waiting for CI

#800 chore(ci): improve ci
  .github/workflows/new-ticket-label-issue.yml
Labels: Missing dev review, Don't merge yet

#785 chore(cargo): Update dependency
  Cargo.lock
  Cargo.toml
Labels: QA Tested, Ready to Merge

#807 fix(overlays): temporary fix for windows overlay bug
  .github/workflows/cargo.yml
  ui/src/components/settings/sub_pages/general.rs
  ui/src/main.rs
Labels: Missing dev review, Don't merge yet

#809 fix(settings): Fix accessibility width
  ui/src/components/settings/styles.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#810 fix(clearall): remove clear all extension till the implementation is done
  Cargo.toml
Labels: QA Tested, Ready to Merge

#781 chore(General): Tweaked Lunar Eclipse theme and other small fixes.
  kit/src/components/indicator/mod.rs
  kit/src/components/indicator/style.scss
  kit/src/components/user_image_group/styles.scss
  kit/src/elements/checkbox/style.scss
  ui/Cargo.toml
  ui/extra/themes/lunar-eclipse.css
  ui/src/components/chat/edit_group.rs
  ui/src/components/chat/style.scss
Labels: Ready to Merge

#808 chore(cargo): Update dependency
  Cargo.lock
  Cargo.toml
  common/src/warp_runner/manager/commands/constellation_commands.rs
Labels: Ready for testing, Missing dev review, Don't merge yet

#811 chore(dependencies): remove unused dependencies
  Cargo.lock
  common/Cargo.toml
  ui/Cargo.toml
Labels: Ready to Merge

#803 update(FilePreview): Change file preview window to modal
  common/locales/en-US/main.ftl
  common/locales/pt-BR/main.ftl
  common/src/state/action.rs
  common/src/state/mod.rs
  common/src/state/ui.rs
  kit/src/components/modal/mod.rs
  ui/src/layouts/file_preview.rs
  ui/src/layouts/storage.rs
  ui/src/window_manager/mod.rs
Labels: Ready for testing, Missing dev review, Don't merge yet

#813 chore(cargo): Update dependency
  Cargo.lock
  Cargo.toml
  common/src/warp_runner/manager/commands/raygun_commands.rs
Labels: Missing dev review, Don't merge yet, already tested - to be checked when to merge

#797 update(UI): Refactor storage space UI
  common/locales/en-US/main.ftl
  common/src/warp_runner/manager/commands/constellation_commands.rs
  ui/src/components/chat/compose/mod.rs
  ui/src/layouts/file_preview.rs
  ui/src/layouts/storage.rs
  ui/src/layouts/storage/controller.rs
  ui/src/layouts/storage/functions.rs
  ui/src/layouts/storage/mod.rs
  ui/src/layouts/storage/storage.js
Labels: Don't merge yet, already tested - to be checked when to merge

#817 chore(locales): update pt-PT locales
  common/locales/pt-PT/main.ftl
Labels: Missing dev review, Don't merge yet

#819 fix(deb): include dependencies in linux installer
  ui/deb/DEBIAN/control
Labels: Missing dev review, Draft, Don't merge yet

#820 update(controls): removed state from kit component
  kit/src/components/topbar_controls/mod.rs
  ui/extra/themes/lunar-eclipse.css
Labels: Ready for testing, Don't merge yet

#831 chore(typo): fix typo
  common/src/warp_runner/manager/commands/raygun_commands.rs
Labels: Missing dev review, Don't merge yet

#824 chore(update): improve locale
  common/locales/en-US/main.ftl
Labels: Missing dev review, Don't merge yet

#833 chore(locales): update spanish mx translations file
  common/locales/es-MX/main.ftl
Labels: Missing dev review, Don't merge yet

#832 chore(scroll): when chat has content is not scrolling everything
  kit/src/components/message_group/style.scss
Labels: Missing dev review, Don't merge yet

#828 chore(cargo): Update dependency
  Cargo.lock
  Cargo.toml
  common/src/lib.rs
  common/src/warp_runner/manager/commands/constellation_commands.rs
  common/src/warp_runner/manager/commands/mod.rs
  common/src/warp_runner/mod.rs
  ui/src/layouts/file_preview.rs
  ui/src/layouts/storage/mod.rs
Labels: Ready for testing, Ready to Merge

#829 chore(build): minor build updates
  .github/workflows/build-dmg-universal.yml
  .github/workflows/build-release-linux.yml
  Cargo.lock
  Cargo.toml
  Makefile
  ui/deb/DEBIAN/control
  ui/wix/main.wxs
Labels: Missing dev review, Don't merge yet, already tested

#844 fix(chat): Add padding to msg end
  ui/src/components/chat/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#843 fix(settings): Fix selection order being random
  kit/src/elements/select/mod.rs
Labels: QA Tested, Don't merge yet, Ready to Merge

#849 chore(appium): test chats in one GH runner and refactor test workflow
  .github/workflows/ui-test-automation.yml
  .github/workflows/ui-test-execution.yml
  .github/workflows/ui-test-windows.yml
Labels: Ready for testing, Don't merge yet

#847 chore(hide): hide features
  ui/src/components/settings/sidebar.rs
  ui/src/components/settings/sub_pages/files.rs
  ui/src/components/settings/sub_pages/general.rs
  ui/src/components/settings/sub_pages/notifications.rs
  ui/src/components/settings/sub_pages/privacy.rs
  ui/src/layouts/settings.rs
Labels: QA Tested

#728 feat(chat): Attachment visualizer
  kit/src/components/file_embed/mod.rs
  kit/src/components/file_embed/style.scss
  kit/src/components/message/mod.rs
  kit/src/components/message/style.scss
  kit/src/components/message_reply/mod.rs
  kit/src/components/message_reply/style.scss
  kit/src/layout/chatbar/mod.rs
Labels: Missing dev review, Don't merge yet

#848 feat(chat): Expand group click area
  kit/src/layout/topbar/mod.rs
  kit/src/layout/topbar/style.scss
  ui/src/components/chat/compose/mod.rs
Labels: Changes requested, Missing dev review, Don't merge yet, Failed Automated Test
