Repository Satellite-im/Uplink, pull requests merged in 2023-03, with the labels that each got.

#336 chore(chat): Add chat soft return (for #308)
  kit/src/components/message/mod.rs
  kit/src/elements/input/mod.rs
  kit/src/elements/input/script.js
  kit/src/elements/input/style.scss
  kit/src/elements/input/update_input_height.js
  kit/src/layout/chatbar/mod.rs
Labels: QA Tested, Ready to Merge

#349 chore(Unlock): first pass at making the unlock page a bit cleaner
  common/locales/en-US/main.ftl
  kit/src/components/message/mod.rs
  kit/src/elements/input/mod.rs
  ui/src/layouts/style.scss
  ui/src/layouts/unlock.rs
  ui/src/main.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#348 chore(appium): add windows CI tests workflow
  .github/workflows/ui-test-windows.yml
Labels: QA Tested, Missing dev review, Don't merge yet

#359 hotfix(Compose): Hotfix broken minimal view code
  ui/src/layouts/chat.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#354 fix(input): make separate elements for input and textarea
  common/locales/en-US/main.ftl
  kit/src/elements/input/mod.rs
  kit/src/elements/input/script.js
  kit/src/elements/input/style.scss
  kit/src/elements/mod.rs
  kit/src/elements/multiline/mod.rs
  kit/src/elements/textarea/mod.rs
  kit/src/elements/textarea/script.js
  kit/src/elements/textarea/style.scss
  kit/src/elements/textarea/update_input_height.js
  kit/src/layout/chatbar/mod.rs
  ui/src/components/chat/sidebar.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#360 chore(cargo): Update dependency
  common/Cargo.toml
  common/src/warp_runner/mod.rs
  extensions/Cargo.toml
  kit/Cargo.toml
  ui/Cargo.toml
Labels: QA Tested, Missing dev review, Don't merge yet

#363 Fix blank language dropdown on new accounts
  common/src/language/mod.rs
  common/src/state/settings.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#364 add favorite/unfavorite to friend context menu
  icons/src/icons/outline/heart_slash.svg
  ui/src/components/chat/compose.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/friends/friends_list/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#367 Add files via upload
  icons/src/icons/outline/heart-slash.svg
  icons/src/icons/outline/satellite.svg
Labels: Missing dev review, Don't merge yet

#361 Art unlock
  common/locales/en-US/main.ftl
  common/locales/es-MX/main.ftl
  common/locales/pt-BR/main.ftl
  common/locales/pt-PT/main.ftl
  kit/src/components/toast/style.scss
  kit/src/layout/sidebar/style.scss
  kit/src/style.scss
  ui/extra/themes/default.scss
  ui/src/components/README.md
  ui/src/components/calldialog/style.scss
  ui/src/components/chat/welcome/style.scss
  ui/src/components/settings/sidebar.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/components/settings/sub_pages/profile/style.scss
  ui/src/components/style.scss
  ui/src/layouts/settings.rs
  ui/src/layouts/style.scss
  ui/src/layouts/unlock.rs
  ui/src/main.rs
Labels: Missing dev review, Don't merge yet

#350 chore(files): update to files css to make things line up nicer
  kit/src/components/file_embed/style.scss
  kit/src/elements/file/mod.rs
  kit/src/elements/file/style.scss
  kit/src/elements/folder/mod.rs
  kit/src/elements/folder/style.scss
  kit/src/style.scss
  ui/src/layouts/storage.rs
  ui/src/layouts/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#369 chore(sidebar): fix issue where main content was overlapping
  ui/src/components/chat/welcome/style.scss
Labels: QA Tested

#357 fix(error): toast error alert on add friend errors
  common/locales/en-US/main.ftl
  ui/src/components/friends/add.rs
Labels: QA Tested, Ready to Merge

#370 chore(appium): update to GH workflow for MacOS tests
  .github/workflows/ui-test-execution.yml
Labels: QA Tested, Missing dev review

#372 chore(Emotes): Added mascot emotes now so we don't lose them
  ui/extra/images/mascot/emotes/1.png
  ui/extra/images/mascot/emotes/10.png
  ui/extra/images/mascot/emotes/11.png
  ui/extra/images/mascot/emotes/12.png
  ui/extra/images/mascot/emotes/13.png
  ui/extra/images/mascot/emotes/14.png
  ui/extra/images/mascot/emotes/15.png
  ui/extra/images/mascot/emotes/16.png
  ui/extra/images/mascot/emotes/17.png
  ui/extra/images/mascot/emotes/18.png
  ui/extra/images/mascot/emotes/2.png
  ui/extra/images/mascot/emotes/3.png
  ui/extra/images/mascot/emotes/4.png
  ui/extra/images/mascot/emotes/5.png
  ui/extra/images/mascot/emotes/6.png
  ui/extra/images/mascot/emotes/7.png
  ui/extra/images/mascot/emotes/8.png
  ui/extra/images/mascot/emotes/9.png
Labels: Missing dev review, Don't merge yet

#377 fix(friends): remove Favorite/Unfavorite option for not initialized chat
  ui/src/components/friends/friends_list/mod.rs
Labels: Missing dev review, Don't merge yet

#375 chore(cargo): Update dependency
  common/Cargo.toml
  common/src/warp_runner/manager/commands/raygun_commands.rs
  extensions/Cargo.toml
  kit/Cargo.toml
  ui/Cargo.toml
Labels: QA Tested, Ready to Merge

#376 add(config): add launch.json for VSC
  .vscode/launch.json
Labels: QA Tested, Ready to Merge

#385 chore(typo): fix typo
  ui/src/main.rs
Labels: QA Tested, Ready to Merge

#381 chore(cargo): Update dependency
  common/Cargo.toml
  extensions/Cargo.toml
  kit/Cargo.toml
  ui/Cargo.toml
Labels: Ready for testing, Don't merge yet

#382 chore(settings): Move profile to the top of the sidebar
  ui/src/components/settings/sidebar.rs
Labels: QA Tested, Don't merge yet

#378 feat(profile): wire up profile to warp
  common/src/state/account.rs
  common/src/state/identity.rs
  common/src/state/mod.rs
  common/src/warp_runner/manager/commands/multipass_commands.rs
  common/src/warp_runner/mod.rs
  kit/src/elements/file/mod.rs
  kit/src/elements/input/mod.rs
  kit/src/elements/textarea/mod.rs
  kit/src/layout/topbar/mod.rs
  ui/Cargo.toml
  ui/src/components/chat/compose.rs
  ui/src/components/friends/add.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/layouts/create_account.rs
  ui/src/layouts/unlock.rs
  ui/src/main.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#391 chore(workflow): fix workflow
  .github/workflows/cargo.yml
Labels: Missing dev review, Don't merge yet

#393 fix(workflow): install libwebkit2g2k
  .github/workflows/cargo.yml
Labels: Missing dev review, Don't merge yet

#390 update(Readme): Add instructions to install ffmpeg
  README.md
Labels: QA Tested, Missing dev review, Don't merge yet

#380 feat(messages): edit messages
  common/locales/en-US/main.ftl
  common/src/state/mod.rs
  common/src/testing/mock.rs
  common/src/warp_runner/manager/commands/raygun_commands.rs
  common/src/warp_runner/ui_adapter/message_event.rs
  common/src/warp_runner/ui_adapter/mod.rs
  kit/src/components/message/mod.rs
  kit/src/elements/textarea/mod.rs
  ui/src/components/chat/compose.rs
  ui/src/components/friends/add.rs
  ui/src/layouts/chat.rs
  ui/src/layouts/storage.rs
  ui/src/main.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#389 feat(friends): Add "accept" option to pending friend context menu
  ui/src/components/friends/incoming_requests/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#387 feat(chat): Default sidebar message for new chat
  common/locales/en-US/main.ftl
  ui/src/components/chat/sidebar.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#401 chore(workflow): fix clippy workflow
  .github/workflows/cargo.yml
Labels: Missing dev review

#398 chore(state): unify data model concerning identities
  common/src/state/action.rs
  common/src/state/chats.rs
  common/src/state/friends.rs
  common/src/state/mod.rs
  common/src/testing/mock.rs
  common/src/warp_runner/manager/commands/multipass_commands.rs
  common/src/warp_runner/manager/commands/raygun_commands.rs
  common/src/warp_runner/ui_adapter/mod.rs
  common/src/warp_runner/ui_adapter/raygun_event.rs
  ui/src/components/chat/compose.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/friends/blocked/mod.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/friends/incoming_requests/mod.rs
  ui/src/components/friends/outgoing_requests/mod.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/layouts/chat.rs
  ui/src/layouts/friends.rs
  ui/src/layouts/storage.rs
  ui/src/main.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#397 chore(Extensions): fix extensions setting page in prep for market
  common/locales/en-US/main.ftl
  common/src/state/action.rs
  common/src/state/mod.rs
  extensions/src/lib.rs
  native_extensions/emoji_selector/src/lib.rs
  ui/src/components/chat/compose.rs
  ui/src/components/settings/styles.scss
  ui/src/components/settings/sub_pages/extensions.rs
  ui/src/extensions/browser.rs
  ui/src/extensions/extensions.scss
  ui/src/extensions/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#406 fix(clippy)
  ui/src/components/settings/sub_pages/extensions.rs
  ui/src/extensions/browser.rs
Labels: Missing dev review, Don't merge yet

#403 feat(identity): show online indicator and platform
  common/src/state/account.rs
  common/src/state/action.rs
  common/src/state/identity.rs
  common/src/state/mod.rs
  common/src/warp_runner/manager/commands/multipass_commands.rs
  common/src/warp_runner/ui_adapter/mod.rs
  kit/src/components/indicator/mod.rs
  kit/src/components/user_image_group/mod.rs
  ui/src/components/chat/compose.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/friends/blocked/mod.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/friends/incoming_requests/mod.rs
  ui/src/components/friends/outgoing_requests/mod.rs
  ui/src/components/settings/sub_pages/developer.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/main.rs
  ui/src/utils/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#411 feat(settings): add toast and improve input element
  common/locales/en-US/main.ftl
  common/src/state/ui.rs
  kit/src/elements/input/mod.rs
  ui/src/components/friends/add.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#412 chore(state): rearrange state
  common/src/state/mod.rs
Labels: Ready for testing, QA Tested, Missing dev review

#384 chore(cargo): Restructure workspace Cargo.toml
  Cargo.toml
  common/Cargo.toml
  extension_example/Cargo.toml
  extensions/Cargo.toml
  icons/Cargo.toml
  kit/Cargo.toml
  ui/Cargo.toml
Labels: QA Tested, Missing dev review, Don't merge yet

#426 feat(lang): Add german translation
  common/locales/de/main.ftl
  common/src/language/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#392 chore(appium): remove step to run appium server in background
  .github/workflows/ui-test-execution.yml
  .github/workflows/ui-test-windows.yml
Labels: Missing dev review

#433 refactor(Unlock): Apply theme on login
  ui/src/layouts/unlock.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#432 refactor(AutoFocus): Focus on ChatBar when you change chats and when reply
  icons/build.rs
  kit/src/elements/textarea/focus.js
  kit/src/elements/textarea/mod.rs
  kit/src/layout/chatbar/mod.rs
  ui/src/components/chat/compose.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#415 fix(input): save changes on mouseout
  kit/src/elements/input/mod.rs
  ui/src/components/friends/add.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#435 feat(settings): Clear button user settings
  kit/src/elements/input/mod.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
Labels: QA Tested

#438 fix(notification): make sound when chat UI is not active
  common/src/state/action.rs
  common/src/state/mod.rs
  ui/src/layouts/chat.rs
  ui/src/utils/lifecycle.rs
  ui/src/utils/mod.rs
Labels: Missing dev review, Don't merge yet

#430 chore(cargo): Update dependency
  Cargo.toml
  common/src/lib.rs
  common/src/warp_runner/manager/commands/multipass_commands.rs
  common/src/warp_runner/mod.rs
Labels: QA Tested, Ready to Merge

#448 fix(context Menu): Fix ids sent to the context menu script
  kit/src/components/context_menu/mod.rs
Labels: QA Tested, Missing dev review, Ready to Merge

#447 chore(identity): Update friends identity upon update event
  common/src/state/mod.rs
  common/src/warp_runner/ui_adapter/multipass_event.rs
  ui/src/main.rs
Labels: QA Tested, Ready to Merge

#442 feat(conversations): clear unreads and move chats to top of sidebar
  common/src/state/action.rs
  common/src/state/chats.rs
  common/src/state/mod.rs
  common/src/testing/mock.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/friends/friends_list/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#414 feat(cache): export cache
  common/Cargo.toml
  common/src/warp_runner/manager/commands/mod.rs
  common/src/warp_runner/manager/commands/other_commands.rs
  common/src/warp_runner/manager/events.rs
  common/src/warp_runner/manager/mod.rs
  common/src/warp_runner/mod.rs
  ui/src/components/settings/sub_pages/developer.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#460 feat(chat): lazy load messages
  common/src/state/action.rs
  common/src/state/chats.rs
  common/src/state/mod.rs
  ui/src/components/chat/compose.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/friends/blocked/mod.rs
  ui/src/components/friends/friend/mod.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/friends/incoming_requests/mod.rs
  ui/src/components/friends/outgoing_requests/mod.rs
  ui/src/utils/format_timestamp.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#434 fix(textarea): add onblur to textarea to fix click out of edit
  kit/src/components/message/mod.rs
  kit/src/elements/input/mod.rs
  kit/src/elements/textarea/mod.rs
  kit/src/layout/chatbar/mod.rs
  ui/src/components/chat/compose.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#461 chore(cargo): Update dependency
  Cargo.toml
Labels: QA Tested, Ready to Merge

#429 feat(FilePreview): Possible to see a preview of Image, Video and PDF Files
  Cargo.toml
  common/locales/en-US/main.ftl
  common/locales/es-MX/main.ftl
  common/locales/pt-BR/main.ftl
  common/locales/pt-PT/main.ftl
  common/src/lib.rs
  common/src/state/action.rs
  common/src/state/mod.rs
  common/src/state/ui.rs
  common/src/warp_runner/manager/commands/constellation_commands.rs
  kit/src/elements/file/mod.rs
  kit/src/elements/file/style.scss
  kit/src/elements/folder/style.scss
  ui/Cargo.toml
  ui/src/components/chat/compose.rs
  ui/src/components/media/player.rs
  ui/src/components/media/popout_player.rs
  ui/src/components/media/remote_control.rs
  ui/src/layouts/file_preview.rs
  ui/src/layouts/mod.rs
  ui/src/layouts/storage.rs
  ui/src/layouts/style.scss
  ui/src/main.rs
  ui/src/utils/mod.rs
  ui/src/window_manager/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#467 feat(chats): lazier loading
  common/src/state/mod.rs
  kit/src/components/context_menu/mod.rs
  ui/src/components/chat/compose.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#466 chore(cargo): Update workspace dependencies
  Cargo.toml
  common/Cargo.toml
Labels: QA Tested, Ready to Merge

#470 fix(config): Remove additional entry in Cargo.toml
  Cargo.toml
Labels: Missing dev review, Don't merge yet

#468 fix(sidebar): Fix missing scrollbar in sidebar
  ui/src/layouts/style.scss
  ui/src/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#463 fix(input): add num pad enter to keyup
  kit/src/elements/input/mod.rs
  kit/src/elements/textarea/mod.rs
Labels: Changes requested, QA Tested, Don't merge yet

#473 feat(settings): Add did + copy field to profile setting again
  common/locales/en-US/main.ftl
  kit/src/elements/button/style.scss
  kit/src/elements/mod.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/components/settings/sub_pages/profile/style.scss
Labels: Missing dev review, Don't merge yet

#478 feat(favorites): show profile picture in favorites
  .rustfmt.toml
  kit/src/components/user_image_group/mod.rs
  native_extensions/emoji_selector/src/lib.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#486 update(UserTyping): Add profile picture
  ui/src/components/chat/compose.rs
Labels: QA Tested, Ready to Merge

#483 update(ChatFile): Adjust download file from chat
  common/src/warp_runner/manager/commands/raygun_commands.rs
  ui/src/components/chat/compose.rs
Labels: QA Tested, Ready to Merge

#485 chore(cargo): Update dependency
  Cargo.toml
  common/src/warp_runner/mod.rs
  common/src/warp_runner/ui_adapter/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#496 chore(build): add signed mac builds back to tag creation (releases in github)
  .github/workflows/build-dmg-universal.yml
  Makefile
Labels: QA Tested, Missing dev review, Don't merge yet

#493 update(StatusMessage): Fix 128 chars status
  common/src/state/mod.rs
  ui/src/components/friends/friend/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#491 feat(files): Remove bottom corner rect of scrollbars
  ui/src/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#445 feat(chat): Disable various chat feature if not friend anymore
  common/locales/en-US/main.ftl
  common/src/state/mod.rs
  kit/src/elements/textarea/mod.rs
  kit/src/elements/textarea/script.js
  kit/src/elements/textarea/style.scss
  kit/src/elements/tooltip/mod.rs
  kit/src/layout/chatbar/mod.rs
  ui/src/components/chat/compose.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#492 feat(chats): fetch messages from warp on demand
  common/src/state/chats.rs
  common/src/state/mod.rs
  common/src/testing/mock.rs
  common/src/warp_runner/manager/commands/raygun_commands.rs
  common/src/warp_runner/ui_adapter/mod.rs
  ui/src/components/chat/compose.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#504 chore(windows): hide textarea scrollbar that shows up in windows only
  kit/src/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#506 add(aria): add aria labels for chat tests creation
  kit/src/components/indicator/mod.rs
  kit/src/components/message/mod.rs
  kit/src/components/message_group/mod.rs
  kit/src/components/message_reply/mod.rs
  kit/src/components/user_image/mod.rs
  kit/src/elements/textarea/mod.rs
  ui/src/components/chat/compose.rs
Labels: Missing dev review

#515 fix(ChatButton): Fix chat button to not hide on resize app
  ui/src/components/chat/style.scss
Labels: Missing dev review, Don't merge yet

#539 fix(Pathing): Fixed nested themes folder
  common/src/lib.rs
  kit/src/fonts/AmaticSC-Regular.ttf
  kit/src/fonts/NotoSans-Black.ttf
  kit/src/fonts/NotoSans-BlackItalic.ttf
  kit/src/fonts/NotoSans-Bold.ttf
  kit/src/fonts/NotoSans-BoldItalic.ttf
  kit/src/fonts/NotoSans-ExtraBold.ttf
  kit/src/fonts/NotoSans-ExtraBoldItalic.ttf
  kit/src/fonts/NotoSans-ExtraLight.ttf
  kit/src/fonts/NotoSans-ExtraLightItalic.ttf
  kit/src/fonts/NotoSans-Italic.ttf
  kit/src/fonts/NotoSans-Light.ttf
  kit/src/fonts/NotoSans-LightItalic.ttf
  kit/src/fonts/NotoSans-Medium.ttf
  kit/src/fonts/NotoSans-MediumItalic.ttf
  kit/src/fonts/NotoSans-SemiBold.ttf
  kit/src/fonts/NotoSans-SemiBoldItalic.ttf
  kit/src/fonts/NotoSans-Thin.ttf
  kit/src/fonts/NotoSans-ThinItalic.ttf
  kit/src/fonts/OpenDyslexic-Regular.otf
  kit/src/fonts/OpenSans-Variable.ttf
  kit/src/fonts/Roboto-Regular.ttf
  kit/src/style.scss
  ui/src/main.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#516 fix(calling): disable options to use voice and video calling
  common/src/lib.rs
  kit/src/elements/button/mod.rs
  ui/src/components/chat/compose.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#503 feat(chats): group chats
  common/src/state/action.rs
  common/src/state/chats.rs
  common/src/state/mod.rs
  common/src/testing/mock.rs
  common/src/warp_runner/manager/commands/raygun_commands.rs
  common/src/warp_runner/ui_adapter/mod.rs
  kit/src/components/user_image/mod.rs
  kit/src/components/user_image_group/mod.rs
  kit/src/elements/checkbox/mod.rs
  kit/src/elements/checkbox/style.scss
  kit/src/elements/input/mod.rs
  kit/src/elements/mod.rs
  ui/src/components/chat/compose.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/chat/style.scss
  ui/src/components/friends/friends_list/mod.rs
  ui/src/layouts/create_group.rs
  ui/src/layouts/mod.rs
  ui/src/layouts/style.scss
  ui/src/main.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#531 fix(login): Login page displays "UNKNOWN"
  common/locales/en-US/main.ftl
  common/src/language/mod.rs
  common/src/state/mod.rs
  common/src/state/ui.rs
  kit/src/elements/input/mod.rs
  ui/src/extension_browser/mod.rs
  ui/src/layouts/unlock.rs
Labels: Changes requested, Missing dev review, Don't merge yet

#538 fix(welcome): make settings welcome active again
  common/src/state/ui.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
Labels: QA Tested, Ready to Merge

#540 fix(username): profile username number types mixed up
  ui/src/components/settings/sub_pages/profile/mod.rs
Labels: QA Tested, Ready to Merge

#518 update(Reply): Add possibility to reply with attachments
  common/src/warp_runner/manager/commands/raygun_commands.rs
  ui/src/components/chat/compose.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#533 fix(DragAndDrop): Fix wrong feedback when user is not dragging a file
  native_extensions/emoji_selector/src/lib.rs
  ui/src/components/chat/compose.rs
  ui/src/layouts/storage.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#526 feat(OpenDyslexic): Adds an option to toggle support for open dyslexic font faces
  common/locales/en-US/main.ftl
  common/locales/pt-BR/main.ftl
  common/src/state/action.rs
  common/src/state/configuration.rs
  kit/src/components/file_embed/style.scss
  kit/src/elements/file/style.scss
  kit/src/elements/folder/style.scss
  kit/src/style.scss
  native_extensions/emoji_selector/src/lib.rs
  ui/Config.toml
  ui/docs/testing/uplink-checklist.md
  ui/src/components/settings/sidebar.rs
  ui/src/components/settings/styles.scss
  ui/src/components/settings/sub_pages/accessibility.rs
  ui/src/components/settings/sub_pages/general.rs
  ui/src/components/settings/sub_pages/mod.rs
  ui/src/layouts/settings.rs
  ui/src/layouts/storage.rs
  ui/src/main.rs
  ui/src/open-dyslexic.css
  ui/src/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#547 chore(CSS): touch up a bunch of style stuff
  Makefile
  kit/src/components/file_embed/style.scss
  kit/src/components/message_group/mod.rs
  kit/src/elements/button/style.scss
  kit/src/elements/checkbox/style.scss
  kit/src/layout/sidebar/style.scss
  kit/src/style.scss
  ui/src/components/chat/create_group.rs
  ui/src/components/chat/mod.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/chat/style.scss
  ui/src/layouts/mod.rs
  ui/src/layouts/style.scss
  ui/src/main.rs
Labels: QA Tested, Missing dev review, Don't merge yet, Conflicts

#550 chore(appium): update concurrency in appium workflow
  .github/workflows/ui-test-execution.yml
  .github/workflows/ui-test-windows.yml
Labels: QA Tested, Ready to Merge

#559 Hotfix 2
  .gitignore
  Cargo.toml
  common/src/state/ui.rs
  extensions/src/lib.rs
  native_extensions/clear_all/src/lib.rs
  ui/src/main.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#556 chore(Sidebar): fix double scrollbar bug
  kit/src/layout/sidebar/style.scss
  ui/src/components/chat/sidebar.rs
  ui/src/components/chat/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#564 chore(cargo): Update dependency
  .gitignore
  Cargo.lock
  Cargo.toml
Labels: QA Tested, Missing dev review, Don't merge yet
