Repository Satellite-im/Uplink, pull requests merged in 2023-12, with the labels that each got.

#1573 chore(readme): Fix the binary name
  README.md
Labels: QA Override

#1569 chore(cargo): Update dependency
  Cargo.lock
  Cargo.toml
Labels: QA Tested, Ready to Merge

#1575 fix(ui): Fix context item height
  kit/src/components/context_menu/style.scss
Labels: Don't merge yet, Waiting for CI

#1554 feat(sidebar): move chat to top of sidebar when call is offered/answered
  Cargo.lock
  common/src/state/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1582 chore(readme): Dependencies instructions for Fedora 38
  README.md
Labels: Missing dev review, Don't merge yet

#1584 chore(vscode): Remove suggestion for unnecessary Rust Syntax extension
  .vscode/extensions.json
  .vscode/settings.json
Labels: Ready to Merge, QA Override

#1583 fix(mobile): adjust icon and label for input space on mobile
  ui/src/components/friends/add.rs
Labels: Failed Automated Test, Waiting for CI

#1579 chore(appium): remove not required artifacts on failed test executions
  .github/workflows/ui-test-automation.yml
Labels: Draft, Don't merge yet

#1589 fix(ChatText): don't try to parse DID if string is too short
  kit/src/components/message/mod.rs
Labels: QA Tested, Ready to Merge

#1571 feat(settings): Impl online status change setting
  common/locales/en-US/main.ftl
  common/src/state/mod.rs
  common/src/warp_runner/manager/commands/multipass_commands.rs
  kit/src/elements/select/mod.rs
  kit/src/elements/select/style.scss
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/components/settings/sub_pages/profile/style.scss
  ui/src/layouts/chats/presentation/chat/group_users.rs
  ui/src/layouts/chats/presentation/chatbar/mod.rs
  ui/src/layouts/chats/presentation/sidebar/search.rs
Labels: Waiting for CI

#1568 chore(Logger): Added primer for log level and state tabs in logger
  README.md
  common/locales/en-US/main.ftl
  common/src/state/mod.rs
  kit/src/components/channel/mod.rs
  kit/src/components/message/style.scss
  kit/src/elements/button/style.scss
  kit/src/elements/input/mod.rs
  kit/src/elements/mod.rs
  kit/src/style.scss
  native_extensions/emoji_selector/src/style.css
  ui/src/components/community/sidebar/mod.rs
  ui/src/components/debug_logger/mod.rs
  ui/src/components/debug_logger/style.scss
  ui/src/components/friends/add.rs
  ui/src/components/friends/nothing_here/mod.rs
  ui/src/components/friends/style.scss
  ui/src/components/settings/sub_pages/audio.rs
  ui/src/extension_browser/extensions.scss
  ui/src/layouts/storage/files_layout/mod.rs
  ui/src/layouts/storage/style.scss
  ui/src/logger/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet, Failed Automated Test

#1600 chore(appium): workaround for automated tests issue with webdriverio
  .github/workflows/ui-test-automation.yml
Labels: QA Tested, Don't merge yet

#1587 refactor(PasteShortcut): Fix paste for Linux OS System with shortcut
  Cargo.lock
  kit/src/elements/textarea/mod.rs
  kit/src/layout/chatbar/mod.rs
  ui/Cargo.toml
  ui/src/components/paste_files_with_shortcut/mod.rs
  ui/src/layouts/chats/mod.rs
  ui/src/layouts/chats/presentation/chatbar/mod.rs
  ui/src/layouts/storage/files_layout/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1602 chore(settings): Keyboard shortcuts settings
  common/locales/en-US/main.ftl
  icons/src/icons/outline/keybind.svg
  icons/src/icons/outline/record-circle.svg
  ui/src/components/settings/sidebar.rs
  ui/src/components/settings/styles.scss
  ui/src/components/settings/sub_pages/keybinds.rs
  ui/src/components/settings/sub_pages/mod.rs
  ui/src/layouts/settings.rs
Labels: Missing dev review, Don't merge yet, Waiting for CI

#1597 feat(friends): Add ability to search friends in friends list
  common/locales/en-US/main.ftl
  ui/src/components/friends/friends_list/mod.rs
Labels: QA Tested, Don't merge yet, Ready to Merge

#1605 fix(mobile): Change position of create group modal in mobile
  ui/src/layouts/chats/presentation/sidebar/mod.rs
  ui/src/layouts/chats/style.scss
Labels: Waiting for CI

#1590 fix(mobile): Rework topbar mobile layout
  common/locales/en-US/main.ftl
  kit/src/style.scss
  ui/src/layouts/chats/presentation/chat/controls.rs
  ui/src/layouts/chats/presentation/chat/edit_group.rs
  ui/src/layouts/chats/presentation/chat/pinned_messages/mod.rs
  ui/src/layouts/chats/presentation/chat/pinned_messages/style.scss
  ui/src/layouts/chats/presentation/style.scss
  ui/src/layouts/chats/style.scss
  ui/src/style.scss
Labels: Waiting for CI

#1614 chore(actions): update to latest
  .github/workflows/avoid-typos.yml
  .github/workflows/build-dmg-universal.yml
  .github/workflows/ui-test-automation.yml
Labels: Ready to Merge

#1611 fix(TouchPad): Fix context menu with touch pad when there is dialog
  kit/src/components/embeds/file_embed/mod.rs
  kit/src/elements/file/mod.rs
Labels: QA Tested, Don't merge yet

#1593 update(FontSize): Change font size with shortcut
  kit/src/components/slide_selector/mod.rs
  ui/src/components/mod.rs
  ui/src/components/settings/sub_pages/general.rs
  ui/src/components/shortcuts/change_font_size_shortcut/mod.rs
  ui/src/components/shortcuts/mod.rs
  ui/src/components/shortcuts/paste_file_shortcut/mod.rs
  ui/src/layouts/chats/presentation/chatbar/mod.rs
  ui/src/lib.rs
  ui/src/utils/get_font_sizes.rs
  ui/src/utils/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1613 fix(bug): QuickProfile renders offscreen
  kit/src/components/context_menu/style.scss
  ui/src/layouts/chats/presentation/style.scss
Labels: QA Tested, Ready to Merge

#1629 fix(Files): Fix showing message on toast notification when file has no thumbnail
  common/locales/en-US/main.ftl
Labels: QA Tested, Missing dev review, Don't merge yet, Failed Automated Test

#1630 update(aria): simplify aria labels for chat messages
  kit/src/components/message/mod.rs
Labels: QA Tested, Ready to Merge

#1561 feat(audio): Add Audio tests
  common/locales/en-US/main.ftl
  common/src/warp_runner/manager/commands/blink_commands.rs
  ui/src/components/settings/styles.scss
  ui/src/components/settings/sub_pages/audio.rs
Labels: QA Tested, Don't merge yet, Failed Automated Test

#1609 chore(cargo): Update dependency
  Cargo.lock
  Cargo.toml
  common/src/warp_runner/ui_adapter/message_event.rs
Labels: QA Tested, Ready to Merge, Failed Automated Test

#1637 chore(license): Relicense to MIT
  LICENSE
  LICENSE.md
Labels: Missing dev review, Don't merge yet

#1631 fix(format_text): escape special characters
  kit/src/components/message/mod.rs
Labels: Don't merge yet, Failed Automated Test

#1634 fix(groups): Group UI update
  ui/src/layouts/chats/presentation/chat/controls.rs
  ui/src/layouts/chats/presentation/chat/group_users.rs
  ui/src/layouts/chats/presentation/chat/topbar.rs
  ui/src/layouts/chats/style.scss
Labels: QA Tested, Ready to Merge

#1618 feat(logger): use env_logger and RUST_LOG for better control of logging
  .gitignore
  Cargo.lock
  common/src/lib.rs
  ui/Cargo.toml
  ui/src/bootstrap.rs
  ui/src/lib.rs
  ui/src/logger/mod.rs
Labels: Waiting for CI

#1644 chore(ci): update to latest
  .github/workflows/add-label.yml
  .github/workflows/avoid-typos.yml
  .github/workflows/lint-PR-title.yml
  .github/workflows/remove-labels.yml
Labels: Waiting for CI

#1635 fix(ui): fix inconsistent app style between login and app
  ui/src/layouts/unlock.rs
  ui/src/lib.rs
Labels: Waiting for CI

#1636 fix(bug): Unable to drag window in mobile
  ui/src/components/topbar/release_info/style.scss
Labels: Ready for testing, Don't merge yet

#1643 chore(mobile): Coming soon button style
  ui/src/layouts/chats/presentation/style.scss
Labels: Don't merge yet, Waiting for CI

#1645 chore(cargo): Update dependency
  Cargo.lock
  Cargo.toml
  common/src/lib.rs
  common/src/warp_runner/mod.rs
Labels: QA Tested, Ready to Merge

#1649 update(Welcome): Improve message in welcome page
  common/locales/en-US/main.ftl
  ui/src/layouts/chats/presentation/welcome/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1651 fix(settings): Improve License page in settings
  icons/LICENSE-APACHE
  icons/src/icons/LICENSE-MIT
  ui/src/components/settings/sub_pages/licenses.rs
Labels: QA Tested, Don't merge yet, Failed Automated Test

#1648 fix(IdentityStatus): Fix identity status update when user update any data in profile page
  common/src/warp_runner/manager/commands/multipass_commands.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1601 feat(calling): Call user indicators
  Cargo.lock
  ui/src/components/media/calling.rs
  ui/src/components/media/style.scss
Labels: QA Tested, Don't merge yet, Ready to Merge

#1642 chore(appium): move testing reports into a different repo
  .github/workflows/ui-test-automation.yml
Labels: QA Tested, Don't merge yet

#1653 chore(assets): add icons
  icons/src/icons/outline/document-media.svg
  icons/src/icons/outline/headphones-slash.svg
  icons/src/icons/outline/headphones.svg
Labels: Waiting for CI

#1654 improvement(call): Update deafen icon in call ui
  ui/src/components/media/calling.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1656 feat(about): made in
  common/locales/en-US/main.ftl
  ui/src/components/settings/styles.scss
  ui/src/components/settings/sub_pages/about.rs
Labels: Changes requested, Missing dev review, Don't merge yet, Failed Automated Test

#1659 chore(misc): Change default discovery
  common/src/lib.rs
  common/src/warp_runner/mod.rs
Labels: Missing dev review, Don't merge yet, Ready to Merge, QA Override, Waiting for CI

#1660 fix(vscode): Remove debug arg from vscode launch
  .vscode/launch.json
Labels: Ready to Merge, QA Override
