Repository Satellite-im/Uplink, pull requests merged in 2023-06, with the labels that each got.

#860 fix(emoji): Fix scrollbar layout change in emoji selector
  native_extensions/emoji_selector/src/style.css
Labels: QA Tested, Missing dev review, Don't merge yet

#864 chore(typo): fix typo
  kit/src/elements/label/mod.rs
  ui/src/layouts/unlock.rs
Labels: QA Tested, Ready to Merge, QA Override

#862 fix(group): Fix favorite ignoring group name
  ui/src/components/chat/sidebar.rs
Labels: QA Tested, Ready to Merge

#845 fix(notification): new message notification sound after turning off all notifications
  common/src/state/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet, Failed Automated Test

#865 chore(locales): add pt locale
  common/locales/pt-PT/main.ftl
Labels: QA Tested, Missing dev review, Don't merge yet

#786 feat(notification): Clickable notifications
  Cargo.lock
  common/Cargo.toml
  common/locales/en-US/main.ftl
  common/src/notifications.rs
  common/src/state/mod.rs
  ui/src/components/settings/sub_pages/developer.rs
  ui/src/layouts/friends.rs
  ui/src/main.rs
Labels: QA Tested, Missing dev review, Don't merge yet, missing fixing conflict

#867 add(aria): add aria labels for ui elements
  kit/src/components/message/mod.rs
  kit/src/components/slide_selector/mod.rs
  kit/src/components/user/mod.rs
  kit/src/components/user_image/mod.rs
  kit/src/components/user_image_group/mod.rs
  native_extensions/emoji_selector/src/lib.rs
  ui/src/components/chat/compose/messages.rs
  ui/src/components/chat/create_group.rs
  ui/src/components/chat/edit_group.rs
  ui/src/components/chat/group_users.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/chat/welcome/mod.rs
  ui/src/components/debug_logger/mod.rs
  ui/src/components/friends/add.rs
  ui/src/components/friends/blocked/mod.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/friends/incoming_requests/mod.rs
  ui/src/components/friends/outgoing_requests/mod.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/extension_browser/mod.rs
  ui/src/layouts/storage/mod.rs
Labels: QA Tested, Ready to Merge

#866 feat(blink): add blink to uplink
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  common/locales/en-US/main.ftl
  common/src/state/action.rs
  common/src/state/call.rs
  common/src/state/mod.rs
  common/src/state/ui.rs
  common/src/warp_runner/manager/commands/blink_commands.rs
  common/src/warp_runner/manager/commands/mod.rs
  common/src/warp_runner/manager/events.rs
  common/src/warp_runner/manager/mod.rs
  common/src/warp_runner/mod.rs
  kit/src/layout/sidebar/mod.rs
  ui/src/components/chat/compose/messages.rs
  ui/src/components/chat/compose/mod.rs
  ui/src/components/chat/group_users.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/media/player.rs
  ui/src/components/media/popout_player.rs
  ui/src/components/media/remote_control.rs
  ui/src/components/settings/sidebar.rs
  ui/src/components/settings/sub_pages/about.rs
  ui/src/components/settings/sub_pages/files.rs
  ui/src/main.rs
  ui/src/utils/auto_updater.rs
  ui/src/utils/mod.rs
Labels: QA Tested, Don't merge yet, Failed Automated Test

#871 fix(chat): change quickprofile layout
  ui/src/components/chat/compose/messages.rs
  ui/src/components/chat/show_context.js
  ui/src/components/chat/style.scss
Labels: QA Tested, Ready to Merge

#886 fix(emoji): Fix wrong emoji icon
  native_extensions/emoji_selector/src/lib.rs
Labels: QA Tested, Ready to Merge

#889 chore(groups): Updated topbar for groups
  common/locales/en-US/main.ftl
  common/src/notifications.rs
  ui/src/components/chat/compose/mod.rs
  ui/src/components/chat/group_users.rs
  ui/src/layouts/storage/functions.rs
Labels: Don't merge yet

#891 fix(chat): Chat whitespace fix
  kit/src/components/message/mod.rs
  ui/src/components/chat/compose/chatbar.rs
Labels: QA Tested, Ready to Merge, Waiting for CI

#870 fix(files): Fix path decoding issue on linux for file dragging
  ui/src/layouts/storage/functions.rs
Labels: Changes requested, Don't merge yet, Failed Automated Test

#904 fix(textColor): Fix text color in file name on chats
  kit/src/components/embeds/file_embed/mod.rs
Labels: Failed Automated Test

#900 fix(ui): Hide overflow completly from logger
  ui/src/components/debug_logger/style.scss
Labels: QA Tested, Ready to Merge

#905 update(Group): Fix group view with a lot of participants
  ui/src/components/chat/group_users.rs
  ui/src/components/chat/style.scss
Labels: QA Tested, Ready to Merge

#907 chore(settings): remove themes option in settings
  ui/src/components/settings/sub_pages/general.rs
Labels: QA Tested, Don't merge yet, Waiting for CI

#906 update(ReplyButton): Fix reply button size
  kit/src/elements/button/style.scss
Labels: Missing dev review, Don't merge yet

#912 fix(logger): Hide logger when loading app
  ui/src/main.rs
Labels: Ready for testing, Don't merge yet

#914 feat(logger): Add min height for debug logger
  ui/src/components/debug_logger/script.js
Labels: QA Tested, Ready to Merge

#916 fix(unreads): fix count of unread messages for simple cases
  common/src/state/chats.rs
  common/src/state/mod.rs
Labels: QA Tested, Don't merge yet, Waiting for CI

#909 fix(input): Fix input validation reset on submission even if value isn't cleared
  kit/src/elements/input/mod.rs
Labels: QA Tested, Ready to Merge

#917 chore(appium): remove cargo update from appium build job
  .github/workflows/ui-test-automation.yml
Labels: Missing dev review, Don't merge yet

#908 feat(Unlock): Adds a context menu to the unlock page with ability to reset
  common/locales/en-US/main.ftl
  ui/src/layouts/storage/mod.rs
  ui/src/layouts/style.scss
  ui/src/layouts/unlock.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#918 fix(settings): Change update message in the about section
  common/locales/en-US/main.ftl
  ui/src/components/settings/sub_pages/about.rs
Labels: QA Tested, Ready to Merge

#859 update(window_size): Fix window size if it is maximized on login
  common/src/state/ui.rs
  kit/src/components/topbar_controls/mod.rs
  ui/src/layouts/loading.rs
  ui/src/layouts/unlock.rs
  ui/src/main.rs
Labels: QA Tested, Ready to Merge, Failed Automated Test

#913 fix(group): Fix clear button in group creation not resetting
  kit/src/elements/input/mod.rs
  ui/src/components/chat/create_group.rs
  ui/src/components/chat/edit_group.rs
Labels: QA Tested, Ready to Merge

#930 chore(themeselector): add back theme selector
  ui/src/components/settings/sub_pages/general.rs
Labels: Missing dev review, Don't merge yet

#931 chore(pictures): Implement calls to clear pictures and banners
  common/src/warp_runner/manager/commands/multipass_commands.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
Labels: QA Tested, Ready to Merge

#938 fix(image): Fix the microphone-slash svg
  icons/src/icons/outline/microphone-slash.svg
Labels: Ready to Merge, QA Override, Failed Automated Test

#939 add(Icon): Add microphone-wave svg
  icons/src/icons/outline/microphone-wave.svg
Labels: Missing dev review, Don't merge yet

#934 fix(settings): Remove reset button when banner or profile picture is empty
  ui/src/components/settings/sub_pages/profile/mod.rs
Labels: QA Tested, Ready to Merge

#929 fix(login): Login pin fix
  common/locales/en-US/main.ftl
  ui/src/layouts/unlock.rs
  ui/src/main.rs
Labels: checking stuff

#942 fix(cargo): remove warning from cargo build
  ui/Cargo.toml
Labels: Ready to Merge, QA Override

#932 chore(cargo): Update dependency
  .github/workflows/build-dmg-universal.yml
  .github/workflows/build-release-linux.yml
  .github/workflows/build-release-windows.yml
  .github/workflows/cargo.yml
  .github/workflows/ui-test-automation.yml
  Cargo.lock
  Cargo.toml
  common/src/lib.rs
  common/src/state/identity.rs
  common/src/warp_runner/mod.rs
  ui/build.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
Labels: QA Tested, Don't merge yet, checking stuff

#940 feat(Settings): Add more audio settings & volume slider.
  common/locales/en-US/main.ftl
  icons/src/lib.rs
  kit/src/elements/mod.rs
  kit/src/elements/range/mod.rs
  kit/src/elements/range/style.scss
  kit/src/style.scss
  ui/extra/themes/example.scss
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/friends/style.scss
  ui/src/components/settings/sub_pages/audio.rs
Labels: Missing dev review, Don't merge yet, Failed Automated Test, Waiting for CI

#945 fix(common): Use get to prevent overflow
  common/src/state/identity.rs
Labels: QA Tested, Missing dev review, Don't merge yet, Failed Automated Test

#947 fix(theme): Light theme fix
  ui/extra/themes/light.scss
Labels: QA Tested, Ready to Merge

#948 chore(cargo): Update dependency
  Cargo.lock
  Cargo.toml
Labels: QA Override
