Repository Satellite-im/Uplink, pull requests merged in 2023-11, with the labels that each got.

#1421 fix(settings): fix audio
  common/locales/en-US/main.ftl
  common/src/state/action.rs
  common/src/state/configuration.rs
  common/src/warp_runner/manager/commands/blink_commands.rs
  kit/src/elements/range/mod.rs
  ui/src/components/settings/sub_pages/audio.rs
Labels: QA Tested, Ready to Merge, Failed Automated Test

#1435 fix(chatbar): don't close emoji picker on scroll
  ui/src/layouts/chats/data/chatbar/mod.rs
  ui/src/layouts/chats/data/chatbar/typing_indicator.rs
  ui/src/layouts/chats/data/chatbar/typing_info.rs
  ui/src/layouts/chats/data/mod.rs
  ui/src/layouts/chats/presentation/chat/mod.rs
  ui/src/layouts/chats/presentation/chatbar/coroutines.rs
  ui/src/layouts/chats/presentation/chatbar/mod.rs
  ui/src/layouts/chats/presentation/messages/coroutines.rs
Labels: QA Tested, Ready to Merge, Failed Automated Test

#1442 fix(ui): Move char counter down a bit
  kit/src/elements/textarea/style.scss
Labels: QA Tested, Ready to Merge

#1326 fix(log): Dont load debug file
  common/src/state/mod.rs
  ui/src/logger/mod.rs
Labels: Don't merge yet, Failed Automated Test, Waiting for CI

#1440 feat(calling): bump warp and wire up silence button
  Cargo.lock
  Cargo.toml
  common/locales/en-US/main.ftl
  common/src/state/call.rs
  common/src/state/mod.rs
  common/src/warp_runner/manager/commands/blink_commands.rs
  ui/src/components/media/calling.rs
Labels: QA Tested, Ready to Merge

#1444 chore(coderabbit): add custom file
  .coderabbit.yaml
Labels: Failed Automated Test, Waiting for CI

#1441 fix(ui): Fix modal light theme background
  kit/src/layout/modal/style.scss
  kit/src/style.scss
  ui/extra/themes/light.scss
Labels: QA Tested, Ready to Merge, Failed Automated Test

#1446 chore(bot): ditch bot poems
  .coderabbit.yaml
Labels: Missing dev review, Don't merge yet

#1447 fix(logs): Remove a logging message that was left in
  kit/src/elements/textarea/update_char_counter.js
Labels: QA Tested, Missing dev review, Don't merge yet

#1449 fix(misc): return error via oneshot to prevent panicking
  common/src/warp_runner/mod.rs
Labels: Don't merge yet, Ready to Merge, QA Override

#1451 fix(ui): Add some margin to modals
  kit/src/layout/modal/style.scss
Labels: Missing dev review, Don't merge yet, Waiting for CI

#1450 fix(ui): Change button tooltip layout
  kit/src/elements/tooltip/style.scss
  ui/src/layouts/chats/style.scss
  ui/src/layouts/storage/files_layout/mod.rs
Labels: QA Tested, Ready to Merge

#1455 chore(docs): fix 404 in docs
  docs/new-dev.md
Labels: Missing dev review, Don't merge yet, Waiting for CI

#1459 chore(appium): remove build ubuntu step on ui automated tests
  .github/workflows/ui-test-automation.yml
Labels: Missing dev review, Don't merge yet

#1458 chore(docs): fix 404
  docs/architecture.md
Labels: QA Tested, Ready to Merge

#1456 chore(docs): updating test docs
  ui/docs/testing/uplink-checklist.md
Labels: Draft, Don't merge yet

#1457 chore(cargo): Update dependency
  .github/workflows/build-dmg-universal.yml
  .github/workflows/build-release-linux.yml
  .github/workflows/build-release-windows.yml
  .github/workflows/cargo.yml
  .github/workflows/ui-test-automation.yml
  Cargo.lock
  Cargo.toml
  common/src/lib.rs
  common/src/warp_runner/manager/commands/raygun_commands.rs
  common/src/warp_runner/manager/events.rs
  common/src/warp_runner/mod.rs
  ui/build.rs
Labels: QA Tested, Ready to Merge

#1477 chore(docs): update test docs
  ui/docs/testing/uplink-checklist.md
Labels: Waiting for CI

#1483 chore(recording): add tooltip
  common/locales/en-US/main.ftl
  ui/src/components/media/calling.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1402 chore(chatbar): disabling the chatbar when it's loading instead of displaying different text and not being multi line by default
  common/locales/en-US/main.ftl
  kit/src/elements/textarea/style.scss
  kit/src/layout/chatbar/mod.rs
  kit/src/style.scss
Labels: QA Tested, Ready to Merge

#1454 feat(favorites): Dont show typing indicator in slimbar if chat in sidebar
  ui/src/layouts/slimbar.rs
Labels: QA Tested, Ready to Merge

#1427 fix(quickprofile): Disable onblur for msg and hide profile on enter
  common/src/state/mod.rs
  ui/src/layouts/chats/presentation/quick_profile/mod.rs
Labels: QA Tested, Ready to Merge

#1471 refactor(mobile): Prepare uplink for mobile
  ui/src/lib.rs
  ui/src/main.rs
Labels: QA Tested, Ready to Merge

#1453 feat(groups): Quickprofile chat friend request
  common/locales/en-US/main.ftl
  ui/src/layouts/chats/presentation/chat/group_users.rs
  ui/src/layouts/chats/presentation/chat/mod.rs
  ui/src/layouts/chats/presentation/messages/coroutines.rs
  ui/src/layouts/chats/presentation/messages/effects.rs
  ui/src/layouts/chats/presentation/messages/mod.rs
  ui/src/layouts/chats/presentation/quick_profile/mod.rs
  ui/src/layouts/chats/presentation/style.scss
  ui/src/layouts/chats/scripts/show_context.js
Labels: QA Tested, Missing dev review, Don't merge yet

#1472 feat(friends): Add feature to share friends
  common/locales/en-US/main.ftl
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/friends/style.scss
  ui/src/layouts/chats/presentation/quick_profile/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1492 feat(chat): Add a notification if whether download is success or failed
  common/locales/en-US/main.ftl
  ui/src/layouts/chats/presentation/messages/coroutines.rs
  ui/src/layouts/storage/files_layout/mod.rs
  ui/src/layouts/storage/functions.rs
  ui/src/layouts/storage/send_files_layout/mod.rs
Labels: Missing dev review, Don't merge yet, Waiting for CI

#1484 fix(mobile): mobile layout and slimbar
  ui/src/components/friends/style.scss
  ui/src/components/settings/sub_pages/profile/style.scss
  ui/src/layouts/friends.rs
  ui/src/layouts/settings.rs
  ui/src/layouts/storage/files_layout/mod.rs
  ui/src/layouts/storage/style.scss
Labels: Waiting for CI

#1480 chore(Everywhere): Various UI Tweaks, adds secondary-darker var
  common/locales/en-US/main.ftl
  kit/src/components/context_menu/style.scss
  kit/src/components/embeds/file_embed/style.scss
  kit/src/components/embeds/identity_embed/mod.rs
  kit/src/components/message/mod.rs
  kit/src/components/message/style.scss
  kit/src/components/message_reply/style.scss
  kit/src/layout/chatbar/style.scss
  kit/src/layout/sidebar/style.scss
  kit/src/style.scss
  ui/src/layouts/chats/presentation/quick_profile/mod.rs
  ui/src/layouts/chats/style.scss
Labels: QA Tested, Don't merge yet

#1490 feat(Messages): Adds copy text option to message context menu
  common/locales/en-US/main.ftl
  ui/src/components/friends/add.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/extension_browser/mod.rs
  ui/src/layouts/chats/presentation/messages/mod.rs
Labels: Ready to Merge

#1497 chore(fix): fix test
  kit/src/components/message/mod.rs
Labels: QA Tested, Ready to Merge

#1502 fix(chat): Fix long msg in codeblocks not breaking
  kit/src/elements/textarea/style.scss
  ui/extra/assets/styles/prism-one-dark.css
Labels: QA Tested, Ready to Merge

#1488 refactor(EmojiSuggestion): Close emoji suggestion modal with X button or typing ESCAPE keycode
  kit/src/elements/textarea/mod.rs
  kit/src/layout/chatbar/mod.rs
Labels: QA Tested, Don't merge yet, Ready to Merge

#1498 feat(download): Use temp file for download
  ui/src/layouts/chats/presentation/messages/coroutines.rs
  ui/src/layouts/storage/functions.rs
  ui/src/utils/download.rs
  ui/src/utils/mod.rs
Labels: QA Tested, Ready to Merge

#1499 task(groups): Change calling to only include joined participants
  ui/src/components/media/calling.rs
Labels: Failed Automated Test, Waiting for CI

#1518 update(main): add prod mode attr to remove terminal from windows build
  ui/src/main.rs
Labels: QA Tested, Missing dev review, Don't merge yet, Failed Automated Test

#1491 update(React): Let react disabled if user disable emoji extension
  common/src/state/ui.rs
  ui/src/components/emoji_group/mod.rs
  ui/src/extension_browser/mod.rs
  ui/src/layouts/chats/presentation/messages/mod.rs
Labels: Waiting for CI

#1513 fix(chat): Fix scroll btn for large msg
  ui/src/layouts/chats/scripts/observer_script.js
Labels: QA Tested, Ready to Merge

#1508 fix(chat): Fix group typing indicator
  kit/src/components/user_image/style.scss
  kit/src/components/user_image_group/mod.rs
  kit/src/components/user_image_group/styles.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#1525 chore(bot): bot was fired
  .coderabbit.yaml
Labels: Missing dev review, Don't merge yet

#1510 fix(ImageFromPinned): Fixed modal position when user opens from pinned messages
  kit/src/layout/modal/mod.rs
  kit/src/layout/modal/style.scss
  ui/src/layouts/chats/presentation/chat/controls.rs
Labels: QA Tested, Don't merge yet

#1512 update(Sidebar): Don't show markdown in sidebar
  ui/src/layouts/chats/presentation/sidebar/mod.rs
Labels: QA Tested, Failed Automated Test

#1526 chore(locales): remove locales
  common/locales/en-US/main.ftl
Labels: Missing dev review, Don't merge yet

#1527 chore(locales): remove locales
  common/locales/de/main.ftl
  common/locales/es-MX/main.ftl
  common/locales/pt-PT/main.ftl
Labels: QA Tested, Missing dev review, Don't merge yet

#1448 fix(ui): Fix large unread number not centered
  ui/src/lib.rs
  ui/src/style.scss
Labels: Don't merge yet, Failed Automated Test

#1531 feat(Friending): Copy username#shortid
  common/locales/en-US/main.ftl
  ui/src/components/friends/add.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
Labels: QA Tested, Ready to Merge

#1529 fix(NoFriends): Fixes mascot becoming very wide
  ui/src/components/friends/style.scss
Labels: QA Tested, Ready to Merge

#1524 fix(ui): Fix quickprofile element below chatbar
  ui/src/layouts/chats/presentation/style.scss
Labels: QA Tested, Ready to Merge

#1523 fix(FileName): fix name for images from storage
  kit/src/components/embeds/file_embed/mod.rs
  ui/src/components/files/attachments.rs
Labels: QA Tested, Ready to Merge

#1521 update(EmojiPicker): Create type bar for emoji picker
  native_extensions/emoji_selector/Cargo.toml
  native_extensions/emoji_selector/src/lib.rs
Labels: QA Tested, Ready to Merge

#1538 fix(DragEvent): Fix drag event on Linux
  Cargo.lock
  ui/src/components/files/upload_progress_bar/mod.rs
  ui/src/utils/get_drag_event.rs
  ui/src/webview_config.rs
Labels: Ready for testing, Don't merge yet

#1539 update(Add): Update toast when past own did
  ui/src/components/friends/add.rs
Labels: Failed Automated Test

#1540 update(ShareDID): Let share did option as not danger
  kit/src/components/context_menu/mod.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/layouts/chats/presentation/quick_profile/mod.rs
Labels: linter failing

#1522 fix(call): Improv user ui in call
  kit/src/components/context_menu/context.js
  kit/src/components/context_menu/mod.rs
  ui/src/components/media/calling.rs
  ui/src/components/media/resize_handler.js
  ui/src/components/media/style.scss
Labels: Waiting for CI

#1547 fix(images): Fix img thumbnails converted to jpeg always
  common/src/warp_runner/mod.rs
Labels: Don't merge yet, Failed Automated Test, Waiting for CI

#1548 update(SuggestedEmoji): Improve Suggested Emoji UI
  common/locales/en-US/main.ftl
  kit/src/layout/chatbar/mod.rs
  ui/src/layouts/chats/style.scss
Labels: Don't merge yet, Failed Automated Test, Waiting for CI

#1546 fix(ui): Change nav bar to vertical buttons
  ui/src/extension_browser/extensions.scss
Labels: Changes requested, Don't merge yet, Failed Automated Test

#1533 chore(cargo): Update dependency
  Cargo.lock
  Cargo.toml
  common/src/lib.rs
  common/src/state/call.rs
  common/src/state/mod.rs
  common/src/warp_runner/mod.rs
Labels: QA Tested, Don't merge yet, Failed Automated Test

#1550 fix(bugs): mobile bug fixes
  kit/src/elements/textarea/script.js
  kit/src/layout/topbar/style.scss
  ui/src/layouts/chats/mod.rs
  ui/src/layouts/chats/presentation/welcome/mod.rs
  ui/src/layouts/chats/presentation/welcome/style.scss
Labels: QA Tested, Ready to Merge
