Repository Satellite-im/Uplink, pull requests merged in 2023-10, with the labels that each got.

#1264 fix(chat): Remove padding for image preview modal
  kit/src/layout/modal/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#1267 fix(files): fix file modal padding
  kit/src/layout/modal/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#1249 fix(placeholder): change placeholder text based on windowsize
  ui/src/layouts/chats/presentation/chatbar.rs
Labels: Waiting for CI

#1278 update(DeveloperMode): Hide user volume if experimental flag is off
  ui/src/layouts/chats/presentation/quick_profile/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet, Failed Automated Test

#1277 update(Storage): Disable send files button if no files are selected
  ui/src/layouts/storage/send_files_layout/send_files_components.rs
Labels: QA Tested, Missing dev review, Don't merge yet, Failed Automated Test

#1242 chore(friends): add placeholder, hide titles for no requests
  common/locales/en-US/main.ftl
  ui/src/components/friends/blocked/mod.rs
  ui/src/components/friends/incoming_requests/mod.rs
  ui/src/components/friends/mod.rs
  ui/src/components/friends/nothing_here/mod.rs
  ui/src/components/friends/outgoing_requests/mod.rs
  ui/src/components/friends/style.scss
  ui/src/layouts/friends.rs
Labels: Waiting for CI

#1283 refactor(bot): update ci
  .github/workflows/lint-PR-title.yml
Labels: Missing dev review, Don't merge yet, Waiting for CI

#1282 fix(Storage): Adjust remove attachment button position
  ui/src/layouts/chats/style.scss
Labels: Missing dev review, Don't merge yet

#1275 feat(Storage): Fix close button on Send Files Layout
  kit/src/elements/file/mod.rs
  kit/src/layout/modal/mod.rs
  ui/src/layouts/storage/send_files_layout/modal.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1281 update(Storage): Adjust padding of select chats
  ui/src/layouts/storage/send_files_layout/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1284 chore(keys): remove not needed keys
  common/locales/es-MX/main.ftl
  common/locales/pt-BR/main.ftl
  common/locales/pt-PT/main.ftl
Labels: QA Tested, Missing dev review, Don't merge yet

#1292 chore(appium): use macos 13 on tests workflow
  .github/workflows/ui-test-automation.yml
Labels: Missing dev review

#1291 fix(chatbar): Fix typing indicator moving chatbar
  kit/src/components/message_typing/style.scss
  kit/src/layout/chatbar/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#1250 fix(friends): Fix did hash for outgoing/incoming being reversed
  common/src/warp_runner/ui_adapter/mod.rs
  ui/src/components/friends/blocked/mod.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/friends/incoming_requests/mod.rs
  ui/src/components/friends/outgoing_requests/mod.rs
Labels: Waiting for CI

#1288 chore(cargo): Update dependency
  Cargo.lock
  Cargo.toml
  common/src/state/mod.rs
  common/src/warp_runner/ui_adapter/mod.rs
Labels: QA Tested, Ready to Merge

#1304 fix(files): Disable share button if no chat selected
  ui/src/layouts/storage/send_files_layout/send_files_components.rs
Labels: Ready to Merge, Waiting for CI

#1301 fix(groups): Remove status indicator for group images
  kit/src/components/user_image_group/mod.rs
Labels: Ready to Merge, Waiting for CI

#1253 feat(CropImageTool): Crop profile picture tool
  common/locales/en-US/main.ftl
  kit/src/elements/button/style.scss
  kit/src/elements/mod.rs
  kit/src/layout/modal/mod.rs
  ui/src/components/crop_image_tool/adjust_crop_circle_size.js
  ui/src/components/crop_image_tool/get_image_dimensions.js
  ui/src/components/crop_image_tool/mod.rs
  ui/src/components/crop_image_tool/save_cropped_image.js
  ui/src/components/crop_image_tool/style.scss
  ui/src/components/mod.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/layouts/storage/files_layout/mod.rs
Labels: Waiting for CI

#1308 add(aria): labels for call image modals and emoji suggestions
  kit/src/layout/chatbar/mod.rs
  kit/src/layout/modal/mod.rs
  ui/src/components/files/file_preview.rs
  ui/src/components/media/calling.rs
  ui/src/layouts/storage/shared_component.rs
Labels: QA Tested, Missing dev review, Don't merge yet, Ready to Merge

#1309 add(aria): aria labels for crop tool and range elements
  kit/src/elements/range/mod.rs
  ui/src/components/crop_image_tool/mod.rs
  ui/src/components/settings/sub_pages/audio.rs
  ui/src/layouts/chats/presentation/quick_profile/mod.rs
Labels: Missing dev review, Don't merge yet

#1289 update(CropImage): Add mask on crop tool
  kit/src/elements/button/style.scss
  kit/src/elements/mod.rs
  kit/src/elements/range/mod.rs
  ui/src/components/crop_image_tool/adjust_crop_circle_size.js
  ui/src/components/crop_image_tool/mod.rs
  ui/src/components/crop_image_tool/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#1313 fix(quickprofile): Only show user volume in vc
  common/locales/en-US/main.ftl
  ui/src/layouts/chats/presentation/quick_profile/mod.rs
Labels: Failed Automated Test, Waiting for CI

#1307 chore(messaging): fetch messages on demand
  Cargo.lock
  common/src/lib.rs
  common/src/state/chats.rs
  common/src/state/mod.rs
  common/src/warp_runner/data/mod.rs
  common/src/warp_runner/manager/commands/raygun_commands.rs
  common/src/warp_runner/mod.rs
  common/src/warp_runner/ui_adapter/message_event.rs
  common/src/warp_runner/ui_adapter/mod.rs
  common/src/warp_runner/ui_adapter/multipass_event.rs
  common/src/warp_runner/ui_adapter/raygun_event.rs
  icons/src/lib.rs
  kit/src/components/indicator/mod.rs
  ui/Cargo.toml
  ui/src/layouts/chats/README.md
  ui/src/layouts/chats/data/chat_data/active_chat/messages.rs
  ui/src/layouts/chats/data/chat_data/active_chat/metadata.rs
  ui/src/layouts/chats/data/chat_data/active_chat/mod.rs
  ui/src/layouts/chats/data/chat_data/active_chat/partial_message.rs
  ui/src/layouts/chats/data/chat_data/chat_behavior/mod.rs
  ui/src/layouts/chats/data/chat_data/chat_behavior/scroll_behavior.rs
  ui/src/layouts/chats/data/chat_data/chat_behavior/scroll_to.rs
  ui/src/layouts/chats/data/chat_data/chat_behavior/view_init.rs
  ui/src/layouts/chats/data/chat_data/mod.rs
  ui/src/layouts/chats/data/chat_props.rs
  ui/src/layouts/chats/data/js_msg.rs
  ui/src/layouts/chats/data/misc.rs
  ui/src/layouts/chats/data/mod.rs
  ui/src/layouts/chats/data/msg_group.rs
  ui/src/layouts/chats/data/scroll_btn.rs
  ui/src/layouts/chats/mod.rs
  ui/src/layouts/chats/presentation/chat/controls.rs
  ui/src/layouts/chats/presentation/chat/coroutines.rs
  ui/src/layouts/chats/presentation/chat/mod.rs
  ui/src/layouts/chats/presentation/chat/pinned_messages/mod.rs
  ui/src/layouts/chats/presentation/chat/topbar.rs
  ui/src/layouts/chats/presentation/chatbar.rs
  ui/src/layouts/chats/presentation/messages/coroutines.rs
  ui/src/layouts/chats/presentation/messages/effects.rs
  ui/src/layouts/chats/presentation/messages/mod.rs
  ui/src/layouts/chats/scripts/mod.rs
  ui/src/layouts/chats/scripts/observer_script.js
  ui/src/layouts/chats/scripts/scroll_to_bottom.js
  ui/src/layouts/chats/scripts/scroll_to_top.js
  ui/src/layouts/chats/scripts/setup_context_parent.js
  ui/src/layouts/chats/scripts/show_context.js
  ui/src/main.rs
  ui/src/utils/auto_updater.rs
Labels: QA Tested, Ready to Merge, Failed Automated Test

#1306 update(CropImage): Add possibility to move image on crop tool
  ui/src/components/crop_image_tool/adjust_crop_circle_size.js
  ui/src/components/crop_image_tool/mod.rs
  ui/src/components/crop_image_tool/move_image.js
  ui/src/components/crop_image_tool/save_cropped_image.js
Labels: QA Tested, Ready to Merge, Waiting for CI

#1260 feat(call): Impl calling ringtone
  common/src/sounds.rs
  common/src/sounds/RingTone.ogg
  ui/src/components/media/calling.rs
Labels: QA Tested, Missing dev review, Waiting for CI

#1332 chore(docs): update read me
  README.md
Labels: Missing dev review, Don't merge yet

#1330 update(locales): update spanish mx language file to latest
  common/locales/es-MX/main.ftl
Labels: Waiting for CI

#1331 chore(appium): build ubuntu on tests workflow to ensure app builds
  .github/workflows/ui-test-automation.yml
Labels: Waiting for CI

#1329 fix(chats): replies, favorites, and pins
  common/src/state/mod.rs
  ui/src/layouts/chats/data/chat_data/active_chat/metadata.rs
  ui/src/layouts/chats/data/chat_data/active_chat/mod.rs
  ui/src/layouts/chats/presentation/chat/mod.rs
  ui/src/layouts/chats/presentation/chat/pinned_messages/mod.rs
Labels: QA Tested, Ready to Merge

#1334 feat(developer): Added ability to only show developer settings after clicking version number 10 times.
  Cargo.lock
  common/src/state/action.rs
  common/src/state/mod.rs
  common/src/state/ui.rs
  native_extensions/emoji_selector/Cargo.toml
  native_extensions/emoji_selector/src/style.css
  ui/src/components/settings/sidebar.rs
  ui/src/components/settings/sub_pages/about.rs
Labels: QA Tested, Ready to Merge

#1299 feat(ui): Window size setting
  common/src/state/ui.rs
  ui/src/bootstrap.rs
  ui/src/layouts/unlock.rs
  ui/src/main.rs
Labels: QA Tested, Ready to Merge

#1325 chore(cargo): Update dependency
  Cargo.lock
  Cargo.toml
Labels: Don't merge yet, Question

#1350 fix(chat): Scroll to time ago element
  ui/src/layouts/chats/scripts/scroll_to_bottom.js
Labels: QA Tested, Missing dev review, Don't merge yet, Failed Automated Test

#1356 fix(FileDIalog): Not panic anymore when open File Dialog in debug mode
  Cargo.toml
Labels: QA Tested, Ready to Merge, Failed Automated Test

#1353 fix(css): add css to fix markdown
  kit/src/components/message/style.scss
  kit/src/components/message_reply/style.scss
  kit/src/style.scss
  ui/src/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#1339 fix(chatbar): use typing indicator from State
  ui/src/layouts/chats/data/chat_data/active_chat/mod.rs
  ui/src/layouts/chats/presentation/chatbar.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1354 feat(settings): make the settings page remember where you were
  ui/src/bootstrap.rs
  ui/src/components/settings/sidebar.rs
  ui/src/layouts/chats/presentation/quick_profile/mod.rs
  ui/src/layouts/settings.rs
Labels: QA Tested, Ready to Merge

#1358 fix(crash): fix crash on macos
  .github/workflows/build-release-linux.yml
  .github/workflows/cargo.yml
  .github/workflows/ui-test-automation.yml
  Cargo.lock
  Cargo.toml
  README.md
  ui/Cargo.toml
  ui/src/main.rs
  ui/src/webview_config.rs
  ui/src/window_builder.rs
Labels: Don't merge yet, Failed Automated Test, Waiting for CI

#1352 fix(ui): Restrict context menu to the main component
  kit/src/components/context_menu/context.js
Labels: Waiting for CI

#1362 chore(readme): add contributors
  README.md
Labels: Missing dev review, Don't merge yet

#1363 chore(docs): update docs
  docs/architecture.md
Labels: Missing dev review, Don't merge yet

#1364 chore(docs): add commit guidelines
  docs/commit-message-guidelines.md
  docs/contributing_process.md
Labels: Missing dev review, Don't merge yet

#1361 chore(slimbar): hide slimbar when it doesnt have anything in it
  common/src/state/mod.rs
  ui/src/layouts/chats/mod.rs
  ui/src/layouts/friends.rs
  ui/src/layouts/settings.rs
  ui/src/layouts/storage/files_layout/mod.rs
Labels: Missing dev review, Don't merge yet, Waiting for CI

#1357 feat(markdown): big emoji, ascii emoji, and new settings
  Cargo.lock
  common/locales/en-US/main.ftl
  common/src/state/action.rs
  common/src/state/mod.rs
  common/src/state/ui.rs
  kit/Cargo.toml
  kit/src/components/message/mod.rs
  kit/src/components/message_reply/mod.rs
  kit/src/layout/chatbar/mod.rs
  ui/src/components/settings/sidebar.rs
  ui/src/components/settings/sub_pages/messages.rs
  ui/src/components/settings/sub_pages/mod.rs
  ui/src/layouts/chats/presentation/chat/pinned_messages/mod.rs
  ui/src/layouts/chats/presentation/chatbar.rs
  ui/src/layouts/chats/presentation/messages/mod.rs
  ui/src/layouts/chats/presentation/sidebar/mod.rs
  ui/src/layouts/settings.rs
  ui/src/layouts/storage/send_files_layout/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet, Failed Automated Test

#1366 fix(chat): Markdown strikethrough fix
  Cargo.lock
  kit/Cargo.toml
  kit/src/components/message/mod.rs
  ui/src/style.scss
Labels: QA Tested, Ready to Merge

#1371 fix(windows): update dioxus to fix panic
  Cargo.lock
  Cargo.toml
  kit/src/components/topbar_controls/mod.rs
  ui/src/auth_guard.rs
  ui/src/main.rs
  ui/src/style.scss
Labels: Don't merge yet, Failed Automated Test, Waiting for CI

#1394 chore(chat): Remove conversation limit
  Cargo.lock
  Cargo.toml
Labels: Missing dev review, Don't merge yet, QA Override

#1370 fix(context-menu): fix null on script
  kit/src/components/context_menu/context.js
Labels: QA Tested, Ready to Merge

#1395 fix(chat): Ignore case for matching emoji
  common/src/state/ui.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1317 update(CropImage): Create crop tool for banner image
  ui/src/components/crop_image_tool/circle_format_tool/adjust_crop_circle_size.js
  ui/src/components/crop_image_tool/circle_format_tool/mod.rs
  ui/src/components/crop_image_tool/circle_format_tool/save_cropped_image.js
  ui/src/components/crop_image_tool/mod.rs
  ui/src/components/crop_image_tool/move_image.js
  ui/src/components/crop_image_tool/rectangle_format_tool/adjust_crop_rectangle_size.js
  ui/src/components/crop_image_tool/rectangle_format_tool/mod.rs
  ui/src/components/crop_image_tool/rectangle_format_tool/save_cropped_image.js
  ui/src/components/crop_image_tool/style.scss
  ui/src/components/settings/sub_pages/profile/mod.rs
Labels: QA Tested, Ready to Merge, Failed Automated Test

#1415 chore(release): 0.1.7 release
  Cargo.lock
  Cargo.toml
  ui/extra/macos/Uplink.app/Contents/Info.plist
Labels: Missing dev review, Don't merge yet

#1355 fix(DuplicatedImage): Fix duplicate images pasted on chats
  ui/src/components/files/attachments.rs
  ui/src/components/paste_files_with_shortcut/mod.rs
  ui/src/utils/clipboard/clipboard_data.rs
Labels: QA Tested, Ready to Merge

#1369 chore(cargo): Update Dependency
  Cargo.lock
  Cargo.toml
  common/src/state/chats.rs
  common/src/state/mod.rs
  common/src/state/pending_message.rs
  common/src/testing/mock.rs
  common/src/warp_runner/manager/commands/mod.rs
  common/src/warp_runner/manager/commands/multipass_commands.rs
  common/src/warp_runner/mod.rs
  common/src/warp_runner/ui_adapter/mod.rs
  ui/src/components/crop_image_tool/circle_format_tool/mod.rs
  ui/src/components/crop_image_tool/mod.rs
  ui/src/components/crop_image_tool/rectangle_format_tool/mod.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/layouts/chats/presentation/chat/pinned_messages/mod.rs
  ui/src/layouts/chats/presentation/chatbar.rs
  ui/src/layouts/chats/presentation/messages/mod.rs
  ui/src/layouts/chats/presentation/sidebar/mod.rs
  ui/src/layouts/storage/files_layout/mod.rs
  ui/src/layouts/storage/send_files_layout/mod.rs
  ui/src/utils/clipboard/clipboard_data.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1425 chore(locales): update string
  common/locales/en-US/main.ftl
Labels: Ready for testing, Don't merge yet

#1417 fix(ui): Change checkbox border color so be more visible
  kit/src/elements/checkbox/style.scss
Labels: Waiting for CI

#1398 fix(group): Hide scroll for group list if not needed
  ui/src/layouts/chats/style.scss
Labels: Waiting for CI

#1399 fix(call): Silence button call
  common/locales/en-US/main.ftl
  ui/src/components/media/calling.rs
Labels: Missing dev review, Don't merge yet, Failed Automated Test, Waiting for CI

#1423 update(aria): add aria labels for crop tool profile and banner
  kit/src/elements/file/mod.rs
  kit/src/elements/folder/mod.rs
  ui/src/components/crop_image_tool/circle_format_tool/mod.rs
  ui/src/components/crop_image_tool/rectangle_format_tool/mod.rs
Labels: QA Tested, Ready to Merge

#1248 feat(dev): Dev tools update
  kit/src/components/context_menu/mod.rs
  ui/src/webview_config.rs
Labels: Missing dev review, Don't merge yet

#1430 chore(commands): add some of the common commands that are useful for …
  docs/dev_commands_cheatsheet.md
Labels: Waiting for CI

#1426 fix(model): fix bug where modal closes automatically
  kit/src/components/embeds/file_embed/mod.rs
  kit/src/layout/modal/mod.rs
  ui/src/components/crop_image_tool/circle_format_tool/mod.rs
  ui/src/layouts/storage/files_layout/file_modal.rs
  ui/src/layouts/storage/send_files_layout/modal.rs
  ui/src/main.rs
Labels: QA Tested, Ready to Merge

#1428 feat(sidebar): hide option to clear unreads when there are no unreads
  ui/src/layouts/chats/presentation/sidebar/mod.rs
Labels: Don't merge yet, Waiting for CI

#1300 feat(chat): Quickprofile layout
  Cargo.lock
  common/locales/en-US/main.ftl
  common/src/warp_runner/manager/commands/multipass_commands.rs
  kit/Cargo.toml
  kit/src/components/context_menu/mod.rs
  kit/src/components/context_menu/style.scss
  kit/src/components/message/mod.rs
  kit/src/components/message/style.scss
  kit/src/elements/button/mod.rs
  ui/src/layouts/chats/presentation/quick_profile/mod.rs
  ui/src/layouts/chats/style.scss
Labels: Failed Automated Test, Waiting for CI

#1429 feat(sidebar): display call controls in the sidebar
  ui/src/components/settings/sidebar.rs
Labels: Waiting for CI

#1431 fix(attachment): show thumbnail for images
  Cargo.lock
  Cargo.toml
  common/locales/en-US/main.ftl
  common/locales/pt-PT/main.ftl
  common/src/language/mod.rs
  common/src/state/mod.rs
  kit/Cargo.toml
  kit/src/components/embeds/file_embed/mod.rs
  kit/src/components/message/mod.rs
  kit/src/components/message_typing/mod.rs
  kit/src/elements/input/mod.rs
  ui/Cargo.toml
  ui/src/components/files/attachments.rs
  ui/src/components/files/upload_progress_bar/mod.rs
  ui/src/layouts/chats/mod.rs
  ui/src/layouts/chats/presentation/chat/topbar.rs
  ui/src/layouts/chats/presentation/chatbar.rs
  ui/src/layouts/chats/presentation/messages/mod.rs
  ui/src/layouts/chats/presentation/sidebar/mod.rs
  ui/src/layouts/storage/functions.rs
  ui/src/layouts/storage/send_files_layout/mod.rs
  ui/src/layouts/storage/send_files_layout/send_files_components.rs
  ui/src/layouts/unlock.rs
  ui/src/main.rs
Labels: QA Tested, Ready to Merge
