Repository Satellite-im/Uplink, pull requests merged in 2023-07, with the labels that each got.

#950 chore(appium): fail build job on appium workflow if app binary is not found
  .github/workflows/ui-test-automation.yml
Labels: Missing dev review, Don't merge yet

#951 chore(appium): repairing setup for appium workflow on upload artifact
  .github/workflows/ui-test-automation.yml
Labels: Missing dev review, Don't merge yet

#954 fix(ui): Change button background
  kit/src/components/embeds/file_embed/style.scss
  kit/src/elements/button/style.scss
  kit/src/style.scss
  ui/extra/themes/example.scss
  ui/extra/themes/light.scss
Labels: Ready for testing, Don't merge yet

#955 feat(Audio): Radio list selection
  common/locales/en-US/main.ftl
  icons/src/icons/outline/radio-selected.svg
  icons/src/icons/outline/radio.svg
  kit/src/elements/mod.rs
  kit/src/elements/radio_list/mod.rs
  kit/src/elements/radio_list/style.scss
  ui/src/components/settings/sub_pages/audio.rs
Labels: QA Tested, Don't merge yet, Failed Automated Test

#957 chore(Licenses): Added a place for us to display licenses
  common/locales/en-US/main.ftl
  icons/LICENSE-APACHE
  icons/src/icons/LICENSE-MIT
  ui/src/components/settings/sidebar.rs
  ui/src/components/settings/styles.scss
  ui/src/components/settings/sub_pages/developer.rs
  ui/src/components/settings/sub_pages/licenses.rs
  ui/src/components/settings/sub_pages/mod.rs
  ui/src/layouts/settings.rs
Labels: QA Tested, Ready to Merge

#949 feat(UploadProgressBar): Create loading progress bar
  Cargo.lock
  common/locales/en-US/main.ftl
  common/src/lib.rs
  common/src/state/storage.rs
  common/src/testing/mock.rs
  common/src/upload_file_channel.rs
  common/src/warp_runner/manager/commands/constellation_commands.rs
  common/src/warp_runner/manager/commands/mod.rs
  common/src/warp_runner/mod.rs
  ui/src/components/chat/compose/mod.rs
  ui/src/components/files/mod.rs
  ui/src/components/files/upload_progress_bar/mod.rs
  ui/src/components/files/upload_progress_bar/style.scss
  ui/src/layouts/storage/controller.rs
  ui/src/layouts/storage/file_modal.rs
  ui/src/layouts/storage/functions.rs
  ui/src/layouts/storage/mod.rs
  ui/src/main.rs
  ui/src/utils/get_drag_event.rs
  ui/src/utils/mod.rs
  ui/src/utils/verify_valid_paths.rs
Labels: QA Tested, Missing dev review, Don't merge yet, Failed Automated Test

#959 fix(Messaging): Fixes the "you" bug, kind of.
  common/locales/en-US/main.ftl
  ui/src/components/chat/compose/messages.rs
Labels: Missing dev review, Don't merge yet, QA Override

#963 chore(appium): add allure tests results report
  .github/workflows/ui-test-automation.yml
Labels: QA Tested, Missing dev review, Don't merge yet

#966 chore(language): update spanish translations file to most recent
  common/locales/es-MX/main.ftl
Labels: QA Tested, Missing dev review, Don't merge yet

#967 chore(locales): update pt locales
  common/locales/pt-PT/main.ftl
Labels: QA Tested, Missing dev review, Don't merge yet

#980 fix(files): Improv file/folder renaming
  kit/src/elements/file/mod.rs
  kit/src/elements/folder/mod.rs
  kit/src/elements/input/mod.rs
  kit/src/elements/input/script.js
  ui/src/layouts/storage/mod.rs
Labels: QA Tested, Ready to Merge

#988 fix(Profile): Clear input validation after submit
  kit/src/elements/input/mod.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
Labels: QA Tested, Ready to Merge, Failed Automated Test

#991 chore(link): fix url
  kit/src/components/message/mod.rs
Labels: QA Tested, Ready to Merge

#985 update(Link): Get more information as possible from links
  Cargo.lock
  kit/Cargo.toml
  kit/src/components/embeds/link_embed/get_link_data.rs
  kit/src/components/embeds/link_embed/mod.rs
Labels: QA Tested, Ready to Merge

#1000 chore(readme): Update README.md
  README.md
Labels: QA Tested, Ready to Merge, QA Override

#999 fix(Profile): Fixes long usernames overflowing profile
  ui/src/components/chat/style.scss
Labels: QA Tested, Ready to Merge

#1002 chore(allure): update workflow to upload artifacts from allure report
  .github/workflows/ui-test-automation.yml
Labels: Missing dev review, Don't merge yet, Failed Automated Test

#996 fix(sidebar): Display markdown in sidebar
  kit/src/components/message/mod.rs
  kit/src/components/user/mod.rs
  ui/src/components/chat/sidebar.rs
Labels: QA Tested, Ready to Merge, Failed Automated Test

#997 fix(login): Fix unlock page
  ui/src/layouts/unlock.rs
Labels: QA Tested, Don't merge yet

#974 feat(PasteFiles): Paste files or image from clipboard
  Cargo.lock
  common/src/warp_runner/manager/commands/constellation_commands.rs
  ui/Cargo.toml
  ui/src/components/chat/compose/chatbar.rs
  ui/src/components/files/file_preview.rs
  ui/src/components/mod.rs
  ui/src/components/paste_files_with_shortcut/mod.rs
  ui/src/layouts/storage/mod.rs
  ui/src/utils/clipboard/clipboard_data.rs
  ui/src/utils/clipboard/macos_clipboard.rs
  ui/src/utils/clipboard/mod.rs
  ui/src/utils/mod.rs
Labels: QA Tested, Failed Automated Test

#1005 chore(groups): add group creator indicator to dropdown
  common/locales/en-US/main.ftl
  ui/src/components/chat/compose/mod.rs
  ui/src/components/chat/group_users.rs
  ui/src/components/chat/style.scss
Labels: QA Tested, Ready to Merge, Failed Automated Test

#1009 fix(chat): wrap username in topbar
  ui/src/components/chat/style.scss
Labels: QA Tested, Ready to Merge, Failed Automated Test

#1023 add(aria): Add missing aria labels for UI elements
  kit/src/components/embeds/file_embed/mod.rs
  kit/src/components/message/mod.rs
  kit/src/elements/textarea/mod.rs
  kit/src/layout/modal/mod.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/files/upload_progress_bar/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1031 chore(ci): update
  .github/workflows/new-ticket-label-issue.yml
Labels: QA Tested, Missing dev review, Don't merge yet

#1035 fix(input): Add margin to textareas
  kit/src/elements/textarea/style.scss
Labels: QA Tested, Ready to Merge, Failed Automated Test

#1022 chore(misc): Various stuff
  common/Cargo.toml
  common/locales/en-US/main.ftl
  common/src/lib.rs
  common/src/state/action.rs
  common/src/state/configuration.rs
  common/src/state/mod.rs
  common/src/state/ui.rs
  extensions/Cargo.toml
  kit/Cargo.toml
  kit/src/components/context_menu/mod.rs
  kit/src/components/context_menu/style.scss
  kit/src/components/message/mod.rs
  kit/src/components/message_group/style.scss
  kit/src/elements/input/style.scss
  kit/src/elements/textarea/style.scss
  ui/Cargo.toml
  ui/src/components/chat/compose/messages.rs
  ui/src/components/chat/compose/mod.rs
  ui/src/components/emoji_group/mod.rs
  ui/src/components/emoji_group/style.scss
  ui/src/components/mod.rs
  ui/src/components/settings/sub_pages/developer.rs
  ui/src/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet, Failed Automated Test

#1041 chore(build): add dmg file back to release
  .github/workflows/build-dmg-universal.yml
Labels: Missing dev review, Don't merge yet

#1043 chore(linter): fix linter
  ui/src/components/chat/compose/messages.rs
Labels: Ready to Merge, QA Override

#1044 fix(GroupUsers): Let find users with case non sensitive
  ui/src/components/chat/group_users.rs
Labels: QA Tested, Ready to Merge

#1036 fix(scroll): add scroll to create group
  ui/src/components/chat/style.scss
Labels: QA Tested, Ready to Merge, Failed Automated Test

#1034 fix(chat): New line at cursor location
  kit/src/elements/textarea/mod.rs
  kit/src/elements/textarea/script.js
Labels: QA Tested, Ready to Merge, Failed Automated Test

#1050 fix(vscode): new toml extension is now recommended
  .vscode/extensions.json
Labels: Ready to Merge, QA Override

#1018 chore(cargo): Update dependency
  .github/workflows/build-dmg-universal.yml
  .github/workflows/build-release-linux.yml
  .github/workflows/build-release-windows.yml
  .github/workflows/cargo.yml
  .github/workflows/ui-test-automation.yml
  Cargo.lock
  Cargo.toml
  README.md
  common/src/state/mod.rs
Labels: QA Tested, Ready to Merge

#1053 fix(messages): show past messages in correct order
  common/src/state/mod.rs
  common/src/warp_runner/manager/commands/raygun_commands.rs
  common/src/warp_runner/ui_adapter/mod.rs
  ui/src/components/chat/compose/messages.rs
Labels: QA Tested

#1055 fix(CreateGroup): Fix long username on create group
  ui/src/components/chat/create_group.rs
  ui/src/components/chat/style.scss
Labels: QA Tested, Ready to Merge
