Repository Satellite-im/Uplink, pull requests merged in 2023-02, with the labels that each got.

#215 fix(fmt): format project and modify VSCode settings.json
  .gitignore
  .vscode/settings.json
  kit/src/components/message/mod.rs
  kit/src/components/message_reply/mod.rs
  kit/src/elements/button/mod.rs
  kit/src/elements/folder/mod.rs
  kit/src/elements/input/mod.rs
  kit/src/elements/mod.rs
  kit/src/elements/tooltip/mod.rs
  shared/src/lib.rs
  ui/src/components/chat/compose.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/chat/welcome/mod.rs
  ui/src/components/debug_logger/mod.rs
  ui/src/components/friends/mod.rs
  ui/src/components/media/player.rs
  ui/src/components/settings/sub_pages/extensions.rs
  ui/src/layouts/friends.rs
Labels: QA Approved, Missing dev review

#218 update(log): Remove passphrase
  ui/src/warp_runner/mod.rs
Labels: QA Approved, Missing dev review

#222 fix(logging): don't log passphrase
  icons/build.rs
  ui/build.rs
  ui/src/components/chat/compose.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/friends/add.rs
  ui/src/components/friends/blocked/mod.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/friends/incoming_requests/mod.rs
  ui/src/components/friends/outgoing_requests/mod.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/layouts/create_account.rs
  ui/src/layouts/unlock.rs
  ui/src/logger/mod.rs
  ui/src/main.rs
  ui/src/testing/mock.rs
  ui/src/warp_runner/manager/commands/multipass_commands.rs
  ui/src/warp_runner/manager/commands/raygun_commands.rs
  ui/src/warp_runner/manager/commands/tesseract_commands.rs
  ui/src/warp_runner/manager/events.rs
  ui/src/warp_runner/mod.rs
  ui/src/warp_runner/ui_adapter/message_event.rs
Labels: Changes requested, QA Approved

#228 chore(cargo): Update dependency
  shared/Cargo.toml
  ui/Cargo.toml
  ui/src/warp_runner/mod.rs
  ui/src/warp_runner/ui_adapter/multipass_event.rs
Labels: QA Approved

#236 fix(sidebar): fix friends sidebar
  ui/src/layouts/friends.rs
  ui/src/main.rs
Labels: QA Approved

#212 feat(Constellation): Start constellation in Uplink adding new folder
  kit/src/elements/folder/mod.rs
  kit/src/elements/folder/style.scss
  kit/src/elements/input/mod.rs
  ui/src/layouts/files.rs
  ui/src/layouts/mod.rs
  ui/src/layouts/storage.rs
  ui/src/layouts/style.scss
  ui/src/main.rs
  ui/src/state/mod.rs
  ui/src/state/storage.rs
  ui/src/testing/mock.rs
  ui/src/warp_runner/manager/commands/constellation_commands.rs
  ui/src/warp_runner/manager/commands/mod.rs
  ui/src/warp_runner/manager/events.rs
  ui/src/warp_runner/manager/mod.rs
  ui/src/warp_runner/mod.rs
Labels: QA Approved, Missing dev review

#242 fix(PR213): address changes requested in PR 213
  kit/src/elements/folder/mod.rs
  ui/src/components/debug_logger/mod.rs
  ui/src/components/settings/sub_pages/notifications.rs
  ui/src/layouts/settings.rs
  ui/src/layouts/storage.rs
  ui/src/main.rs
  ui/src/state/mod.rs
  ui/src/state/notifications.rs
  ui/src/utils/notifications.rs
  ui/src/warp_runner/manager/commands/constellation_commands.rs
  ui/src/warp_runner/manager/events.rs
  ui/src/warp_runner/mod.rs
Labels: Missing dev review

#243 fix(serialize): fix custom serializers for state
  ui/src/main.rs
  ui/src/state/chats.rs
  ui/src/state/friends.rs
Labels: QA Approved, Missing dev review

#219 chore(appium): update build process on macos CI
  .github/workflows/ui-test-execution.yml
Labels: Missing dev review, Draft

#250 fix(Settings): Adds spelling punctuation
  ui/src/components/settings/sub_pages/developer.rs
Labels: Missing dev review

#252 feat(Constellation): Upload files using file browser
  kit/src/elements/file/mod.rs
  kit/src/elements/file/style.scss
  ui/Cargo.toml
  ui/src/components/debug_logger/mod.rs
  ui/src/components/debug_logger/style.scss
  ui/src/layouts/storage.rs
  ui/src/logger/mod.rs
  ui/src/warp_runner/manager/commands/constellation_commands.rs
Labels: QA Approved, Missing dev review

#264 fix(toast): position toast for mobile
  kit/src/components/toast/style.scss
Labels: QA Approved

#270 chore(sounds): comment out the focus sound
  ui/src/main.rs
Labels: Missing dev review

#271 fix(misc): Increase file desc limit
  ui/Cargo.toml
  ui/src/main.rs
Labels: bug, Missing dev review, improvement, Medium Priority

#273 chore(sounds): comment out the use to fix the warning
  ui/src/main.rs
Labels: Ready for testing

#283 chore(profile): fix developer button to open the right path
  ui/src/components/settings/sub_pages/developer.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#284 add(Folder): Add unit tests to format name function
  kit/src/elements/folder/mod.rs
Labels: QA Tested, Ready to Merge

#266 feat(Constellation): Directories navigation
  kit/src/elements/folder/mod.rs
  kit/src/elements/input/mod.rs
  kit/src/elements/multiline/mod.rs
  ui/src/components/friends/add.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/layouts/create_account.rs
  ui/src/layouts/storage.rs
  ui/src/layouts/unlock.rs
  ui/src/main.rs
  ui/src/state/action.rs
  ui/src/state/mod.rs
  ui/src/state/storage.rs
  ui/src/state/ui.rs
  ui/src/testing/mock.rs
  ui/src/warp_runner/manager/commands/constellation_commands.rs
  ui/src/warp_runner/mod.rs
Labels: QA Tested, Ready to Merge

#282 chore(themes): fix themes dropdown for windows and sorts items alphabetically
  ui/src/main.rs
  ui/src/utils/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#277 fix(pr252): address comments for real this time
  kit/src/elements/file/mod.rs
  ui/src/components/debug_logger/mod.rs
  ui/src/utils/mod.rs
  ui/src/warp_runner/manager/commands/constellation_commands.rs
Labels: QA Tested

#285 fix(FolderLocations): don't hardcode paths for folders
  ui/src/components/settings/sub_pages/developer.rs
  ui/src/utils/mod.rs
Labels: QA Tested, Missing dev review

#292 fix(theme): fixed the line we dont need anymore
  ui/src/utils/mod.rs
Labels: Ready for testing, Don't merge yet

#295 fix(username): auto focus for username
  ui/src/layouts/create_account.rs
Labels: QA Tested, Ready to Merge

#294 fix(Storage): Fix files grid in storage
  kit/src/elements/file/style.scss
  kit/src/elements/folder/style.scss
Labels: QA Tested, Files, Ready to Merge

#296 chore(test): add UI test results report as PR comment
  .github/workflows/ui-test-execution.yml
Labels: QA Tested, Ready to Merge

#300 fix(tooltip): videocall tooltip clipped offscreen
  ui/src/components/chat/compose.rs
  ui/src/components/chat/style.scss
Labels: QA Tested

#303 chore(sidebar): fix issue with resize handle
  kit/src/layout/sidebar/script.js
  kit/src/layout/sidebar/style.scss
  ui/src/components/chat/style.scss
Labels: QA Tested, Ready to Merge

#276 chore(Sounds): Started wiring notification sounds
  shared/locales/en-US/main.ftl
  ui/src/components/settings/sub_pages/audio.rs
  ui/src/components/settings/sub_pages/developer.rs
  ui/src/config.rs
  ui/src/state/action.rs
  ui/src/state/configuration.rs
  ui/src/state/mod.rs
  ui/src/state/notifications.rs
  ui/src/utils/notifications.rs
  ui/src/warp_runner/ui_adapter/message_event.rs
  ui/src/warp_runner/ui_adapter/multipass_event.rs
Labels: Missing dev review, Don't merge yet

#298 feat(Thumbnail): Add thumbnails for images and video files
  kit/src/elements/file/mod.rs
  kit/src/elements/file/style.scss
  ui/Cargo.toml
  ui/src/layouts/storage.rs
  ui/src/warp_runner/manager/commands/constellation_commands.rs
Labels: QA Tested, Missing dev review, Don't merge yet, Files

#309 fix(hovers): fix hover jitter on button
  kit/src/style.scss
Labels: QA Tested, Ready to Merge

#310 fix(timestamp): fix "time ago" calculation in User element
  kit/Cargo.toml
  kit/src/components/user/mod.rs
  ui/src/components/chat/sidebar.rs
Labels: Missing dev review, Don't merge yet

#278 fix(did_to_identity): never fail
  ui/src/warp_runner/ui_adapter/mod.rs
Labels: Ready for testing, Ready to Merge

#311 fix(config): fix default values and saving
  ui/src/components/chat/sidebar.rs
  ui/src/components/settings/sidebar.rs
  ui/src/components/settings/sub_pages/audio.rs
  ui/src/components/settings/sub_pages/developer.rs
  ui/src/components/settings/sub_pages/general.rs
  ui/src/components/settings/sub_pages/notifications.rs
  ui/src/config.rs
  ui/src/layouts/create_account.rs
  ui/src/layouts/unlock.rs
  ui/src/logger/mod.rs
  ui/src/main.rs
  ui/src/state/action.rs
  ui/src/state/configuration.rs
  ui/src/state/mod.rs
  ui/src/state/notifications.rs
  ui/src/warp_runner/manager/commands/constellation_commands.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#313 feat(chats): show unread
  kit/src/components/user/mod.rs
  ui/src/components/chat/compose.rs
  ui/src/layouts/chat.rs
  ui/src/layouts/friends.rs
  ui/src/layouts/settings.rs
  ui/src/layouts/storage.rs
  ui/src/state/action.rs
  ui/src/state/chats.rs
  ui/src/state/mod.rs
  ui/src/state/ui.rs
Labels: QA Tested, Ready to Merge

#312 feat(Constellation): Rename files and folders
  common/locales/en-US/main.ftl
  common/locales/es-MX/main.ftl
  common/locales/pt-BR/main.ftl
  common/locales/pt-PT/main.ftl
  common/src/warp_runner/manager/commands/constellation_commands.rs
  kit/src/elements/file/mod.rs
  kit/src/elements/folder/mod.rs
  kit/src/elements/input/mod.rs
  kit/src/layout/chatbar/mod.rs
  ui/src/components/friends/add.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/layouts/create_account.rs
  ui/src/layouts/storage.rs
  ui/src/layouts/unlock.rs
Labels: Ready for testing, Don't merge yet

#317 add(ui): add aria labels needed to for appium tests
  kit/src/elements/switch/mod.rs
  kit/src/elements/tooltip/mod.rs
  kit/src/layout/topbar/mod.rs
  ui/src/components/debug_logger/mod.rs
  ui/src/components/friends/add.rs
  ui/src/components/settings/sub_pages/developer.rs
  ui/src/components/settings/sub_pages/notifications.rs
  ui/src/main.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#293 update(Storage): Fix scroll in uplink storage
  ui/src/layouts/storage.rs
  ui/src/layouts/style.scss
Labels: Changes requested, Don't merge yet, Files, Low Priority

#315 feat(DownloadFile): Download one file with right click
  common/locales/en-US/main.ftl
  common/locales/es-MX/main.ftl
  common/locales/pt-BR/main.ftl
  common/locales/pt-PT/main.ftl
  common/src/warp_runner/manager/commands/constellation_commands.rs
  ui/src/layouts/storage.rs
Labels: QA Tested, Missing dev review, Don't merge yet, Files, Low Priority

#325 fix(extensions): remove panics
  extensions/src/lib.rs
  kit/src/components/user/mod.rs
  kit/src/elements/file/mod.rs
  native_extensions/emoji_selector/src/lib.rs
  ui/src/components/chat/compose.rs
  ui/src/components/settings/sub_pages/extensions.rs
  ui/src/extensions/mod.rs
  ui/src/layouts/storage.rs
  ui/src/main.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#326 feat(replies): add back end for displaying message replies and reactions
  common/src/lib.rs
  common/src/state/action.rs
  common/src/state/chats.rs
  common/src/state/mod.rs
  common/src/testing/mock.rs
  common/src/warp_runner/manager/commands/raygun_commands.rs
  common/src/warp_runner/ui_adapter/message_event.rs
  common/src/warp_runner/ui_adapter/mod.rs
  kit/Cargo.toml
  kit/src/components/message/mod.rs
  ui/src/components/chat/compose.rs
  ui/src/components/chat/sidebar.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#331 fix(clippy): fix a few clippy warnings
  extensions/src/lib.rs
  kit/src/components/message/mod.rs
  ui/src/components/calldialog/mod.rs
  ui/src/components/friends/friend/mod.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/settings/sub_pages/developer.rs
  ui/src/logger/mod.rs
Labels: Missing dev review, Don't merge yet

#328 add(icon): Add files via upload
  icons/src/icons/outline/basketball.svg
  icons/src/icons/outline/leaf.svg
  icons/src/icons/outline/omega.svg
Labels: QA Tested, Missing dev review, Don't merge yet

#333 feat(logger): add button to view state
  common/locales/en-US/main.ftl
  ui/src/components/settings/sub_pages/developer.rs
  ui/src/logger/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#314 fix(clearmessage): clear friend did after submit
  kit/src/elements/input/mod.rs
  ui/src/components/friends/add.rs
Labels: QA Tested, Ready to Merge

#324 chore(Windows/Unix): Remove toolbar on systems other than osx
  README.md
  ui/Cargo.toml
  ui/src/main.rs
  ui/src/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#332 feat(delete): add ability to delete a message from a conversation
  common/locales/en-US/main.ftl
  common/src/state/mod.rs
  common/src/warp_runner/manager/commands/raygun_commands.rs
  common/src/warp_runner/ui_adapter/message_event.rs
  kit/src/components/context_menu/mod.rs
  ui/src/components/chat/compose.rs
  ui/src/extensions/mod.rs
Labels: QA Tested, Ready to Merge

#340 chore(cargo): Update Dependency
  common/Cargo.toml
  extensions/Cargo.toml
  kit/Cargo.toml
  ui/Cargo.toml
Labels: QA Tested, Missing dev review, Don't merge yet

#339 fix(windows): remove transparency support . . . known issue on windows
  ui/src/main.rs
Labels: QA Tested, Ready to Merge

#342 chore(appium): update GH action for UI Tests on MacOS
  .github/workflows/ui-test-execution.yml
Labels: QA Tested, Ready to Merge

#338 chore(directories): rename uplink directory
  common/src/lib.rs
  ui/src/main.rs
Labels: QA Tested, Ready to Merge

#344 feat(DeleteItems): Delete a file or entire directory
  common/locales/en-US/main.ftl
  common/locales/es-MX/main.ftl
  common/locales/pt-BR/main.ftl
  common/locales/pt-PT/main.ftl
  common/src/warp_runner/manager/commands/constellation_commands.rs
  ui/src/components/chat/compose.rs
  ui/src/layouts/storage.rs
Labels: QA Tested, Files, Ready to Merge

#335 feat(chats): wire up UI for replies, typing indicator, and attachments
  common/src/warp_runner/manager/commands/raygun_commands.rs
  kit/src/components/file_embed/mod.rs
  kit/src/components/message/mod.rs
  kit/src/components/message_reply/style.scss
  kit/src/components/message_typing/style.scss
  launch_docker.sh
  quick_build.sh
  ui/src/components/chat/compose.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/chat/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet
