Repository Satellite-im/Uplink, pull requests merged in 2023-01, with the labels that each got.

#47 chore(Overlay): Started Uplink Overlay
  .DS_Store
  Cargo.lock
  Makefile
  kit/Cargo.toml
  ui/Cargo.toml
  ui/Config.toml
  ui/extra/macos/Uplink.app/Contents/Info.plist
  ui/locales/en-US/main.ftl
  ui/src/components/settings/sub_pages/developer.rs
  ui/src/components/settings/sub_pages/general.rs
  ui/src/config.rs
  ui/src/layouts/unlock.rs
  ui/src/main.rs
  ui/src/overlay/mod.rs
  ui/src/overlay/style.css
  ui/src/state.rs
  ui/src/testing/mock.rs
  ui/src/warp_runner/mod.rs
Labels: Missing dev review

#49 update(Theme): Add Light theme
  ui/extra/themes/light.scss
Labels: QA Approved, Missing dev review

#53 chore(state): refactor state by splitting it into multiple files
  ui/src/components/chat/compose.rs
  ui/src/components/media/player.rs
  ui/src/components/media/popout_player.rs
  ui/src/state/account.rs
  ui/src/state/action.rs
  ui/src/state/chats.rs
  ui/src/state/friends.rs
  ui/src/state/identity.rs
  ui/src/state/mod.rs
  ui/src/state/route.rs
  ui/src/state/settings.rs
  ui/src/state/ui.rs
  ui/src/testing/mock.rs
Labels: Missing dev review

#56 feat(MediaPlayer): improve handling of calls and MediaPlayer
  ui/src/components/chat/compose.rs
  ui/src/components/media/player.rs
  ui/src/components/media/popout_player.rs
  ui/src/components/media/remote_control.rs
  ui/src/main.rs
  ui/src/state/action.rs
  ui/src/state/chats.rs
  ui/src/state/mod.rs
  ui/src/state/ui.rs
  ui/src/testing/mock.rs
Labels: QA Approved, Missing dev review

#55 update(Uplink-Checklist): Updated and added tests for Settings
  ui/docs/testing/uplink-checklist.md
Labels: documentation, Missing dev review

#61 chore(Indicators): Add css for circle indication icons
  kit/src/compiled_styles.css
  kit/src/components/indicator/mod.rs
  kit/src/components/indicator/style.scss
Labels: Missing dev review

#62 chore(Config): Setup developer mode and caceh dir
  ui/src/components/settings/sub_pages/developer.rs
  ui/src/config.rs
Labels: Missing dev review

#65 feat(cmdline): add command line args and miscellaneous clean up
  kit/src/components/indicator/mod.rs
  kit/src/elements/select/mod.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/config.rs
  ui/src/main.rs
  ui/src/state/action.rs
  ui/src/state/mod.rs
  ui/src/utils/format_timestamp.rs
  ui/src/utils/sounds.rs
  ui/src/warp_runner/mod.rs
Labels: QA Approved, Missing dev review

#72 chore(drag): move desktop drag up so its across the entire top of app…
  ui/src/components/chat/sidebar.rs
  ui/src/components/chat/style.scss
  ui/src/main.rs
  ui/src/style.scss
Labels: Missing dev review

#74 chore(appium): add appium tests and aria labels for ui locators
  .gitignore
  e2e-tests/README.md
  e2e-tests/babel.config.js
  e2e-tests/config/wdio.mac.app.conf.ts
  e2e-tests/config/wdio.mac.ci.conf.ts
  e2e-tests/config/wdio.shared.conf.ts
  e2e-tests/config/wdio.shared.local.appium.conf.ts
  e2e-tests/package.json
  e2e-tests/scripts/run_appium_macos_server.sh
  e2e-tests/tests/helpers/commands.ts
  e2e-tests/tests/screenobjects/AppScreen.ts
  e2e-tests/tests/screenobjects/UplinkMainScreen.ts
  e2e-tests/tests/specs/welcome-screen.spec.ts
  e2e-tests/tsconfig.json
  kit/src/components/nav/mod.rs
  kit/src/components/user/mod.rs
  kit/src/elements/button/mod.rs
  kit/src/layout/sidebar/mod.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/chat/welcome/mod.rs
  ui/src/components/settings/sidebar.rs
  ui/src/main.rs
Labels: QA Approved

#77 feat(login): add unlock and auth layouts
  .gitignore
  Cargo.lock
  kit/src/elements/file/mod.rs
  kit/src/elements/folder/mod.rs
  kit/src/elements/input/mod.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/chat/welcome/mod.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/media/player.rs
  ui/src/components/settings/sidebar.rs
  ui/src/layouts/auth.rs
  ui/src/layouts/chat.rs
  ui/src/layouts/files.rs
  ui/src/layouts/friends.rs
  ui/src/layouts/mod.rs
  ui/src/layouts/unlock.rs
  ui/src/main.rs
  ui/src/state/mod.rs
  ui/src/warp_runner/commands.rs
  ui/src/warp_runner/mod.rs
Labels: QA Approved, Missing dev review

#81 fix(SelectComponent): Add key again
  kit/src/elements/select/mod.rs
  ui/src/components/settings/sub_pages/general.rs
  ui/src/testing/mock.rs
Labels: Ready for testing, Missing dev review

#82 fix(Swtich): Fix underline on switch element
  kit/src/compiled_styles.css
  kit/src/elements/switch/style.scss
Labels: QA Approved, Missing dev review

#79 chore(icon): Add files via upload
  icons/src/icons/outline/chat-plus.svg
  icons/src/icons/outline/chat-slash.svg
  icons/src/icons/outline/circle.svg
  icons/src/icons/outline/replay-one.svg
  icons/src/icons/outline/user-blocked.svg
  icons/src/icons/outline/window-share.svg
Labels: QA Approved, Missing dev review

#90 chore(appium): add aria labels for input and buttons
  kit/src/components/nav/mod.rs
  kit/src/elements/button/mod.rs
  kit/src/elements/input/mod.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/chat/welcome/mod.rs
  ui/src/components/settings/sidebar.rs
  ui/src/layouts/unlock.rs
Labels: QA Approved, Missing dev review

#95 chore(appium): remove appium dir from uplink repo
  .gitignore
  e2e-tests/README.md
  e2e-tests/babel.config.js
  e2e-tests/config/wdio.mac.app.conf.ts
  e2e-tests/config/wdio.mac.ci.conf.ts
  e2e-tests/config/wdio.shared.conf.ts
  e2e-tests/config/wdio.shared.local.appium.conf.ts
  e2e-tests/package.json
  e2e-tests/scripts/run_appium_macos_server.sh
  e2e-tests/tests/helpers/commands.ts
  e2e-tests/tests/screenobjects/AppScreen.ts
  e2e-tests/tests/screenobjects/UplinkMainScreen.ts
  e2e-tests/tests/specs/welcome-screen.spec.ts
  e2e-tests/tsconfig.json
Labels: Missing dev review

#92 update(PopoutPlayer): Close popout when click on close button
  icons/src/outline.rs
  ui/src/components/chat/compose.rs
  ui/src/components/media/player.rs
  ui/src/components/media/popout_player.rs
  ui/src/components/media/remote_control.rs
  ui/src/layouts/auth.rs
  ui/src/state/action.rs
  ui/src/state/mod.rs
  ui/src/state/ui.rs
Labels: QA Approved

#105 update(Window): No resize window when click on chat page
  ui/src/layouts/auth.rs
  ui/src/layouts/chat.rs
Labels: QA Approved

#107 fix(Favorites): Fix favorites indicator
  kit/src/components/user_image_group/mod.rs
Labels: QA Approved

#102 update(ui): add aria labels for ui elements
  kit/src/elements/button/mod.rs
  kit/src/elements/file/mod.rs
  kit/src/elements/folder/mod.rs
  kit/src/elements/input/mod.rs
  ui/src/components/settings/mod.rs
  ui/src/components/settings/sub_pages/audio.rs
  ui/src/components/settings/sub_pages/developer.rs
  ui/src/components/settings/sub_pages/extensions.rs
  ui/src/components/settings/sub_pages/files.rs
  ui/src/components/settings/sub_pages/general.rs
  ui/src/components/settings/sub_pages/privacy.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/layouts/auth.rs
  ui/src/layouts/chat.rs
  ui/src/layouts/files.rs
  ui/src/layouts/friends.rs
  ui/src/layouts/settings.rs
Labels: QA Approved

#106 feat(misc): misc improvements
  ui/Cargo.toml
  ui/src/components/chat/compose.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/friends/blocked/mod.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/friends/incoming_requests/mod.rs
  ui/src/components/friends/outgoing_requests/mod.rs
  ui/src/config.rs
  ui/src/layouts/auth.rs
  ui/src/layouts/unlock.rs
  ui/src/main.rs
  ui/src/state/mod.rs
  ui/src/utils/mod.rs
  ui/src/warp_runner/commands.rs
  ui/src/warp_runner/mod.rs
Labels: QA Approved

#101 chore(icons): Change output of icon codegen
  icons/build.rs
  icons/src/lib.rs
  icons/src/outline.rs
  icons/src/solid.rs
Labels: QA Approved, improvement

#76 fix(Sidebar): add background to full width sidebar so that messages d…
  kit/src/compiled_styles.css
  kit/src/style.scss
Labels: Missing dev review, Draft

#108 chore(responsive): first pass at responsive settings
  ui/src/layouts/settings.rs
  ui/src/layouts/style.scss
Labels: Missing dev review

#115 chore(misc): Cleanup of codebase
  .gitignore
  kit/Cargo.toml
  kit/src/compiled_styles.css
  kit/src/components/context_menu/mod.rs
  kit/src/components/file_embed/mod.rs
  kit/src/components/indicator/mod.rs
  kit/src/components/message/mod.rs
  kit/src/components/message_divider/mod.rs
  kit/src/components/message_reply/mod.rs
  kit/src/components/nav/mod.rs
  kit/src/components/user/mod.rs
  kit/src/components/user_image/mod.rs
  kit/src/components/user_image_group/mod.rs
  kit/src/elements/button/mod.rs
  kit/src/elements/file/mod.rs
  kit/src/elements/folder/mod.rs
  kit/src/elements/input/mod.rs
  kit/src/elements/mod.rs
  kit/src/elements/switch/mod.rs
  kit/src/elements/tooltip/mod.rs
  kit/src/layout/chatbar/mod.rs
  ui/src/components/chat/sidebar.rs
  ui/src/layouts/settings.rs
  ui/src/state/mod.rs
Labels: QA Approved

#120 update(Language): Add spanish
  shared/locales/en-US/main.ftl
  shared/locales/es-MX/main.ftl
  shared/locales/pt-BR/main.ftl
  shared/locales/pt-PT/main.ftl
  shared/src/language/mod.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/chat/welcome/mod.rs
  ui/src/components/files/sidebar.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/media/player.rs
  ui/src/components/media/popout_player.rs
  ui/src/layouts/auth.rs
  ui/src/layouts/create_account.rs
  ui/src/layouts/mod.rs
  ui/src/layouts/unlock.rs
  ui/src/main.rs
  ui/src/testing/mock.rs
  ui/src/warp_runner/commands.rs
  ui/src/warp_runner/mod.rs
  ui/src/window_manager/mod.rs
Labels: Ready for testing, Missing dev review

#114 fix(login): don't load state until the user is authenticated
  shared/locales/en-US/main.ftl
  shared/locales/pt-BR/main.ftl
  shared/locales/pt-PT/main.ftl
  ui/src/components/chat/sidebar.rs
  ui/src/components/chat/welcome/mod.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/media/player.rs
  ui/src/components/media/popout_player.rs
  ui/src/layouts/auth.rs
  ui/src/layouts/create_account.rs
  ui/src/layouts/mod.rs
  ui/src/layouts/unlock.rs
  ui/src/main.rs
  ui/src/warp_runner/commands.rs
  ui/src/warp_runner/mod.rs
  ui/src/window_manager/mod.rs
Labels: QA Approved, Missing dev review

#122 update(global): responsive changes
  icons/src/icons/outline/sidebar-arrow-left.svg
  icons/src/icons/outline/sidebar.svg
  kit/src/components/context_menu/mod.rs
  kit/src/components/nav/mod.rs
  kit/src/elements/button/mod.rs
  kit/src/layout/sidebar/mod.rs
  kit/src/layout/sidebar/style.scss
  kit/src/layout/topbar/mod.rs
  kit/src/style.scss
  ui/extra/themes/draculish.scss
  ui/src/components/chat/compose.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/media/popout_player.rs
  ui/src/components/settings/sidebar.rs
  ui/src/components/settings/styles.scss
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/layouts/auth.rs
  ui/src/layouts/chat.rs
  ui/src/layouts/files.rs
  ui/src/layouts/friends.rs
  ui/src/layouts/settings.rs
  ui/src/layouts/style.scss
  ui/src/main.rs
  ui/src/state/action.rs
  ui/src/state/mod.rs
  ui/src/state/ui.rs
  ui/src/style.scss
  ui/src/testing/mock.rs
Labels: QA Approved, Missing dev review

#133 chore(Responsive): Fix issues in #125
  kit/src/components/message_group/style.scss
  kit/src/components/user_image_group/mod.rs
  kit/src/layout/chatbar/style.scss
  ui/src/components/chat/compose.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/friends/friend/mod.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/main.rs
Labels: Changes requested, Missing dev review

#134 update(Popout): Close popout with popout button
  ui/src/components/media/style.scss
Labels: QA Approved, Missing dev review

#141 feat(friends): mostly wire up friends to warp
  kit/src/components/user_image_group/mod.rs
  kit/src/elements/button/mod.rs
  shared/locales/en-US/main.ftl
  shared/locales/pt-BR/main.ftl
  shared/locales/pt-PT/main.ftl
  ui/Cargo.toml
  ui/src/components/chat/compose.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/friends/add.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/friends/incoming_requests/mod.rs
  ui/src/layouts/auth.rs
  ui/src/layouts/chat.rs
  ui/src/layouts/create_account.rs
  ui/src/layouts/files.rs
  ui/src/layouts/friends.rs
  ui/src/layouts/settings.rs
  ui/src/layouts/unlock.rs
  ui/src/main.rs
  ui/src/state/chats.rs
  ui/src/state/friends.rs
  ui/src/state/mod.rs
  ui/src/testing/mock.rs
  ui/src/utils/mod.rs
  ui/src/warp_runner/commands.rs
  ui/src/warp_runner/mod.rs
  ui/src/warp_runner/ui_adapter/mod.rs
Labels: QA Approved

#138 chore(tests): add GH workflow for CI UI tests execution
  .github/workflows/ui-test-execution.yml
Labels: QA Approved, Missing dev review

#145 chore(Icons): Adds support for 17 new icons.
  icons/src/icons/outline/activity.svg
  icons/src/icons/outline/bluetooth.svg
  icons/src/icons/outline/command.svg
  icons/src/icons/outline/loader.svg
  icons/src/icons/outline/microphone-slash.svg
  icons/src/icons/outline/phone-call.svg
  icons/src/icons/outline/phone-forward.svg
  icons/src/icons/outline/phone-slash.svg
  icons/src/icons/outline/shield-slash.svg
  icons/src/icons/outline/shield.svg
  icons/src/icons/outline/speaker-wave-alt.svg
  icons/src/icons/outline/speaker.svg
  icons/src/icons/outline/toggle-left.svg
  icons/src/icons/outline/toggle-right.svg
  icons/src/icons/outline/view-columns-2.svg
  icons/src/icons/outline/voicemail.svg
  icons/src/icons/outline/watch.svg
Labels: Missing dev review

#148 chore(cargo): Update dependency
  shared/Cargo.toml
  ui/Cargo.toml
  ui/src/warp_runner/commands.rs
  ui/src/warp_runner/mod.rs
Labels: enhancement, QA Approved, Missing dev review, improvement

#156 chore(inputValidation): Fix input validation
  kit/src/elements/input/mod.rs
Labels: QA Approved

#149 feat(Logger): Create logger
  .gitignore
  shared/locales/en-US/main.ftl
  shared/locales/es-MX/main.ftl
  shared/locales/pt-BR/main.ftl
  shared/locales/pt-PT/main.ftl
  ui/Cargo.toml
  ui/src/components/debug_logger/mod.rs
  ui/src/components/debug_logger/script.js
  ui/src/components/debug_logger/style.scss
  ui/src/components/mod.rs
  ui/src/components/settings/sub_pages/audio.rs
  ui/src/components/settings/sub_pages/developer.rs
  ui/src/components/settings/sub_pages/general.rs
  ui/src/components/settings/sub_pages/privacy.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/logger/mod.rs
  ui/src/main.rs
  ui/src/state/action.rs
  ui/src/state/mod.rs
  ui/src/state/ui.rs
  ui/src/testing/mock.rs
  ui/src/window_manager/mod.rs
Labels: QA Approved

#155 feat(friends): wire up other friend events
  kit/src/elements/input/mod.rs
  shared/locales/en-US/main.ftl
  shared/locales/es-MX/main.ftl
  shared/locales/pt-BR/main.ftl
  shared/locales/pt-PT/main.ftl
  ui/Cargo.toml
  ui/src/components/chat/compose.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/friends/add.rs
  ui/src/components/friends/blocked/mod.rs
  ui/src/components/friends/friend/mod.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/friends/incoming_requests/mod.rs
  ui/src/components/friends/outgoing_requests/mod.rs
  ui/src/layouts/chat.rs
  ui/src/layouts/create_account.rs
  ui/src/layouts/unlock.rs
  ui/src/logger/mod.rs
  ui/src/main.rs
  ui/src/state/chats.rs
  ui/src/state/friends.rs
  ui/src/state/mod.rs
  ui/src/warp_runner/commands.rs
  ui/src/warp_runner/mod.rs
  ui/src/warp_runner/ui_adapter/mod.rs
Labels: Ready for testing, Missing dev review

#164 feat(unlock): allow enter key
  ui/src/layouts/unlock.rs
Labels: QA Approved

#162 chore(validation): added ability to ignore colons on inputs, which lets us insert friend codes but still otherwise limit alpha numeric chars
  kit/src/elements/input/mod.rs
  ui/src/components/friends/add.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/layouts/create_account.rs
  ui/src/layouts/unlock.rs
Labels: QA Approved

#167 update(vs-extensions): added Darius recommended vs-code extensions
  .vscode/extensions.json
Labels: QA Approved

#168 feat(friends): improve friend removal
  ui/src/components/chat/compose.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/main.rs
  ui/src/state/mod.rs
  ui/src/warp_runner/commands.rs
  ui/src/warp_runner/mod.rs
  ui/src/warp_runner/ui_adapter/mod.rs
Labels: QA Approved, Missing dev review

#169 fix(friends): make friends work with mock data again
  ui/src/components/friends/add.rs
  ui/src/components/friends/blocked/mod.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/friends/incoming_requests/mod.rs
  ui/src/components/friends/outgoing_requests/mod.rs
  ui/src/main.rs
  ui/src/state/action.rs
  ui/src/state/mod.rs
Labels: QA Approved, Missing dev review

#181 feat(settings): use logger instead of log
  ui/src/components/settings/sub_pages/profile/mod.rs
Labels: Missing dev review

#177 feat(input): allow clearing the input element
  kit/src/elements/file/mod.rs
  kit/src/elements/folder/mod.rs
  kit/src/elements/input/mod.rs
  kit/src/elements/multiline/mod.rs
  kit/src/layout/chatbar/mod.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/friends/add.rs
  ui/src/components/settings/sidebar.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/layouts/create_account.rs
  ui/src/layouts/unlock.rs
Labels: QA Approved, Missing dev review

#184 fix(input): Revert "feat(input): allow clearing the input element (#177)"
  kit/src/elements/file/mod.rs
  kit/src/elements/folder/mod.rs
  kit/src/elements/input/mod.rs
  kit/src/elements/multiline/mod.rs
  kit/src/layout/chatbar/mod.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/friends/add.rs
  ui/src/components/settings/sidebar.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/layouts/create_account.rs
  ui/src/layouts/unlock.rs
Labels: QA Approved

#194 chore(docs): add documentation for warp runner
  docs/architecture.md
Labels: documentation, Missing dev review

#196 chore(docs): Use tasks instead of threads
  docs/architecture.md
  ui/src/warp_runner/mod.rs
Labels: documentation, Missing dev review, improvement

#201 chore(cargo): Updated dependency
  shared/Cargo.toml
  ui/Cargo.toml
  ui/src/warp_runner/ui_adapter/mod.rs
Labels: enhancement, QA Approved, Missing dev review

#200 chore(WarpRunner): refactor warp_runner
  docs/architecture.md
  ui/src/components/chat/compose.rs
  ui/src/components/friends/add.rs
  ui/src/components/friends/blocked/mod.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/friends/incoming_requests/mod.rs
  ui/src/components/friends/outgoing_requests/mod.rs
  ui/src/layouts/create_account.rs
  ui/src/layouts/unlock.rs
  ui/src/main.rs
  ui/src/warp_runner/conv_stream.rs
  ui/src/warp_runner/manager/commands/mod.rs
  ui/src/warp_runner/manager/commands/multipass_commands.rs
  ui/src/warp_runner/manager/commands/raygun_commands.rs
  ui/src/warp_runner/manager/commands/tesseract_commands.rs
  ui/src/warp_runner/manager/events.rs
  ui/src/warp_runner/manager/mod.rs
  ui/src/warp_runner/mod.rs
  ui/src/warp_runner/ui_adapter/message_event.rs
  ui/src/warp_runner/ui_adapter/mod.rs
  ui/src/warp_runner/ui_adapter/multipass_event.rs
  ui/src/warp_runner/ui_adapter/raygun_event.rs
Labels: QA Approved, Missing dev review

#202 fix(warp_runner): clear tesseract and store warp_runner in use_ref
  ui/src/main.rs
  ui/src/warp_runner/manager/commands/multipass_commands.rs
  ui/src/warp_runner/manager/events.rs
Labels: QA Approved

#199 feat(logger): use log crate
  ui/src/components/debug_logger/mod.rs
  ui/src/logger/mod.rs
  ui/src/main.rs
Labels: Changes requested

#207 update(Uplink-Checklist): Adding more documentation
  ui/docs/testing/uplink-checklist.md
Labels: Missing dev review

#203 chore(tesseract-helper): added helper function to see if local accoun…
  ui/src/layouts/unlock.rs
  ui/src/main.rs
Labels: QA Approved

#205 feat(reactions): add reactions to warp_runner
  ui/src/components/chat/compose.rs
  ui/src/state/action.rs
  ui/src/state/mod.rs
  ui/src/warp_runner/manager/commands/raygun_commands.rs
  ui/src/warp_runner/ui_adapter/message_event.rs
Labels: QA Approved

#183 fix(devtool): fix theme and tools bug
  ui/src/components/settings/sub_pages/developer.rs
  ui/src/components/settings/sub_pages/general.rs
Labels: QA Approved

#210 fix(login): fix "invalid signature" error on login
  ui/Cargo.toml
  ui/src/logger/mod.rs
  ui/src/warp_runner/manager/commands/mod.rs
  ui/src/warp_runner/manager/commands/multipass_commands.rs
  ui/src/warp_runner/manager/commands/raygun_commands.rs
  ui/src/warp_runner/manager/commands/tesseract_commands.rs
  ui/src/warp_runner/manager/events.rs
  ui/src/warp_runner/manager/mod.rs
  ui/src/warp_runner/mod.rs
Labels: QA Approved

#211 feat(typing): add backend for typing indicator
  ui/src/components/chat/compose.rs
  ui/src/components/chat/style.scss
  ui/src/components/settings/sub_pages/general.rs
  ui/src/main.rs
  ui/src/state/chats.rs
  ui/src/state/mod.rs
  ui/src/testing/mock.rs
  ui/src/warp_runner/manager/commands/raygun_commands.rs
  ui/src/warp_runner/ui_adapter/message_event.rs
  ui/src/warp_runner/ui_adapter/mod.rs
Labels: QA Approved
