Repository Satellite-im/Uplink, pull requests merged in 2023-09, with the labels that each got.

#1168 feat(Raygun): Send files from storage into chats
  common/locales/en-US/main.ftl
  common/src/lib.rs
  common/src/warp_runner/manager/commands/raygun_commands.rs
  kit/src/elements/file/mod.rs
  kit/src/elements/file/style.scss
  ui/src/components/chat/compose/chatbar.rs
  ui/src/components/chat/compose/context_file_location.rs
  ui/src/components/chat/compose/mod.rs
  ui/src/components/chat/compose/quick_profile.rs
  ui/src/components/chat/compose/style.scss
  ui/src/layouts/storage/functions.rs
  ui/src/layouts/storage/mod.rs
  ui/src/layouts/storage/send_files_components.rs
  ui/src/layouts/storage/style.scss
  ui/src/layouts/style.scss
Labels: QA Tested, Don't merge yet, Failed Automated Test

#1166 chore(Css/UI): Cleaned up UI elements to conform to mockups and standard component.
  kit/src/components/channel/mod.rs
  kit/src/components/channel/style.scss
  kit/src/components/channel_group/mod.rs
  kit/src/components/channel_group/style.scss
  kit/src/components/context_menu/mod.rs
  kit/src/components/context_menu/style.scss
  kit/src/components/embeds/file_embed/mod.rs
  kit/src/components/embeds/file_embed/style.scss
  kit/src/components/message/style.scss
  kit/src/components/mod.rs
  kit/src/components/nav/style.scss
  kit/src/elements/button/style.scss
  kit/src/elements/input/style.scss
  kit/src/layout/chatbar/style.scss
  kit/src/layout/modal/mod.rs
  kit/src/layout/modal/style.scss
  kit/src/layout/sidebar/style.scss
  kit/src/layout/topbar/mod.rs
  kit/src/layout/topbar/style.scss
  kit/src/style.scss
  ui/src/components/chat/compose/mod.rs
  ui/src/components/chat/compose/quick_profile.rs
  ui/src/components/chat/edit_group.rs
  ui/src/components/chat/pinned_messages/mod.rs
  ui/src/components/chat/pinned_messages/script.js
  ui/src/components/chat/pinned_messages/style.scss
  ui/src/components/chat/scroll_to_message.js
  ui/src/components/chat/sidebar.rs
  ui/src/components/chat/style.scss
  ui/src/components/community/mod.rs
  ui/src/components/community/sidebar/mod.rs
  ui/src/components/mod.rs
  ui/src/layouts/community/mod.rs
  ui/src/layouts/community/sidebar.rs
  ui/src/layouts/community/style.scss
  ui/src/layouts/mod.rs
  ui/src/layouts/slimbar.rs
  ui/src/layouts/storage/file_modal.rs
  ui/src/main.rs
  ui/src/style.scss
Labels: Missing dev review, Failed Automated Test

#1179 feat(crash): Improve crash handling
  common/src/lib.rs
  ui/src/bootstrap.rs
Labels: Don't merge yet, QA Override, Failed Automated Test

#1180 fix(sidebar): Fix sidebar navigation not showing buttons correctly
  ui/src/components/chat/sidebar.rs
Labels: QA Tested, Ready to Merge, Failed Automated Test, Waiting for CI

#1175 chore(cargo): Update dependency
  Cargo.lock
  Cargo.toml
  common/src/sounds.rs
  common/src/state/mod.rs
  common/src/warp_runner/mod.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
Labels: Ready for testing

#1190 feat(misc): UI tweaks sep
  common/src/warp_runner/manager/commands/constellation_commands.rs
  kit/src/components/channel_group/style.scss
  kit/src/components/context_menu/style.scss
  kit/src/components/embeds/file_embed/mod.rs
  kit/src/components/embeds/file_embed/style.scss
  kit/src/components/message/style.scss
  kit/src/components/message_group/style.scss
  kit/src/elements/button/style.scss
  kit/src/elements/checkbox/mod.rs
  kit/src/elements/file/mod.rs
  kit/src/elements/file/style.scss
  kit/src/elements/folder/style.scss
  kit/src/elements/input/style.scss
  kit/src/layout/modal/mod.rs
  kit/src/layout/modal/style.scss
  kit/src/style.scss
  ui/src/components/chat/compose/chatbar.rs
  ui/src/components/chat/compose/context_file_location.rs
  ui/src/components/chat/compose/mod.rs
  ui/src/components/chat/compose/style.scss
  ui/src/components/chat/pinned_messages/style.scss
  ui/src/components/chat/sidebar.rs
  ui/src/components/chat/style.scss
  ui/src/components/emoji_group/mod.rs
  ui/src/components/emoji_group/style.scss
  ui/src/components/files/file_preview.rs
  ui/src/components/files/style.scss
  ui/src/layouts/chat.rs
  ui/src/layouts/friends.rs
  ui/src/layouts/storage/file_modal.rs
  ui/src/layouts/storage/mod.rs
  ui/src/layouts/storage/send_files_components.rs
  ui/src/layouts/storage/style.scss
  ui/src/layouts/style.scss
Labels: QA Tested, Don't merge yet, Failed Automated Test

#1157 feat(ui): Improve call UIs
  common/locales/en-US/main.ftl
  common/src/state/call.rs
  common/src/state/mod.rs
  ui/src/components/calldialog/mod.rs
  ui/src/components/calldialog/style.scss
  ui/src/components/chat/compose/mod.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/media/calling.rs
  ui/src/components/media/mod.rs
  ui/src/components/media/remote_control.rs
  ui/src/components/media/style.scss
  ui/src/components/mod.rs
  ui/src/components/style.scss
  ui/src/main.rs
Labels: QA Tested, Missing dev review

#1185 fix(blink): allow audio i/o devices which use 2 input/output channels
  Cargo.lock
  common/src/state/mod.rs
  common/src/warp_runner/manager/events.rs
Labels: Missing dev review, Don't merge yet

#1196 fix(messages): put backslash before >
  kit/src/components/message/mod.rs
Labels: QA Tested, Ready to Merge

#1205 update(extensions): fix turn off extension
  ui/src/components/chat/compose/chatbar.rs
Labels: Ready for testing, Missing dev review, Don't merge yet

#1200 fix(chat): Add missing unread indicator to chat button
  kit/src/components/nav/mod.rs
  kit/src/style.scss
  native_extensions/emoji_selector/src/lib.rs
  ui/src/main.rs
  ui/src/style.scss
Labels: Ready for testing, Don't merge yet

#1194 update(aria): change aria labels for user and friend
  kit/src/components/user/mod.rs
  kit/src/components/user_image_group/mod.rs
  ui/src/components/chat/compose/mod.rs
  ui/src/components/chat/sidebar.rs
  ui/src/components/friends/blocked/mod.rs
  ui/src/components/friends/friend/mod.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/friends/incoming_requests/mod.rs
  ui/src/components/friends/outgoing_requests/mod.rs
  ui/src/layouts/slimbar.rs
Labels: Missing dev review, Failed Automated Test

#1193 feat(chat): Emoji autofill
  common/src/state/ui.rs
  kit/src/elements/textarea/cursor_script.js
  kit/src/elements/textarea/mod.rs
  kit/src/elements/textarea/script.js
  kit/src/elements/textarea/update_char_counter.js
  kit/src/layout/chatbar/emoji_scroll.js
  kit/src/layout/chatbar/mod.rs
  native_extensions/emoji_selector/src/lib.rs
  ui/src/components/chat/compose/chatbar.rs
  ui/src/components/chat/style.scss
Labels: QA Tested, Waiting for CI

#1212 fix(settings): Fix welcome message width
  ui/src/components/settings/sub_pages/profile/style.scss
Labels: QA Tested, Ready to Merge, Failed Automated Test

#1213 fix(chat): Fix slimbar no scroll
  kit/src/layout/slimbar/style.scss
Labels: Waiting for CI

#1206 update(Chat): Fix drag and drop on chats on Windows OS
  ui/src/components/chat/compose/mod.rs
  ui/src/layouts/chat.rs
  ui/src/layouts/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet, Failed Automated Test

#1204 feat(markdown): improve markdown handling
  kit/Cargo.toml
  kit/src/components/message/mod.rs
  kit/src/components/nav/mod.rs
  kit/src/elements/input/mod.rs
  ui/src/components/chat/pinned_messages/mod.rs
  ui/src/main.rs
  ui/src/misc_scripts.rs
Labels: Waiting for CI

#1214 chore(chats): refactor get_messages
  ui/src/components/chat/compose/chatbar.rs
  ui/src/components/chat/compose/messages/coroutines.rs
  ui/src/components/chat/compose/messages/effects.rs
  ui/src/components/chat/compose/messages/mod.rs
  ui/src/components/chat/compose/messages/scripts.rs
  ui/src/utils/mod.rs
Labels: Waiting for CI

#1183 update(RayGun): Send files from both sources in same message
  Cargo.lock
  Cargo.toml
  common/locales/en-US/main.ftl
  common/src/lib.rs
  common/src/state/action.rs
  common/src/state/chats.rs
  common/src/state/mod.rs
  common/src/state/pending_message.rs
  common/src/warp_runner/manager/commands/constellation_commands.rs
  common/src/warp_runner/manager/commands/raygun_commands.rs
  kit/src/components/context_menu/mod.rs
  ui/src/components/chat/compose/chatbar.rs
  ui/src/components/chat/compose/context_file_location.rs
  ui/src/components/chat/compose/quick_profile.rs
  ui/src/components/files/upload_progress_bar/mod.rs
  ui/src/layouts/chat.rs
  ui/src/layouts/storage/controller.rs
  ui/src/layouts/storage/functions.rs
  ui/src/layouts/storage/mod.rs
  ui/src/layouts/storage/send_files_components.rs
  ui/src/utils/verify_valid_paths.rs
Labels: Waiting for CI

#1217 chore(locales): add pt-PT locales
  common/locales/pt-PT/main.ftl
Labels: Missing dev review, Don't merge yet

#1218 chore(key): remove duplicated key
  common/locales/en-US/main.ftl
Labels: Ready to Merge, QA Override

#1219 chore(Idea): Added run & build configs for .idea based editors
  .gitignore
  .idea/.gitignore
  .idea/Uplink.iml
  .idea/modules.xml
  .idea/vcs.xml
Labels: Waiting for CI

#1202 feat(settings): Add device selection for microphone/speaker
  common/src/state/settings.rs
  common/src/warp_runner/manager/commands/blink_commands.rs
  ui/src/components/settings/sub_pages/audio.rs
Labels: Waiting for CI

#1207 feat(call): Speaking indicator
  common/src/state/call.rs
  common/src/state/mod.rs
  common/src/warp_runner/manager/mod.rs
  kit/src/lib.rs
  ui/src/components/chat/compose/chatbar.rs
  ui/src/components/media/calling.rs
  ui/src/components/media/style.scss
  ui/src/main.rs
  ui/src/utils/mod.rs
Labels: Missing dev review, Don't merge yet

#1221 chore(chats): make unreads a HashSet ans rename messages functions
  common/src/state/chats.rs
  common/src/state/mod.rs
  common/src/testing/mock.rs
  common/src/warp_runner/ui_adapter/mod.rs
  ui/src/components/chat/compose/messages/mod.rs
  ui/src/components/chat/sidebar.rs
  ui/src/main.rs
Labels: QA Tested, Ready to Merge

#1224 fix(input): reset height on button click
  kit/src/elements/textarea/script.js
Labels: QA Tested, Missing dev review, Don't merge yet

#1225 chore(attachments): hide file download button when not hovering
  kit/src/components/embeds/file_embed/style.scss
Labels: Missing dev review, Don't merge yet, Failed Automated Test

#1198 update(Storage): Send Files from Storage to several chats
  common/locales/en-US/main.ftl
  common/src/warp_runner/manager/commands/raygun_commands.rs
  kit/src/components/embeds/file_embed/mod.rs
  kit/src/components/embeds/file_embed/style.scss
  ui/src/components/chat/compose/chatbar.rs
  ui/src/components/files/attachments.rs
  ui/src/components/files/mod.rs
  ui/src/layouts/storage/controller.rs
  ui/src/layouts/storage/mod.rs
  ui/src/layouts/storage/send_files_components.rs
  ui/src/layouts/storage/style.scss
  ui/src/layouts/style.scss
  ui/src/misc_scripts 2.rs
Labels: QA Tested, Ready to Merge, Failed Automated Test

#1230 chore(ui): Community UI assets
  common/locales/en-US/main.ftl
  kit/src/components/community/card/mod.rs
  kit/src/components/community/card/style.scss
  kit/src/components/community/mod.rs
  kit/src/components/context_menu/style.scss
  kit/src/components/embeds/file_embed/mod.rs
  kit/src/components/embeds/file_embed/style.scss
  kit/src/components/mod.rs
  kit/src/components/user/card/mod.rs
  kit/src/components/user/card/style.scss
  kit/src/components/user/mod.rs
  kit/src/layout/modal/style.scss
  kit/src/layout/slimbar/style.scss
  kit/src/style.scss
  ui/src/components/chat/compose/style.scss
  ui/src/components/chat/sidebar.rs
  ui/src/components/chat/style.scss
  ui/src/components/chat/welcome/style.scss
  ui/src/layouts/community/mod.rs
  ui/src/layouts/community/style.scss
  ui/src/layouts/storage/mod.rs
Labels: Missing dev review, Don't merge yet, QA Override

#1226 chore(cargo): Update dependency
  Cargo.lock
  Cargo.toml
  common/src/lib.rs
  common/src/warp_runner/manager/commands/blink_commands.rs
  common/src/warp_runner/mod.rs
  ui/src/layouts/chats/presentation/chat/controls.rs
Labels: Changes requested, QA Tested, Don't merge yet

#1234 chore(main): remove trace statement
  common/src/warp_runner/manager/commands/raygun_commands.rs
  ui/src/main.rs
Labels: Ready to Merge, QA Override

#1237 feat(ContextMenu): Add 'Open Console' option when on developer mode.
  Cargo.lock
  common/locales/en-US/main.ftl
  kit/src/components/channel/mod.rs
  kit/src/components/context_menu/mod.rs
  ui/src/components/files/file_preview.rs
  ui/src/components/friends/blocked/mod.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/friends/incoming_requests/mod.rs
  ui/src/components/friends/outgoing_requests/mod.rs
  ui/src/layouts/chats/presentation/context_menus/mod.rs
  ui/src/layouts/chats/presentation/messages/mod.rs
  ui/src/layouts/chats/presentation/sidebar/mod.rs
  ui/src/layouts/storage/mod.rs
  ui/src/layouts/unlock.rs
  ui/src/main.rs
Labels: QA Tested, Missing dev review, Don't merge yet, Waiting for CI

#1229 update(dependency): Dioxus update
  Cargo.lock
  Cargo.toml
  extensions/src/lib.rs
  icons/src/lib.rs
  kit/src/lib.rs
  native_extensions/clear_all/src/lib.rs
  native_extensions/emoji_selector/src/lib.rs
  ui/src/auth_guard.rs
  ui/src/components/debug_logger/mod.rs
  ui/src/components/media/popout_player.rs
  ui/src/layouts/chats/presentation/messages/mod.rs
  ui/src/layouts/create_account.rs
  ui/src/layouts/storage/files_layout/file_modal.rs
  ui/src/layouts/storage/send_files_layout/send_files_components.rs
  ui/src/layouts/unlock.rs
  ui/src/main.rs
Labels: QA Tested, Ready to Merge, Failed Automated Test

#1240 feat(lang): Update de translation
  common/locales/de/main.ftl
Labels: Missing dev review, Don't merge yet, Failed Automated Test

#1220 feat(calling): Implement volume configs for users
  common/src/state/settings.rs
  common/src/warp_runner/manager/commands/blink_commands.rs
  kit/src/elements/range/mod.rs
  ui/src/components/media/calling.rs
  ui/src/components/settings/sub_pages/audio.rs
  ui/src/layouts/chats/presentation/quick_profile/mod.rs
Labels: Waiting for CI

#1244 chore(appium): remove retry step from macos appium automated tests
  .github/workflows/ui-test-automation.yml
Labels: Missing dev review, Don't merge yet

#1245 fix(slimbar): Fix slimbar width inconsistent
  kit/src/layout/slimbar/style.scss
Labels: Waiting for CI

#1247 feat(dev): Always enable dev tools
  ui/Cargo.toml
  ui/src/webview_config.rs
Labels: Ready for testing, Don't merge yet

#1238 feat(logging): Add additional logging profiles
  common/src/lib.rs
  ui/src/bootstrap.rs
  ui/src/logger/mod.rs
  ui/src/main.rs
  ui/src/misc_scripts 2.rs
Labels: QA Tested, Ready to Merge

#1251 chore(debugger): add a launch profile to run cargo
  .vscode/launch.json
Labels: Missing dev review, Don't merge yet
