Repository Satellite-im/Uplink, pull requests merged in 2024-04, with the labels that each got.

#1958 fix(keybindings): Fix multiple keybind recording at once
  ui/src/components/settings/sub_pages/keybinds.rs
Labels: QA Tested, Ready to Merge

#1960 fix(ui): make modals in chat render on top of all
  ui/src/layouts/chats/style.scss
Labels: Waiting for CI

#1962 chore(release): release 1.0.1
  Cargo.lock
  Cargo.toml
Labels: Don't merge yet

#1961 feat(chat): Add toasts to various quickprofile actions
  common/locales/en-US/main.ftl
  ui/src/layouts/chats/presentation/quick_profile/mod.rs
Labels: QA Tested, Ready to Merge

#1969 fix(calling): Request mic (and camera)
  ui/extra/macos/Uplink.app/Contents/Info.plist
Labels: QA Tested

#1966 task(chat): Update what should be skipped in state.json
  common/src/state/chats.rs
  common/src/state/mod.rs
  common/src/state/scope_ids.rs
  common/src/testing/mock.rs
Labels: QA Tested, Ready to Merge

#1975 fix(chats): fix self reaction position
  kit/src/components/message_group/style.scss
  ui/src/layouts/chats/style.scss
Labels: Waiting for CI

#1976 fix(login): change ordering of account creation pages
  ui/src/layouts/log_in/copy_seed_words.rs
  ui/src/layouts/log_in/create_or_recover.rs
  ui/src/layouts/log_in/enter_username.rs
  ui/src/layouts/log_in/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet, Failed Automated Test

#1980 chore(appium): move appium install steps from workflow
  .github/workflows/ui-test-automation.yml
Labels: Don't merge yet

#1978 fix(ui): rfd import for file dialog fix
  ui/src/main.rs
Labels: QA Tested, Ready to Merge

#1977 chore(cargo): Update warp dependency
  .github/workflows/ui-test-automation.yml
  Cargo.lock
  Cargo.toml
Labels: QA Tested, Missing dev review, Don't merge yet

#1981 chore(release): release 1.0.3
  Cargo.lock
  Cargo.toml
Labels: Don't merge yet
