Repository Satellite-im/Uplink, pull requests merged in 2024-05, with the labels that each got.

#1983 chore(windows): update build action with new signing process
  .github/workflows/build-release-windows.yml
Labels: Missing dev review, Don't merge yet

#1987 chore(build): fix typo on env variable for cert
  .github/workflows/build-release-windows.yml
Labels: Missing dev review, Don't merge yet

#1988 chore(build): fix C: typo on build windows
  .github/workflows/build-release-windows.yml
Labels: Missing dev review, Don't merge yet

#1982 chore(workflows): upgrade deprecated GH actions
  .github/workflows/build-dmg-universal.yml
  .github/workflows/cargo.yml
  .github/workflows/lint-PR-title.yml
  .github/workflows/ui-test-automation.yml
Labels: Don't merge yet

#1990 chore(release): release 1.0.4
  Cargo.lock
  Cargo.toml
Labels: Don't merge yet

#1992 fix(login): Set min size and increase size for phrase window
  ui/src/layouts/log_in/copy_seed_words.rs
  ui/src/layouts/log_in/create_or_recover.rs
  ui/src/layouts/log_in/enter_seed_words.rs
  ui/src/layouts/log_in/enter_username.rs
  ui/src/layouts/log_in/mod.rs
Labels: QA Tested, Ready to Merge

#1979 fix(chat): Dont stop profile fetching when one errors
  common/src/profile_update_channel.rs
Labels: Changes requested, Missing dev review, Don't merge yet

#1993 chore(release): release 1.0.5
  Cargo.lock
  Cargo.toml
Labels: Don't merge yet, Failed Automated Test
