Repository Satellite-im/Uplink, pull requests merged in 2024-02, with the labels that each got.

#1765 fix(chat): Fix user tagging in messages
  common/src/state/mod.rs
  common/src/state/pending_message.rs
  common/src/state/utils.rs
  common/src/testing/mock.rs
  common/src/warp_runner/ui_adapter/mod.rs
  kit/src/components/message/mod.rs
  kit/src/components/message_reply/mod.rs
  kit/src/layout/chatbar/mod.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/layouts/chats/data/msg_group.rs
  ui/src/layouts/chats/presentation/chat/pinned_messages/mod.rs
  ui/src/layouts/chats/presentation/chatbar/mod.rs
  ui/src/layouts/chats/presentation/messages/mod.rs
  ui/src/layouts/chats/presentation/sidebar/mod.rs
  ui/src/layouts/storage/send_files_layout/mod.rs
Labels: Waiting for CI

#1800 fix(VideoExtensions): Fix mkv preview
  common/src/lib.rs
Labels: Waiting for CI

#1794 update(FilePreview): Add option to listen to audio files
  common/src/lib.rs
  kit/src/components/embeds/file_embed/mod.rs
  kit/src/elements/file/mod.rs
  ui/src/layouts/storage/files_layout/file_preview.rs
  ui/src/layouts/storage/shared_component.rs
Labels: QA Tested, Ready to Merge

#1803 chore(keybinds): remove keybinds from experimental
  ui/src/components/settings/sidebar.rs
Labels: QA Tested, Waiting for CI

#1805 chore(img): fix build
  Cargo.toml
  icons/AU-flag.png
  icons/BL-flag.png
  icons/BR-flag.png
  icons/DE-flag.png
  icons/IN-flag.png
  icons/IT-flag.png
  icons/JP-flag.png
  icons/MX-flag.png
  icons/PT-flag.png
  icons/UK-flag.png
  icons/UR-flag.png
  icons/USA-flag.png
  ui/src/components/settings/sub_pages/about.rs
Labels: QA Tested, Don't merge yet

#1807 chore(release): 0.2.2
  Cargo.toml
Labels: Don't merge yet

#1808 chore(build): fix build
  Cargo.toml
  img/AU-flag.png
  img/BL-flag.png
  img/BR-flag.png
  img/DE-flag.png
  img/IN-flag.png
  img/IT-flag.png
  img/JP-flag.png
  img/MX-flag.png
  img/PT-flag.png
  img/UK-flag.png
  img/UR-flag.png
  img/USA-flag.png
  ui/extra/images/AU-flag.png
  ui/extra/images/BL-flag.png
  ui/extra/images/BR-flag.png
  ui/extra/images/DE-flag.png
  ui/extra/images/IN-flag.png
  ui/extra/images/IT-flag.png
  ui/extra/images/JP-flag.png
  ui/extra/images/MX-flag.png
  ui/extra/images/PT-flag.png
  ui/extra/images/UK-flag.png
  ui/extra/images/UR-flag.png
  ui/extra/images/USA-flag.png
  ui/src/components/settings/sub_pages/about.rs
Labels: Don't merge yet

#1809 chore(release): new build 0.2.2
  Cargo.toml
Labels: Don't merge yet

#1812 chore(flags): apply luis fix
  Cargo.toml
  ui/src/components/settings/sub_pages/about.rs
Labels: Don't merge yet

#1813 chore(release): update version to 0.2.2
  Cargo.toml
Labels: Don't merge yet

#1820 chore(lock): update version
  Cargo.lock
Labels: Don't merge yet, Waiting for CI

#1817 update(flags): use flags as images with wix updates
  ui/extra/images/flags/AU-flag.png
  ui/extra/images/flags/BL-flag.png
  ui/extra/images/flags/BR-flag.png
  ui/extra/images/flags/DE-flag.png
  ui/extra/images/flags/IN-flag.png
  ui/extra/images/flags/IT-flag.png
  ui/extra/images/flags/JP-flag.png
  ui/extra/images/flags/MX-flag.png
  ui/extra/images/flags/PT-flag.png
  ui/extra/images/flags/UK-flag.png
  ui/extra/images/flags/UR-flag.png
  ui/extra/images/flags/USA-flag.png
  ui/src/components/settings/styles.scss
  ui/src/components/settings/sub_pages/about.rs
  ui/wix/main.wxs
Labels: Don't merge yet, Failed Automated Test

#1822 chore(docs): add docs
  docs/release-flow.md
Labels: Don't merge yet

#1823 chore(docs): update release docs for wix installer
  docs/release-flow.md
Labels: Missing dev review, Don't merge yet

#1782 fix(chat): fix not escaping for inline codeblocks and url parsing issues
  kit/src/components/message/mod.rs
Labels: QA Tested, Ready to Merge

#1816 feat(recovery): Show error message if seed is wrong
  common/locales/en-US/main.ftl
  ui/src/layouts/log_in/enter_seed_words.rs
  ui/src/layouts/style.scss
Labels: Waiting for CI

#1829 task(icon): Update document-media.svg
  icons/src/icons/outline/document-media.svg
Labels: Missing dev review, Don't merge yet

#1828 task(icon): Update pin.svg
  icons/src/icons/outline/pin.svg
Labels: Waiting for CI

#1827 add(aria): adding aria labels for settings keybinds and others
  kit/src/elements/checkbox/mod.rs
  ui/src/components/settings/sub_pages/about.rs
  ui/src/components/settings/sub_pages/keybinds.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
Labels: Don't merge yet

#1830 add(aria): add aria label for input error on enter seed
  ui/src/layouts/log_in/enter_seed_words.rs
Labels: Don't merge yet

#1824 fix(chat): Change message text layout
  common/src/state/utils.rs
  kit/src/components/message/style.scss
Labels: QA Tested, Ready to Merge

#1775 feat(misc): Profile picture/banner split
  common/src/lib.rs
  common/src/profile_update_channel.rs
  common/src/state/mod.rs
  common/src/warp_runner/manager/commands/mod.rs
  common/src/warp_runner/manager/commands/multipass_commands.rs
  common/src/warp_runner/ui_adapter/mod.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/lib.rs
Labels: Waiting for CI

#1836 chore(log): remove log
  kit/src/components/message/mod.rs
Labels: Don't merge yet, Waiting for CI

#1831 update(Attachments): Improve attachments code, remove duplicates
  common/src/state/action.rs
  common/src/state/mod.rs
  ui/src/layouts/chats/mod.rs
  ui/src/layouts/chats/presentation/chatbar/mod.rs
  ui/src/layouts/chats/presentation/messages/coroutines.rs
Labels: Waiting for CI

#1825 update(Files): Add Preview for PDF and Code Files
  common/locales/en-US/main.ftl
  common/src/lib.rs
  common/src/utils/local_file_path.rs
  kit/src/components/embeds/file_embed/mod.rs
  ui/src/layouts/storage/files_layout/file_preview.rs
  ui/src/layouts/storage/files_layout/style.scss
  ui/src/layouts/storage/shared_component.rs
Labels: Changes requested

#1838 chore(rust): bump rust version
  .github/workflows/build-dmg-universal.yml
  .github/workflows/build-release-linux.yml
  .github/workflows/build-release-windows.yml
  .github/workflows/cargo.yml
  .github/workflows/ui-test-automation.yml
  Cargo.toml
  ui/build.rs
Labels: QA Override

#1832 fix(Markdown): Fix code block on pinned messages
  ui/src/layouts/chats/presentation/chat/pinned_messages/mod.rs
Labels: Waiting for CI

#1843 chore(bot): add ci to add/removel label
  .github/workflows/assigned-label.yml
Labels: Waiting for CI

#1839 chore(cargo): Update warp dependency
  .github/workflows/ui-test-automation.yml
  Cargo.lock
  Cargo.toml
  common/src/state/mod.rs
  ui/src/layouts/chats/data/msg_group.rs
  ui/src/lib.rs
  ui/src/utils/verify_valid_paths.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1852 chore(release): 0.2.3 release
  Cargo.lock
  Cargo.toml
Labels: Don't merge yet

#1725 task(groups): Group chat UI refactor
  Cargo.toml
  common/locales/en-US/main.ftl
  common/src/state/chats.rs
  common/src/state/mod.rs
  common/src/testing/mock.rs
  common/src/warp_runner/manager/commands/raygun_commands.rs
  common/src/warp_runner/ui_adapter/message_event.rs
  common/src/warp_runner/ui_adapter/mod.rs
  kit/src/elements/button/style.scss
  kit/src/layout/modal/mod.rs
  ui/src/layouts/chats/data/chat_data/active_chat/metadata.rs
  ui/src/layouts/chats/data/chat_data/active_chat/mod.rs
  ui/src/layouts/chats/data/chat_props.rs
  ui/src/layouts/chats/presentation/chat/controls.rs
  ui/src/layouts/chats/presentation/chat/edit_group.rs
  ui/src/layouts/chats/presentation/chat/group_settings.rs
  ui/src/layouts/chats/presentation/chat/mod.rs
  ui/src/layouts/chats/presentation/chat/topbar.rs
  ui/src/layouts/chats/presentation/sidebar/create_group.rs
  ui/src/layouts/chats/presentation/style.scss
  ui/src/layouts/chats/style.scss
Labels: Changes requested, Missing dev review, Don't merge yet, Failed Automated Test

#1854 fix(logs): Removes a logging message left in
  ui/src/layouts/chats/presentation/chat/mod.rs
Labels: QA Tested, Don't merge yet

#1859 add(aria): add aria labels for kit and ui elements
  kit/src/components/context_menu/mod.rs
  kit/src/components/embeds/youtube/mod.rs
  ui/src/components/files/upload_progress_bar/mod.rs
  ui/src/components/media/calling.rs
Labels: Ready to Merge

#1858 chore(bot): delete bot
  .github/workflows/avoid-typos.yml
  .github/workflows/new-ticket-label-issue.yml
Labels: Ready to Merge

#1863 chore(appium): exclude execution of automated tests on changes for some files
  .github/workflows/ui-test-automation.yml
Labels: Missing dev review, Don't merge yet

#1865 chore(appium): execute automated tests on locales changes
  .github/workflows/ui-test-automation.yml
Labels: Don't merge yet

#1857 fix(chat): Chatbar selection fix
  kit/src/elements/textarea/rich_editor_handler.js
  kit/src/layout/chatbar/mod.rs
  kit/src/layout/chatbar/style.scss
  kit/src/layout/chatbar/suggestion_scroll.js
Labels: Waiting for CI

#1869 fix(chat): add padding to chatlist and empty chat text
  common/locales/en-US/main.ftl
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/friends/style.scss
  ui/src/layouts/storage/send_files_layout/mod.rs
  ui/src/layouts/storage/send_files_layout/style.scss
Labels: Missing dev review, Don't merge yet

#1872 chore(debug): Don't link debug info for dev profile
  .cargo/config.toml
Labels: Ready to Merge

#1875 chore(cargo): Re-enable unwind when paniking
  Cargo.toml
Labels: Don't merge yet

#1880 chore(appium): replace default warp node on CI tests with script
  .github/workflows/ui-test-automation.yml
  utils/replace_node.ps1
  utils/replace_node.sh
Labels: Don't merge yet

#1879 fix(GroupSettings): Fix close group settings when change toggle
  ui/src/layouts/chats/presentation/chat/mod.rs
Labels: Waiting for CI

#1878 fix(contextmenu): dont show empty context menus
  kit/src/components/context_menu/context.js
Labels: Waiting for CI

#1883 fix(groups): Context menu renders behind group rename
  ui/src/layouts/chats/style.scss
Labels: Waiting for CI

#1874 fix(Shortcut): Fix black screen after shortcut to hide the app
  ui/src/utils/keyboard/shortcut_handlers/navigation.rs
Labels: Waiting for CI

#1888 chore(release): 0.2.4 release
  Cargo.lock
  Cargo.toml
Labels: Waiting for CI

#1891 chore(appium): save uplink logs as artifacts on failure
  .github/workflows/ui-test-automation.yml
Labels: Don't merge yet

#1889 fix(groups): add option to unset context-wrap width
  kit/src/components/context_menu/mod.rs
  kit/src/components/context_menu/style.scss
  ui/src/layouts/chats/presentation/chat/topbar.rs
Labels: Waiting for CI

#1892 update(aria): add dynamic aria label for chat messages
  kit/src/components/message/mod.rs
Labels: Don't merge yet
