Repository Satellite-im/Uplink, pull requests merged in 2024-01, with the labels that each got.

#1657 feat(keybinds): keyboard shortcuts
  common/locales/en-US/main.ftl
  common/src/state/action.rs
  common/src/state/default_keybinds.rs
  common/src/state/mod.rs
  common/src/state/settings.rs
  kit/src/components/mod.rs
  kit/src/components/tooltip_wrap/mod.rs
  kit/src/components/tooltip_wrap/style.scss
  ui/src/components/settings/sidebar.rs
  ui/src/components/settings/styles.scss
  ui/src/components/settings/sub_pages/about.rs
  ui/src/components/settings/sub_pages/keybinds.rs
  ui/src/components/shortcuts/change_font_size_shortcut/mod.rs
  ui/src/components/shortcuts/mod.rs
  ui/src/lib.rs
  ui/src/utils/keyboard/mod.rs
  ui/src/utils/keyboard/navigate_and_highlight_keybinds.js
  ui/src/utils/keyboard/shortcut_handlers/audio.rs
  ui/src/utils/keyboard/shortcut_handlers/font.rs
  ui/src/utils/keyboard/shortcut_handlers/mod.rs
  ui/src/utils/mod.rs
Labels: Missing dev review, Don't merge yet

#1641 feat(markdown): Markdown redo
  kit/src/components/message/mod.rs
  kit/src/style.scss
  ui/extra/assets/styles/prism-one-dark.css
  ui/src/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#1664 fix(mobile): add friend input width off screen
  ui/src/components/friends/style.scss
Labels: Waiting for CI

#1667 feat(Shortcuts): Add shortcut to toggle devmode and open the web inspector
  common/locales/en-US/main.ftl
  common/src/state/default_keybinds.rs
  common/src/state/settings.rs
  ui/src/components/settings/sub_pages/keybinds.rs
  ui/src/lib.rs
  ui/src/utils/keyboard/mod.rs
  ui/src/utils/keyboard/shortcut_handlers/dev.rs
  ui/src/utils/keyboard/shortcut_handlers/mod.rs
Labels: Don't merge yet, Waiting for CI

#1674 fix(bug): issues with resizing
  ui/src/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#1655 feat(login): begin adding account recovery page
  Cargo.lock
  Cargo.toml
  common/locales/en-US/main.ftl
  common/src/warp_runner/manager/commands/multipass_commands.rs
  common/src/warp_runner/mod.rs
  ui/Cargo.toml
  ui/src/layouts/log_in/copy_seed_words.rs
  ui/src/layouts/log_in/create_or_recover.rs
  ui/src/layouts/log_in/enter_seed_words.rs
  ui/src/layouts/log_in/enter_username.rs
  ui/src/layouts/log_in/entry_point.rs
  ui/src/layouts/log_in/mod.rs
  ui/src/layouts/log_in/recover_account.rs
  ui/src/layouts/mod.rs
  ui/src/layouts/style.scss
  ui/src/lib.rs
Labels: Missing dev review, Don't merge yet, Failed Automated Test

#1669 chore(cargo): Update warp dependency
  Cargo.lock
  Cargo.toml
Labels: QA Tested, Ready to Merge

#1678 chore(typos): fix typos
  ui/src/components/friends/add.rs
  ui/src/layouts/chats/data/chat_data/active_chat/messages.rs
Labels: QA Tested, Waiting for CI

#1681 chore(misc): Remove bip39 and use mnemonic utility function
  Cargo.lock
  ui/Cargo.toml
  ui/src/layouts/log_in/copy_seed_words.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1682 feat(Profile): Add the ability to view recovery seed on profile page.
  common/locales/en-US/main.ftl
  common/src/warp_runner/manager/commands/mod.rs
  common/src/warp_runner/manager/commands/tesseract_commands.rs
  common/src/warp_runner/manager/events.rs
  common/src/warp_runner/mod.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/components/settings/sub_pages/profile/style.scss
Labels: Don't merge yet, Failed Automated Test, missing fixing conflict

#1683 chore(release): release v0.2.0
  Cargo.toml
Labels: Missing dev review, Don't merge yet

#1684 fix(sidebar): favorite buttons get moved on sidebar close
  kit/src/layout/slimbar/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#1687 chore(docs): minor update
  README.md
Labels: QA Tested, Missing dev review, Don't merge yet

#1694 chore(docs): minor update
  README.md
Labels: QA Tested, Missing dev review, Don't merge yet

#1695 chore(docs): minor update
  README.md
Labels: Missing dev review, Don't merge yet

#1693 update(aria): add aria labels for settings and recovery screens
  kit/src/elements/select/mod.rs
  ui/src/components/debug_logger/mod.rs
  ui/src/components/settings/mod.rs
  ui/src/components/settings/sub_pages/about.rs
  ui/src/components/settings/sub_pages/accessibility.rs
  ui/src/components/settings/sub_pages/audio.rs
  ui/src/components/settings/sub_pages/developer.rs
  ui/src/components/settings/sub_pages/files.rs
  ui/src/components/settings/sub_pages/general.rs
  ui/src/components/settings/sub_pages/keybinds.rs
  ui/src/components/settings/sub_pages/licenses.rs
  ui/src/components/settings/sub_pages/messages.rs
  ui/src/components/settings/sub_pages/notifications.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/extension_browser/mod.rs
  ui/src/layouts/log_in/copy_seed_words.rs
  ui/src/layouts/log_in/create_or_recover.rs
  ui/src/layouts/log_in/enter_seed_words.rs
  ui/src/layouts/log_in/enter_username.rs
Labels: Missing dev review, Don't merge yet, Failed Automated Test, missing fixing conflict

#1696 update(locales): change/update Croatian, Bosnian, Serbian
  common/locales/bs-BA/bs-BA.ftl
  common/locales/hr-HR/hr-HR.ftl
  common/locales/sr-RS/sr-RS.ftl
Labels: QA Tested

#1691 fix(textarea): add checks for height bug in chat input
  kit/src/elements/textarea/event_listeners.js
  kit/src/elements/textarea/script.js
Labels: QA Tested, Ready to Merge

#1704 feat(LoadingIndicator): Added spinning loading indicator
  icons/src/icons/outline/loader.svg
  kit/src/elements/button/mod.rs
  kit/src/elements/input/mod.rs
  kit/src/elements/loader/mod.rs
  kit/src/elements/loader/style.scss
  kit/src/elements/mod.rs
  ui/src/layouts/chats/presentation/messages/mod.rs
  ui/src/layouts/log_in/entry_point.rs
Labels: Missing dev review, Don't merge yet, Waiting for CI

#1708 chore(ci): add js
  .github/workflows/avoid-typos.yml
Labels: Ready to Merge, QA Override

#1711 chore(workflow): add or remove linter failing label on PR
  .github/workflows/cargo.yml
Labels: Missing dev review, Don't merge yet

#1710 update(Storage): Do not move file position when rename it, just when upload new files
  common/src/warp_runner/manager/commands/constellation_commands.rs
Labels: QA Tested, Ready to Merge

#1701 chore(Replies): Clean up the UI for replies to make them more clear.
  kit/src/components/message_reply/mod.rs
  kit/src/components/message_reply/style.scss
  ui/src/layouts/chats/data/msg_group.rs
  ui/src/layouts/chats/presentation/messages/mod.rs
Labels: Ready to Merge

#1726 chore(workflows): add or remove invalid PR title label automatically
  .github/workflows/lint-PR-title.yml
Labels: QA Tested, Missing dev review, Don't merge yet

#1729 chore(locales): improve locale
  common/locales/en-US/main.ftl
Labels: QA Tested, Missing dev review, Don't merge yet, Failed Automated Test

#1728 update(ReplyMessage): Fix reply offscreen message
  kit/src/components/message_reply/style.scss
Labels: QA Tested, Ready to Merge

#1732 chore(release): release/v0.2.1
  Cargo.toml
Labels: Missing dev review, Don't merge yet

#1730 chore(cargo): Update warp dependency
  Cargo.lock
  Cargo.toml
  common/src/state/mod.rs
  common/src/testing/mock.rs
  common/src/warp_runner/manager/commands/raygun_commands.rs
  common/src/warp_runner/mod.rs
  ui/src/layouts/chats/presentation/messages/coroutines.rs
  ui/src/layouts/chats/presentation/messages/mod.rs
Labels: Don't merge yet, Waiting for CI

#1733 chore(script): add bash script for macos
  README.md
  macos-install_dependencies.sh
Labels: Missing dev review, Don't merge yet

#1738 chore(docs): improve formatting
  README.md
Labels: Missing dev review, Don't merge yet

#1740 chore(docs): minor read me updates
  ui/README.md
Labels: Missing dev review, Don't merge yet

#1742 chore(docs): improve grammar
  ui/docs/common-patterns.md
Labels: Missing dev review, Don't merge yet

#1741 chore(docs): remove empty files
  ui/docs/building/build.md
  ui/docs/building/linux.md
  ui/docs/building/macos.md
  ui/docs/building/production-build.md
  ui/docs/building/windows.md
Labels: Missing dev review, Don't merge yet

#1748 chore(ci): fix warning on workflow
  .github/workflows/ui-test-automation.yml
Labels: Don't merge yet, checking stuff

#1747 chore(docs): update formatting
  docs/dev_commands_cheatsheet.md
Labels: Missing dev review, Don't merge yet

#1727 fix(files): Move download/upload to new tasks
  Cargo.lock
  common/src/upload_file_channel.rs
  common/src/warp_runner/manager/commands/constellation_commands.rs
  common/src/warp_runner/manager/commands/raygun_commands.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/layouts/chats/presentation/chatbar/coroutines.rs
  ui/src/layouts/chats/presentation/messages/coroutines.rs
  ui/src/layouts/chats/presentation/quick_profile/mod.rs
  ui/src/layouts/log_in/copy_seed_words.rs
  ui/src/layouts/storage/files_layout/mod.rs
  ui/src/layouts/storage/functions.rs
  ui/src/lib.rs
  ui/src/utils/async_task_queue.rs
  ui/src/utils/mod.rs
Labels: QA Tested, Ready to Merge

#1752 fix(themes): change link color
  kit/src/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#1736 fix(groups): Fix search crashes
  common/src/state/mod.rs
Labels: Waiting for CI

#1750 fix(loading): use text color for fetching msg text
  ui/src/layouts/chats/presentation/style.scss
Labels: Waiting for CI

#1699 feat(Files): Preview videos files in Storage and Chats
  Cargo.lock
  common/src/lib.rs
  common/src/utils/clear_temp_files_dir.rs
  common/src/utils/img_dimensions_preview.rs
  common/src/utils/lifecycle.rs
  common/src/utils/local_file_path.rs
  common/src/utils/mod.rs
  kit/src/components/embeds/file_embed/mod.rs
  kit/src/components/embeds/file_embed/style.scss
  kit/src/components/message/mod.rs
  kit/src/elements/file/mod.rs
  kit/src/elements/file/style.scss
  ui/src/bootstrap.rs
  ui/src/components/crop_image_tool/circle_format_tool/mod.rs
  ui/src/components/crop_image_tool/rectangle_format_tool/mod.rs
  ui/src/components/files/attachments.rs
  ui/src/components/files/file_preview.rs
  ui/src/components/files/mod.rs
  ui/src/layouts/chats/presentation/messages/coroutines.rs
  ui/src/layouts/chats/presentation/messages/mod.rs
  ui/src/layouts/storage/files_layout/file_modal.rs
  ui/src/layouts/storage/files_layout/file_preview.rs
  ui/src/layouts/storage/files_layout/mod.rs
  ui/src/layouts/storage/functions.rs
  ui/src/layouts/storage/shared_component.rs
  ui/src/utils/async_task_queue.rs
  ui/src/utils/lifecycle.rs
  ui/src/utils/mod.rs
Labels: QA Tested, Ready to Merge

#1705 feat(chat): Chatbar markdown preview
  Cargo.lock
  kit/Cargo.toml
  kit/src/components/message/mod.rs
  kit/src/elements/textarea/markdown.scss
  kit/src/elements/textarea/mod.rs
  kit/src/elements/textarea/rich_editor_handler.js
  kit/src/elements/textarea/sync_data.js
  kit/src/elements/textarea/update_char_counter.js
  kit/src/layout/chatbar/mod.rs
  kit/src/layout/chatbar/suggestion_scroll.js
  ui/extra/assets/scripts/editor.js
  ui/src/misc_scripts.rs
Labels: Waiting for CI

#1751 fix(ui): change attachment text color to dark
  kit/src/components/embeds/file_embed/mod.rs
  kit/src/components/embeds/file_embed/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#1768 task(icon): update video asset
  icons/src/icons/outline/document-media.svg
Labels: Missing dev review, Don't merge yet

#1761 update(KeyBinds): Close inspector with same shortcut
  common/locales/bs-BA/bs-BA.ftl
  common/locales/en-US/main.ftl
  common/locales/sr-RS/sr-RS.ftl
  common/src/state/default_keybinds.rs
  common/src/state/settings.rs
  ui/src/components/settings/sub_pages/keybinds.rs
  ui/src/lib.rs
  ui/src/utils/keyboard/mod.rs
  ui/src/utils/keyboard/shortcut_handlers/dev.rs
  ui/src/utils/keyboard/shortcut_handlers/navigation.rs
Labels: QA Tested, Ready to Merge

#1753 fix(keybindings): add js to force a blur on successful keybind change
  ui/src/components/settings/sub_pages/keybinds.rs
Labels: QA Tested, Ready to Merge

#1772 chore(misc): Add env variable for list of addresses for shuttle discovery
  common/src/warp_runner/mod.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1773 fix(reload): disable reload hotkey to stop refresh breaking bug
  ui/src/layouts/chats/presentation/chat/mod.rs
  ui/src/layouts/chats/scripts/disable_reload_hotkeys.js
  ui/src/layouts/chats/scripts/mod.rs
Labels: QA Tested, Ready to Merge

#1776 fix(flags): fix flags on windows
  img/AU-flag.png
  img/BL-flag.png
  img/BR-flag.png
  img/DE-flag.png
  img/IN-flag.png
  img/IT-flag.png
  img/JP-flag.png
  img/MX-flag.png
  img/PT-flag.png
  img/UK-flag.png
  img/UR-flag.png
  img/USA-flag.png
  ui/src/components/settings/styles.scss
  ui/src/components/settings/sub_pages/about.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1777 chore(script): fix assistant.sh script
  assistant.sh
Labels: Missing dev review, Don't merge yet

#1778 chore(docs): add docs
  common/src/lib.rs
Labels: Missing dev review, Don't merge yet

#1739 fix(chat): Fix emoji reply and unify some stuff
  common/src/state/ui.rs
  kit/src/components/invisible_closer/mod.rs
  kit/src/components/invisible_closer/style.scss
  kit/src/elements/select/mod.rs
  kit/src/elements/select/style.scss
  native_extensions/emoji_selector/src/lib.rs
  ui/src/layouts/chats/presentation/chat/controls.rs
  ui/src/layouts/chats/presentation/style.scss
Labels: QA Tested, Ready to Merge

#1779 chore(logging): add error logging
  ui/src/utils/mod.rs
Labels: Missing dev review, Don't merge yet

#1771 chore(appium): use a custom warp node for CI automation tests
  .github/workflows/ui-test-automation.yml
  utils/replace_node.sh
Labels: Don't merge yet

#1780 chore(typos): fix typos
  ui/src/layouts/log_in/entry_point.rs
  ui/src/layouts/storage/files_layout/file_preview.rs
Labels: Waiting for CI

#1781 chore(icon): update icon when sharing DID
  ui/src/components/friends/friends_list/mod.rs
Labels: Don't merge yet, Waiting for CI

#1787 fix(chat): fix text color when replying to chat message
  kit/src/layout/chatbar/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#1788 fix(chat): fix focus on chat when editing group name
  ui/src/layouts/chats/presentation/chat/topbar.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1786 chore(appium): update ui automated tests to run on macos 14
  .github/workflows/ui-test-automation.yml
Labels: Don't merge yet

#1789 fix(chat): fix focus when creating group
  ui/src/layouts/chats/presentation/sidebar/create_group.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1790 fix(focus): fix focus when entering words on import account
  ui/src/layouts/log_in/enter_seed_words.rs
Labels: QA Tested, Missing dev review, Don't merge yet

#1793 fix(chat): fix focus on chat when editing group name - revert
  ui/src/layouts/chats/presentation/chat/topbar.rs
Labels: blocked

#1792 fix(chat): fix focus when creating group - revert
  ui/src/layouts/chats/presentation/sidebar/create_group.rs
Labels: blocked

#1798 chore(build): update build mac workflow to macos14
  .github/workflows/build-dmg-universal.yml
Labels: QA Tested, Don't merge yet

#1797 fix(Group): Fix search on create group chat
  kit/src/elements/input/mod.rs
  ui/src/layouts/chats/presentation/chat/topbar.rs
  ui/src/layouts/chats/presentation/sidebar/create_group.rs
Labels: QA Tested, Ready to Merge
