Repository Satellite-im/Uplink, pull requests merged in 2024-03, with the labels that each got.

#1884 chore(toast): Remove the toast crash fix to see what happens
  ui/src/layouts/chats/mod.rs
Labels: QA Tested, Ready to Merge

#1886 fix(Group): Fix crash on remove and add same member to the group
  ui/src/layouts/chats/presentation/chat/mod.rs
Labels: Failed Automated Test, Waiting for CI

#1846 feat(files): File transfer UI
  common/locales/en-US/main.ftl
  common/src/state/data_transfer.rs
  common/src/state/mod.rs
  common/src/state/scope_ids.rs
  common/src/upload_file_channel.rs
  common/src/warp_runner/manager/commands/constellation_commands.rs
  kit/src/components/nav/mod.rs
  kit/src/elements/button/mod.rs
  kit/src/elements/button/style.scss
  kit/src/layout/sidebar/mod.rs
  kit/src/style.scss
  ui/src/bootstrap.rs
  ui/src/components/file_transfer/mod.rs
  ui/src/components/file_transfer/style.scss
  ui/src/components/files/upload_progress_bar/mod.rs
  ui/src/components/mod.rs
  ui/src/components/settings/styles.scss
  ui/src/layouts/chats/presentation/messages/coroutines.rs
  ui/src/layouts/chats/presentation/sidebar/mod.rs
  ui/src/layouts/storage/files_layout/controller.rs
  ui/src/layouts/storage/files_layout/mod.rs
  ui/src/layouts/storage/functions.rs
  ui/src/layouts/storage/send_files_layout/mod.rs
  ui/src/lib.rs
  ui/src/utils/async_task_queue.rs
  ui/src/utils/download.rs
Labels: Waiting for CI

#1893 fix(Profile): Add loading spinner on update profile info
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/components/settings/sub_pages/profile/style.scss
Labels: blocked

#1876 task(files): Add failed msg to upload failing
  common/locales/en-US/main.ftl
  common/src/state/mod.rs
  kit/src/components/embeds/file_embed/mod.rs
  ui/src/lib.rs
Labels: QA Tested, Ready to Merge

#1899 add(aria): add a common aria label for spinner
  kit/src/elements/loader/mod.rs
Labels: Failed Automated Test, Waiting for CI

#1894 chore(cargo): Update warp dependency
  .github/workflows/ui-test-automation.yml
  Cargo.lock
  Cargo.toml
  common/src/state/chats.rs
  common/src/state/data_transfer.rs
  common/src/state/mod.rs
  common/src/state/pending_message.rs
  common/src/upload_file_channel.rs
  common/src/warp_runner/manager/commands/constellation_commands.rs
  common/src/warp_runner/manager/commands/raygun_commands.rs
  common/src/warp_runner/ui_adapter/message_event.rs
  kit/src/components/embeds/file_embed/mod.rs
  kit/src/components/message/mod.rs
  ui/src/layouts/chats/data/msg_group.rs
  ui/src/utils/async_task_queue.rs
Labels: QA Tested, Ready to Merge

#1902 update(files): Update toast for file preview
  common/locales/en-US/main.ftl
Labels: Waiting for CI

#1903 task(improvements): Improve chat modal styles
  kit/src/layout/modal/style.scss
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/friends/style.scss
  ui/src/layouts/storage/send_files_layout/mod.rs
  ui/src/layouts/storage/send_files_layout/style.scss
Labels: QA Tested, Ready to Merge

#1910 task(files): Improve upload error msg for storage limit
  common/locales/en-US/main.ftl
  common/src/state/mod.rs
  kit/src/components/embeds/file_embed/mod.rs
Labels: QA Tested, Ready to Merge

#1901 feat(files): disable files/directories that are being deleted
  ui/src/layouts/storage/files_layout/controller.rs
  ui/src/layouts/storage/functions.rs
  ui/src/layouts/storage/shared_component.rs
Labels: Waiting for CI

#1913 fix(ui): Change color for member count div in modal
  ui/src/layouts/storage/send_files_layout/style.scss
Labels: Waiting for CI

#1914 task(icon): Add none Icon
  icons/src/icons/outline/none.svg
Labels: Waiting for CI

#1908 fix(GroupSettings): Fix group settings toggle problem
  ui/src/layouts/chats/presentation/chat/group_settings.rs
Labels: Waiting for CI

#1916 fix(Loader): Fix loader on buttons
  kit/src/elements/button/mod.rs
  kit/src/elements/button/style.scss
  kit/src/elements/loader/style.scss
Labels: Ready for testing, Don't merge yet

#1919 fix(Loader): fix overlay shadow for loader in profile page
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/components/settings/sub_pages/profile/style.scss
Labels: QA Tested, Ready to Merge

#1915 task(recovery): Redo seed enter recovery page
  common/locales/en-US/main.ftl
  kit/src/elements/input/mod.rs
  ui/src/components/settings/sub_pages/profile/mod.rs
  ui/src/layouts/log_in/copy_seed_words.rs
  ui/src/layouts/log_in/enter_seed_handler.js
  ui/src/layouts/log_in/enter_seed_words.rs
  ui/src/layouts/log_in/style.scss
  ui/src/layouts/style.scss
Labels: Waiting for CI

#1922 chore(deps): Drop unused tokio-util dep
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  ui/Cargo.toml
Labels: Ready to Merge

#1924 fix(utils): Remove a log statement in lang checker
  utils/lang_checker.py
Labels: QA Override, Waiting for CI

#1917 chore(cargo): Update dependencies
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  common/src/language/mod.rs
  common/src/notifications.rs
  common/src/testing/mock.rs
  common/src/warp_runner/manager/commands/constellation_commands.rs
  common/src/warp_runner/manager/commands/multipass_commands.rs
  icons/Cargo.toml
  kit/Cargo.toml
  kit/src/components/message/mod.rs
  ui/Cargo.toml
  ui/src/components/crop_image_tool/circle_format_tool/mod.rs
  ui/src/components/crop_image_tool/mod.rs
  ui/src/components/crop_image_tool/rectangle_format_tool/mod.rs
  ui/src/layouts/chats/presentation/messages/mod.rs
  ui/src/layouts/storage/functions.rs
  ui/src/utils/auto_updater.rs
  ui/src/utils/clipboard/clipboard_data.rs
Labels: Waiting for CI

#1927 chore(release): 0.2.5 release
  Cargo.lock
  Cargo.toml
Labels: Don't merge yet

#1909 chore(msg): UUID pending msg tracking
  common/src/state/chats.rs
  common/src/state/mod.rs
  common/src/state/pending_message.rs
  common/src/warp_runner/manager/commands/raygun_commands.rs
  common/src/warp_runner/ui_adapter/message_event.rs
  ui/src/layouts/chats/data/chatbar/mod.rs
  ui/src/layouts/chats/presentation/chatbar/coroutines.rs
  ui/src/layouts/chats/presentation/chatbar/mod.rs
  ui/src/layouts/chats/presentation/quick_profile/mod.rs
  ui/src/layouts/storage/files_layout/mod.rs
  ui/src/utils/async_task_queue.rs
Labels: QA Tested, Ready to Merge

#1931 chore(Colors): Changed colors to more closely match mockups
  kit/src/components/embeds/file_embed/style.scss
  kit/src/components/message/style.scss
  kit/src/components/message_divider/style.scss
  kit/src/elements/button/style.scss
  kit/src/elements/file/style.scss
  kit/src/elements/radio_list/style.scss
  kit/src/elements/select/style.scss
  kit/src/layout/chatbar/style.scss
  kit/src/style.scss
  ui/src/layouts/chats/presentation/style.scss
  ui/src/layouts/storage/send_files_layout/style.scss
Labels: QA Tested, Missing dev review, Don't merge yet

#1928 fix(groups): use group members instead of friend list for removing them
  ui/src/layouts/chats/presentation/chat/edit_group.rs
Labels: Failed Automated Test, Waiting for CI

#1933 chore(appium): add third uplink instance on ui chats tests
  .github/workflows/ui-test-automation.yml
Labels: Waiting for CI

#1935 chore(cargo): Update warp dependency
  .github/workflows/ui-test-automation.yml
  Cargo.lock
  Cargo.toml
  common/src/lib.rs
  common/src/warp_runner/mod.rs
  ui/src/utils/async_task_queue.rs
  utils/replace_node.ps1
  utils/replace_node.sh
Labels: Missing dev review, Don't merge yet, being tested

#1937 chore(copy): update copy
  common/locales/bs-BA/bs-BA.ftl
  common/locales/de/main.ftl
  common/locales/en-US/main.ftl
  common/locales/es-MX/main.ftl
  common/locales/hr-HR/hr-HR.ftl
  common/locales/pl/pl.ftl
  common/locales/pt-BR/main.ftl
  common/locales/pt-PT/main.ftl
  common/locales/sr-RS/sr-RS.ftl
  ui/deb/DEBIAN/control
  ui/src/components/topbar/release_info/mod.rs
  ui/src/components/topbar/release_info/style.scss
Labels: Don't merge yet

#1940 chore(appium): use second instance on test mac
  .github/workflows/ui-test-automation.yml
Labels: Don't merge yet

#1923 task(files): Upload/Download UI rework
  common/locales/en-US/main.ftl
  common/src/state/data_transfer.rs
  common/src/upload_file_channel.rs
  common/src/warp_runner/manager/commands/constellation_commands.rs
  ui/src/components/file_transfer/mod.rs
  ui/src/components/file_transfer/style.scss
  ui/src/layouts/storage/functions.rs
Labels: Don't merge yet, Waiting for CI

#1943 update(flags): fix MX flag on settings about
  ui/extra/images/flags/MX-flag.png
Labels: Don't merge yet

#1930 fix(chat): Chatbar + edit focus and style
  kit/src/components/message/style.scss
  kit/src/elements/textarea/mod.rs
  kit/src/elements/textarea/rich_editor_handler.js
Labels: Waiting for CI

#1942 feat(chat): Chat upload rework
  common/src/state/chats.rs
  common/src/state/mod.rs
  common/src/state/pending_message.rs
  common/src/warp_runner/ui_adapter/message_event.rs
  kit/src/components/embeds/file_embed/mod.rs
  kit/src/components/embeds/file_embed/style.scss
  kit/src/components/message/mod.rs
  ui/src/layouts/chats/data/chat_data/mod.rs
  ui/src/layouts/chats/data/msg_group.rs
  ui/src/layouts/chats/presentation/chat/mod.rs
  ui/src/layouts/chats/presentation/chatbar/coroutines.rs
  ui/src/layouts/chats/presentation/chatbar/mod.rs
  ui/src/layouts/chats/presentation/messages/mod.rs
  ui/src/lib.rs
  ui/src/utils/async_task_queue.rs
Labels: checking stuff

#1946 feat(settings): Implement missing calltimer setting
  common/src/state/ui.rs
  ui/src/components/media/calling.rs
  ui/src/components/settings/sub_pages/audio.rs
Labels: Failed Automated Test, Waiting for CI

#1950 feat(chat): Impl editing last message key shortcut
  kit/src/layout/chatbar/mod.rs
  ui/src/layouts/chats/data/chat_data/active_chat/messages.rs
  ui/src/layouts/chats/data/chat_data/active_chat/mod.rs
  ui/src/layouts/chats/data/chat_data/mod.rs
  ui/src/layouts/chats/presentation/chat/mod.rs
  ui/src/layouts/chats/presentation/chatbar/mod.rs
  ui/src/layouts/chats/presentation/messages/mod.rs
Labels: QA Tested, Ready to Merge

#1952 add(aria): aria labels for share did and color swatch
  kit/src/components/swatch/mod.rs
  ui/src/components/friends/friends_list/mod.rs
  ui/src/components/settings/sub_pages/accessibility.rs
Labels: Don't merge yet

#1951 fix(themes): Text selection color
  kit/src/elements/textarea/markdown.scss
  kit/src/style.scss
  ui/src/layouts/style.scss
Labels: QA Tested, Ready to Merge

#1953 feat(chat): Clicking outside will stop editing msg
  kit/src/components/message/mod.rs
  kit/src/components/message/style.scss
Labels: QA Tested, Ready to Merge
